import {verifyArithmeticQuestion} from './arithmetic.mjs';
export const GRADES=['國小三年級','國小四年級','國小五年級','國小六年級','國中一年級','國中二年級','國中三年級'];
export const SUBJECTS=['國語／國文','英語','數學','自然科學','社會','本土語文','藝術','健康與體育','綜合活動','資訊科技','生活科技','校本課程'];
export const RARITIES={common:{label:'普通',level:1},rare:{label:'稀有',level:2},epic:{label:'史詩',level:3}};
export const TOYS=[{id:'bear',rarity:'common',name:'焦糖小熊',color:'#bd8c5f',icon:'🐻',note:'把每一份努力，抱在懷裡。'},{id:'bunny',rarity:'epic',name:'月光小兔',color:'#e5d2bb',icon:'🐰',note:'帶著好奇，跳向新的發現。'},{id:'cat',rarity:'rare',name:'森林小貓',color:'#89ae93',icon:'🐱',note:'慢慢探索，也是一種勇敢。'}];
export const FESTIVALS={moon:{name:'中秋・月光收藏季',short:'月光中秋',color:'#2e4263',decor:'月亮與星星'},halloween:{name:'萬聖・奇想派對',short:'奇想萬聖',color:'#583d68',decor:'南瓜與小星星'},christmas:{name:'聖誕・冬日心願',short:'冬日聖誕',color:'#366557',decor:'聖誕樹與禮物'},spring:{name:'新春・福氣收藏',short:'福氣新春',color:'#864c41',decor:'燈籠與金色星星'},none:{name:'日常・小小收藏家',short:'日常',color:'#778e80',decor:'展示台'}};
export function uid(){return globalThis.crypto.randomUUID()}
export function seedState(empty=false){return {version:1,classes:empty?[]:[{id:'c1',name:'三年甲班',grade:GRADES[0],code:'DEMO301',cost:3,festival:'moon',eventActive:true}],students:empty?[]:['小宇','小晴','小安','小禾','小恩','小樂','小澄','小米','小森','小月','小辰','小橙'].map((name,i)=>({id:'s'+(i+1),name,number:i+1,group:i%3+1,classId:'c1',balance:[18,25,12,9,32,16,20,8,15,24,11,17][i]})),ledger:[],inventory:empty?[]:[{id:'starter1',studentId:'s1',kind:'bear',earnedAt:Date.now(),source:'示範收藏'},{id:'starter2',studentId:'s1',kind:'bunny',earnedAt:Date.now(),source:'示範收藏'},{id:'starter3',studentId:'s1',kind:'cat',earnedAt:Date.now(),source:'示範收藏'}],rooms:empty?{}:{s1:{wall:'mint',placements:[{itemId:'starter1',x:-1.3,z:.4,rotation:0},{itemId:'starter2',x:0,z:.4,rotation:0},{itemId:'starter3',x:1.3,z:.4,rotation:0}],decorations:[],theme:'moon'}},assignments:[],submissions:[],sessions:[],processed:[]}}
export function check(condition,message){if(!condition)throw new Error(message)}
function text(value,max=200){check(typeof value==='string'&&value.trim().length>0&&value.length<=max,'請填寫有效內容');return value.trim()}
function int(value,min,max){check(Number.isInteger(value)&&value>=min&&value<=max,'數量超出允許範圍');return value}
function student(s,id){const x=s.students.find(x=>x.id===id);check(x,'找不到學生');return x}
function owner(actor,id){check(actor.role==='student'&&actor.studentId===id,'僅能操作自己的資料')}
export function applyAction(previous,a,actor,{now=Date.now(),id=uid}={}){
 check(a&&typeof a.type==='string'&&typeof a.requestId==='string'&&a.requestId.length<=80,'缺少操作識別碼');
 if(previous.processed.includes(a.requestId))return previous;
 const s=structuredClone(previous);const teacher=()=>check(actor.role==='teacher','需要老師權限');
 const addLedger=(st,amount,reason,type='grant',batch=a.requestId)=>{st.balance+=amount;s.ledger.unshift({id:id(),studentId:st.id,classId:st.classId,amount,reason,type,batch,at:now,by:actor.name||'老師'});};
 switch(a.type){
  case 'createClass':teacher();s.classes.push({id:a.classId||id(),name:text(a.name,30),grade:GRADES.includes(a.grade)?a.grade:GRADES[0],code:a.code||id().slice(0,8).toUpperCase(),cost:3,festival:'none',eventActive:false});break;
  case 'registration':{teacher();const c=s.classes.find(c=>c.id===a.classId);check(c,'找不到班級');c.registrationOpen=!!a.open;break;}
  case 'addStudent':{teacher();check(s.classes.some(c=>c.id===a.classId),'找不到班級');s.students.push({id:a.studentId||id(),name:text(a.name,20),number:s.students.filter(x=>x.classId===a.classId).length+1,group:1,classId:a.classId,balance:0});break;}
  case 'grant':{teacher();int(a.amount,-100,100);check(a.amount!==0,'數量不能為零');const ids=[...new Set(a.ids)];check(ids.length>0&&ids.length<=100,'請選擇學生');const reason=text(a.reason,100);ids.map(x=>student(s,x)).forEach(st=>{check(st.balance+a.amount>=0,st.name+'的代幣不足，無法扣除');addLedger(st,a.amount,reason,a.amount<0?'adjust':'grant')});break;}
  case 'undo':{teacher();const rows=s.ledger.filter(x=>x.batch===a.batch&&['grant','adjust'].includes(x.type));check(rows.length&&!rows.some(x=>x.reversed),'這筆發放已撤銷或不能撤銷');for(const row of rows){const st=student(s,row.studentId);check(st.balance-row.amount>=0,st.name+'已使用代幣，無法完整撤銷');row.reversed=true;addLedger(st,-row.amount,'撤銷：'+row.reason,'reversal')}break;}
  case 'settings':{teacher();const c=s.classes.find(c=>c.id===a.classId);check(c,'找不到班級');c.cost=int(a.cost,1,100);check(a.festival in FESTIVALS,'無效主題');c.festival=a.festival;c.eventActive=!!a.eventActive;break;}
  case 'saveRoom':{owner(actor,a.studentId);const r=a.room;check(['mint','blue','pink','cream'].includes(r.wall),'無效牆面');check(r.theme in FESTIVALS,'無效主題');check(Array.isArray(r.placements)&&r.placements.length<=40,'房間最多擺放 40 件');const seen=new Set();for(const p of r.placements){check(s.inventory.some(i=>i.id===p.itemId&&i.studentId===a.studentId)&&!seen.has(p.itemId),'只能擺放自己擁有的寶物');seen.add(p.itemId);check([p.x,p.z,p.rotation].every(Number.isFinite)&&Math.abs(p.x)<=2.1&&p.z>=-1.6&&p.z<=1.6,'擺放位置超出房間')};const c=s.classes.find(x=>x.id===student(s,a.studentId).classId);const old=s.rooms[a.studentId];if(r.theme!==old?.theme)check(r.theme==='none'||c.eventActive&&c.festival===r.theme,'目前未開放此節慶主題');s.rooms[a.studentId]={wall:r.wall,theme:r.theme,placements:r.placements.map(p=>({itemId:p.itemId,x:p.x,z:p.z,rotation:p.rotation}))};break;}
  case 'saveAssignment':{teacher();check(s.classes.some(c=>c.id===a.classId),'找不到班級');const old=s.assignments.find(q=>q.id===a.assignment.id);check(!old||old.status!=='published','已發布的題目不可直接修改');const q=a.assignment;check(GRADES.includes(q.grade),'請選擇年級');text(q.subject,30);check(Array.isArray(q.questions)&&q.questions.length>0&&q.questions.length<=20,'請提供 1–20 題');const questions=q.questions.map(x=>{check(['choice','short','work'].includes(x.type),'無效題型');const item={type:x.type,prompt:text(x.prompt,2000),answer:text(x.answer,2000),explanation:typeof x.explanation==='string'?x.explanation.slice(0,3000):''};if(x.type==='choice'){check(Array.isArray(x.options)&&x.options.length===4,'選擇題需要四個選項');item.options=x.options.map(o=>text(o,500));check(['A','B','C','D'].includes(x.answer),'答案請填 A、B、C 或 D')}return verifyArithmeticQuestion(item)});const entry={id:q.id||id(),classId:a.classId,title:text(q.title,100),grade:q.grade,subject:q.subject,unit:text(q.unit,100),status:q.status==='published'?'published':'draft',questions,rewardMode:q.rewardMode==='perQuestion'||q.reward===undefined?'perQuestion':'custom',reward:int(q.rewardMode==='perQuestion'?questions.length:q.reward??questions.length,0,100),createdAt:old?.createdAt||now};if(old)s.assignments=s.assignments.filter(x=>x.id!==old.id);s.assignments.unshift(entry);break;}
  case 'submit':{owner(actor,a.studentId);const st=student(s,a.studentId);const q=s.assignments.find(x=>x.id===a.assignmentId&&x.classId===st.classId&&x.status==='published');check(q,'找不到已發布的任務');check(!s.submissions.some(x=>x.studentId===st.id&&x.assignmentId===q.id),'已經繳交過這份任務');check(Array.isArray(a.answers)&&a.answers.length===q.questions.length&&a.answers.every(x=>typeof x==='string'&&x.trim()&&x.length<=3000),'請完成所有題目');check(q.questions.every((question,i)=>question.type!=='choice'||['A','B','C','D'].includes(a.answers[i])),'選擇題答案必須為 A–D');s.submissions.unshift({id:id(),studentId:st.id,assignmentId:q.id,answers:a.answers,at:now,status:'pending'});break;}
  case 'publishAnalysis':{teacher();const sub=s.submissions.find(x=>x.id===a.submissionId);check(sub,'找不到作答');sub.publishedAnalysis=text(a.analysis,20000);sub.analysisPublishedAt=now;s.teacherAIResults||={};s.teacherAIResults[sub.id]||={};s.teacherAIResults[sub.id].studentFeedback={value:sub.publishedAnalysis,at:now,format:'student-v1'};break;}
  case 'updateReview':{teacher();const sub=s.submissions.find(x=>x.id===a.submissionId);check(sub&&sub.status==='reviewed','此作答尚未發布回饋');const q=s.assignments.find(x=>x.id===sub.assignmentId);check(q,'找不到任務');check(Array.isArray(a.itemFeedback)&&a.itemFeedback.length===q.questions.length,'請提供每一題的回饋');sub.itemFeedback=a.itemFeedback.map(value=>text(value,2000));sub.feedback=text(a.feedback,2000);sub.score=int(a.score,0,100);sub.reviewUpdatedAt=now;break;}
  case 'review':{teacher();const sub=s.submissions.find(x=>x.id===a.submissionId);check(sub&&sub.status==='pending','此作答已批閱或不存在');sub.feedback=text(a.feedback,2000);sub.score=int(a.score,0,100);sub.status='reviewed';const q=s.assignments.find(x=>x.id===sub.assignmentId);check(q,'找不到任務');if(a.itemFeedback!==undefined){check(Array.isArray(a.itemFeedback)&&a.itemFeedback.length===q.questions.length,'請提供每一題的回饋');sub.itemFeedback=a.itemFeedback.map(value=>text(value,2000))}const reward=int(a.reward??q.reward??q.questions.length,0,100);sub.reward=reward;if(reward)addLedger(student(s,sub.studentId),reward,'完成任務：'+q.title,'task');break;}
  case 'startGame':{owner(actor,a.studentId);const st=student(s,a.studentId);const c=s.classes.find(x=>x.id===st.classId);check(!s.sessions.some(x=>x.studentId===st.id&&x.status==='active'),'請先完成目前的夾取');check(st.balance>=c.cost,'代幣不足，繼續累積課堂獎勵吧');addLedger(st,-c.cost,'夾娃娃機入場','play');s.sessions.push({id:a.sessionId||id(),studentId:st.id,seed:a.seed>>>0,status:'active',at:now});break;}
  case 'finishGame':{owner(actor,a.studentId);check(actor.verifiedGame===true,'遊戲結果必須經過物理驗證');const g=s.sessions.find(x=>x.id===a.sessionId&&x.studentId===a.studentId);check(g,'找不到遊戲');check(g.status==='active','遊戲已結算');check(Array.isArray(a.prizes)&&a.prizes.every(k=>TOYS.some(t=>t.id===k))&&a.prizes.length<=12,'無效獎品');g.status='finished';g.prizes=a.prizes;for(const kind of a.prizes)s.inventory.push({id:id(),studentId:a.studentId,kind,earnedAt:now,source:'夾娃娃機'});break;}
  default:throw new Error('不支援的操作');
 }
 s.processed.push(a.requestId);return s;
}
