import {questionCount,questionsSchema,gradingSchema,gradingPrompt,parseGrading} from './ai-tasks.mjs';
import {requestGemini,AIError} from './gemini.mjs';
import {initializeApp} from 'firebase-admin/app';
import {getFirestore} from 'firebase-admin/firestore';
import {onCall,HttpsError} from 'firebase-functions/v2/https';
import {defineSecret,defineString,defineBoolean} from 'firebase-functions/params';
import {randomBytes,randomUUID,createCipheriv,createDecipheriv} from 'node:crypto';
import RAPIER from '@dimforge/rapier3d-compat';
import {applyAction,seedState,GRADES} from './domain.mjs';
import {simulate,validateTarget} from './physics.mjs';
initializeApp();const db=getFirestore();
const KEY_ENCRYPTION_KEY=defineSecret('KEY_ENCRYPTION_KEY');
const AI_ENABLED=defineBoolean('AI_ENABLED',{default:false});
const GEMINI_MODEL=defineString('GEMINI_MODEL',{default:'gemini-3.5-flash-lite'});
const opts={region:'asia-east1',maxInstances:3,enforceAppCheck:true,timeoutSeconds:60,memory:'512MiB'};
const rapierReady=RAPIER.init();
const requireAuth=r=>{if(!r.auth)throw new HttpsError('unauthenticated','請先登入');return r.auth.uid};
const requireTeacher=r=>{const id=requireAuth(r);if(r.auth.token.teacher!==true)throw new HttpsError('permission-denied','此功能僅供教師使用');return id};
const actionTeacher=new Set(['registration','createClass','addStudent','grant','undo','settings','saveAssignment','review']);
const actionStudent=new Set(['saveRoom','submit','startGame','finishGame']);
function safeId(value){if(typeof value!=='string'||!/^[A-Za-z0-9_-]{1,128}$/.test(value))throw new HttpsError('invalid-argument','無效的識別碼');return value}
import {studentView} from './views.mjs';
function writeState(tx,owner,state){if(Buffer.byteLength(JSON.stringify(state))>700000)throw new HttpsError('resource-exhausted','此試行教室的紀錄容量已接近上限，請管理者匯出並擴充資料結構後繼續。');tx.set(db.doc('workspaces/'+owner),{state});for(const st of state.students)if(st.authenticated)tx.set(db.doc('studentViews/'+st.id),{state:studentView(state,st.id)});}
export const classroomAction=onCall(opts,async r=>{const caller=requireAuth(r),a={...r.data};safeId(a.requestId);const teacher=r.auth.token.teacher===true;if(!(teacher?actionTeacher:actionStudent).has(a.type))throw new HttpsError('permission-denied','此身分無法執行這個操作');let owner=caller;if(!teacher){const member=await db.doc('members/'+caller).get();if(!member.exists)throw new HttpsError('failed-precondition','請先加入班級');owner=member.data().teacherUid;a.studentId=caller;}const ref=db.doc('workspaces/'+owner);const actor={role:teacher?'teacher':'student',studentId:caller,name:teacher?'班級老師':'學生'};let prizes;
 if(a.type==='createClass'){a.classId=randomUUID();a.code=randomBytes(8).toString('hex').toUpperCase()}
 if(a.type==='addStudent')a.studentId=randomUUID();
 if(a.type==='startGame'){a.seed=randomBytes(4).readUInt32LE();a.sessionId=randomUUID()}
 if(a.type==='finishGame'){
  const target=validateTarget(a.target);safeId(a.sessionId);
  const game=await db.runTransaction(async tx=>{const snap=await tx.get(ref);const s=snap.data()?.state;const g=s?.sessions.find(x=>x.id===a.sessionId&&x.studentId===caller);if(!g)throw new HttpsError('not-found','找不到這局遊戲');if(g.status==='finished')return g;if(!g.target){g.target=target;tx.set(ref,{state:s})}return g});
  if(game.status==='finished')return {ok:true,prizes:game.prizes||[]};
  await rapierReady;prizes=simulate(RAPIER,game.seed,game.target);a.prizes=prizes;actor.verifiedGame=true;
 }
 try{return await db.runTransaction(async tx=>{const snap=await tx.get(ref);const state=snap.data()?.state||seedState(true);if(a.type==='finishGame'){const g=state.sessions.find(x=>x.id===a.sessionId&&x.studentId===caller);if(g?.status==='finished')return{ok:true,prizes:g.prizes||[]}}
  if(a.type==='addStudent'&&state.students.length>=100)throw new Error('試行版本每位老師最多管理 100 位學生');
  const next=applyAction(state,a,actor);writeState(tx,owner,next);if(a.type==='createClass')tx.create(db.doc('classCodes/'+a.code),{teacherUid:owner,classId:a.classId,registrationOpen:false});if(a.type==='registration'){const c=next.classes.find(c=>c.id===a.classId);tx.set(db.doc('classCodes/'+c.code),{teacherUid:owner,classId:c.id,registrationOpen:c.registrationOpen})}return{ok:true,...(a.type==='finishGame'?{prizes}:{}),...(a.type==='createClass'?{classId:a.classId}:{})};});}catch(e){if(e instanceof HttpsError)throw e;throw new HttpsError('failed-precondition',e.message||'操作未完成，請重試');}
});
export const joinClass=onCall(opts,async r=>{const user=requireAuth(r);if(r.auth.token.teacher)throw new HttpsError('failed-precondition','教師帳號不能以學生身分加入');const code=String(r.data.code||'').trim().toUpperCase();const name=String(r.data.name||'').trim();if(!/^[A-F0-9]{16}$/.test(code)||!name||name.length>20)throw new HttpsError('invalid-argument','請填寫有效班級代碼與暱稱');const rate=db.doc('joinAttempts/'+user);await db.runTransaction(async tx=>{const snap=await tx.get(rate);const v=snap.data();if(v&&Date.now()-v.at<5000)throw new HttpsError('resource-exhausted','請稍後再試');tx.set(rate,{at:Date.now()})});return db.runTransaction(async tx=>{const member=await tx.get(db.doc('members/'+user));if(member.exists)throw new HttpsError('already-exists','已加入班級，如需轉班請聯絡老師');const c=await tx.get(db.doc('classCodes/'+code));if(!c.exists)throw new HttpsError('not-found','班級代碼無效');const{teacherUid,classId}=c.data();const workspace=await tx.get(db.doc('workspaces/'+teacherUid));const state=workspace.data()?.state;if(!state||state.students.length>=100)throw new HttpsError('resource-exhausted','班級暫時無法加入');const next=applyAction(state,{type:'addStudent',studentId:user,name,classId,requestId:randomUUID()},{role:'teacher'});next.students.find(s=>s.id===user).authenticated=true;tx.create(db.doc('members/'+user),{teacherUid,classId});writeState(tx,teacherUid,next);return{ok:true}})});
function encryptionKey(){const b=Buffer.from(KEY_ENCRYPTION_KEY.value(),'base64');if(b.length!==32)throw new HttpsError('failed-precondition','管理者尚未設定有效的加密金鑰');return b}
function encrypt(key,uid){const iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',encryptionKey(),iv);cipher.setAAD(Buffer.from(uid));const ciphertext=Buffer.concat([cipher.update(key,'utf8'),cipher.final()]);return{iv:iv.toString('base64'),ciphertext:ciphertext.toString('base64'),tag:cipher.getAuthTag().toString('base64')}}
async function decrypt(uid){const snap=await db.doc('teacherSecrets/'+uid).get();if(!snap.exists)throw new HttpsError('failed-precondition','請先在 AI 設定儲存教師金鑰');try{const d=snap.data(),cipher=createDecipheriv('aes-256-gcm',encryptionKey(),Buffer.from(d.iv,'base64'));cipher.setAAD(Buffer.from(uid));cipher.setAuthTag(Buffer.from(d.tag,'base64'));return Buffer.concat([cipher.update(Buffer.from(d.ciphertext,'base64')),cipher.final()]).toString('utf8')}catch{throw new HttpsError('failed-precondition','金鑰無法解密，請重新儲存')}}
export const saveTeacherKey=onCall({...opts,secrets:[KEY_ENCRYPTION_KEY]},async r=>{const uid=requireTeacher(r),key=r.data.key;if(typeof key!=='string'||key.length<20||key.length>512||/\s/.test(key))throw new HttpsError('invalid-argument','請貼上完整的 API Key');await db.doc('teacherSecrets/'+uid).set({...encrypt(key,uid),updatedAt:Date.now()});return{ok:true}});
export const deleteTeacherKey=onCall(opts,async r=>{const uid=requireTeacher(r);await db.doc('teacherSecrets/'+uid).delete();return{ok:true}});
export const teacherKeyStatus=onCall(opts,async r=>{const uid=requireTeacher(r);const s=await db.doc('teacherSecrets/'+uid).get();return{configured:s.exists,enabled:AI_ENABLED.value(),model:GEMINI_MODEL.value(),updatedAt:s.data()?.updatedAt||null}});
async function quota(uid){await db.runTransaction(async tx=>{const ref=db.doc('aiUsage/'+uid),snap=await tx.get(ref),d=snap.data()||{};const day=new Date().toISOString().slice(0,10);if(Date.now()-(d.at||0)<10000)throw new HttpsError('resource-exhausted','請稍候 10 秒再使用 AI');const count=d.day===day?d.count:0;if(count>=50)throw new HttpsError('resource-exhausted','已達本系統每日 50 次的教師使用上限');tx.set(ref,{day,count:count+1,at:Date.now()})})}
async function gemini(uid,prompt,json=false,schema){if(!AI_ENABLED.value())throw new HttpsError('failed-precondition','管理者尚未啟用教師 AI，請完成 Firebase 設定');const key=await decrypt(uid);await quota(uid);try{return await requestGemini({key,model:GEMINI_MODEL.value(),prompt,json,schema})}catch(e){if(e instanceof AIError)throw new HttpsError(e.code,e.message);throw new HttpsError('internal','AI 請求無法完成')}}
export const testTeacherKey=onCall({...opts,secrets:[KEY_ENCRYPTION_KEY]},async r=>{const uid=requireTeacher(r);const start=Date.now();await gemini(uid,'請只回答：連線成功');return{ok:true,model:GEMINI_MODEL.value(),latencyMs:Date.now()-start,testedAt:Date.now()}});
async function saveAIResult(uid,id,mode,value){const ref=db.doc('workspaces/'+uid);await db.runTransaction(async tx=>{const snap=await tx.get(ref),state=snap.data()?.state;if(!state?.submissions.some(x=>x.id===id))throw new HttpsError('not-found','找不到作答');const results=state.teacherAIResults||{};results[id]={...(results[id]||{}),[mode]:{value,at:Date.now()}};tx.update(ref,{'state.teacherAIResults':results})});return value}
export const teacherAI=onCall({...opts,secrets:[KEY_ENCRYPTION_KEY]},async r=>{const uid=requireTeacher(r),d=r.data||{};if(d.mode==='questions'){let count;try{count=questionCount(d.count)}catch(e){throw new HttpsError(e.code,e.message)}if(!GRADES.includes(d.grade)||typeof d.subject!=='string'||!d.subject.trim()||d.subject.length>30||typeof d.unit!=='string'||!d.unit.trim()||d.unit.length>100||typeof d.material!=='string'||d.material.length>10000)throw new HttpsError('invalid-argument','請確認出題欄位');const text=await gemini(uid,`請為 ${d.grade} 的 ${d.subject} 出 ${count} 題。單元目標：${d.unit}。教材與要求：${d.material}。輸出 JSON 格式 {"questions":[{"type":"choice","prompt":"題目","options":["選項一","選項二","選項三","選項四"],"answer":"A","explanation":"解析"}]}。也可使用 type="short" 或 "work"，此時省略 options，answer 填參考答案或評分規準。不可包含 Markdown。`,true,questionsSchema(count));let parsed;try{parsed=JSON.parse(text);if(!Array.isArray(parsed?.questions)||parsed.questions.length!==count)throw new Error('count')}catch{throw new HttpsError('failed-precondition','AI 草稿格式無效，請重試')}try{const empty=seedState(true);empty.classes=[{id:'validation'}];applyAction(empty,{type:'saveAssignment',classId:'validation',requestId:randomUUID(),assignment:{title:'草稿',grade:d.grade,subject:d.subject,unit:d.unit,status:'draft',reward:0,questions:parsed.questions}},{role:'teacher'})}catch{throw new HttpsError('failed-precondition','AI 題目未通過格式檢查，請重新產生')}return{questions:parsed.questions};}
 if(d.mode==='grade'){safeId(d.submissionId);const snap=await db.doc('workspaces/'+uid).get(),state=snap.data()?.state,sub=state?.submissions.find(x=>x.id===d.submissionId),q=state?.assignments.find(x=>x.id===sub?.assignmentId);if(!sub||!q)throw new HttpsError('not-found','找不到作答');if(sub.status!=='pending')throw new HttpsError('failed-precondition','此作答已批閱');try{const grading=parseGrading(await gemini(uid,gradingPrompt(q,sub,state.students),true,gradingSchema),q,sub);return{grading:await saveAIResult(uid,sub.id,'grade',grading)}}catch(e){if(e instanceof AIError)throw new HttpsError(e.code,e.message);throw e}}
 if(d.mode==='analysis'){safeId(d.submissionId);const snap=await db.doc('workspaces/'+uid).get(),state=snap.data()?.state;const sub=state?.submissions.find(s=>s.id===d.submissionId);const q=state?.assignments.find(q=>q.id===sub?.assignmentId);if(!sub||!q)throw new HttpsError('not-found','找不到作答');let content=JSON.stringify({grade:q.grade,subject:q.subject,unit:q.unit,questions:q.questions,answers:sub.answers});for(const st of state.students)if(st.name.length>=2)content=content.split(st.name).join('[學生]');content=content.replace(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi,'[電子郵件]').replace(/09\d{8}/g,'[電話]');const analysis=await gemini(uid,'請根據以下去識別化作答，列出：1. 已掌握概念 2. 可能的觀念缺口與具體作答證據 3. 補強活動 4. 不確定處。不要把單次作答當成定論。資料：'+content);return{analysis:await saveAIResult(uid,sub.id,'analysis',analysis)}}throw new HttpsError('invalid-argument','不支援的 AI 工作');});
