import test from 'node:test';import assert from 'node:assert/strict';
import {balanceChoices,permuteChoice,isChoicePermutation,choiceDistribution} from '../functions/choice-layout.mjs';
import {questionReviewContent,hasQuestionReview} from '../functions/question-review.mjs';
import {mathReviewContent,hasMathReview} from '../functions/math-verification.mjs';
import {createClassroom} from '../desktop/service.mjs';import {mkdtempSync,rmSync} from 'node:fs';import{tmpdir}from'node:os';import{join}from'node:path';
const scope={grade:'國小三年級',subject:'國文',unit:'成語'};
const q={type:'choice',prompt:'小明專心讀書，用哪個成語形容？',options:['虎頭蛇尾','一心一意','歡天喜地','刻舟求劍'],answer:'B',explanation:'答案是 B。一心一意表示專心；選項 A 表示做事有頭無尾。'};
test('all-B sets of 1–20 choices balance without changing correct content, input, or open questions',()=>{for(let n=1;n<=20;n++){const input=Array.from({length:n},()=>structuredClone(q));input.push({type:'short',prompt:'解釋',answer:'內容'});const snapshot=structuredClone(input),result=balanceChoices(input,scope);assert.deepEqual(input,snapshot);const values=Object.values(result.choiceLayout.counts);assert(Math.max(...values)-Math.min(...values)<=1);for(const x of result.questions.slice(0,n)){assert.equal(x.options['ABCD'.indexOf(x.answer)],'一心一意');assert.match(x.explanation,new RegExp('答案是 '+x.answer));assert(isChoicePermutation(q,x))}assert.deepEqual(result.questions[n],input[n])}});
test('permutation retains valid receipts only and rejects altered answers, explanations, scope or options',()=>{const original={...q,provenance:{kind:'bank',sources:[]}};original.teacherReview=questionReviewContent(original,scope);original.mathReview=mathReviewContent(original,scope.subject);const changed=permuteChoice(original,[1,3,0,2],scope);assert.equal(changed.answer,'A');assert.match(changed.explanation,/選項 C/);assert(hasQuestionReview(changed,scope));assert(hasMathReview(changed,scope.subject));assert(!hasQuestionReview(changed,{...scope,grade:'國小四年級'}));assert(!isChoicePermutation(original,{...changed,answer:'B'}));assert(!isChoicePermutation(original,{...changed,explanation:'錯誤詳解'}));assert(!isChoicePermutation(original,{...changed,options:['錯誤',...changed.options.slice(1)]}));assert.equal(permuteChoice({...original,teacherReview:'forged'},[1,0,2,3],scope).teacherReview,undefined)});
test('position-dependent choices and ambiguous letters are locked, labeled options are remapped safely',()=>{for(const patch of [{options:['以上皆是','一心一意','歡天喜地','刻舟求劍']},{prompt:'選項 A 和 B 何者正確？'},{explanation:'B is right.'},{options:['一心一意','一心一意','歡天喜地','刻舟求劍']}]){const input={...q,...patch};const result=balanceChoices([input],scope);assert.deepEqual(result.questions,[input]);assert.equal(result.choiceLayout.skipped.length,1)}const labeled={...q,options:q.options.map((x,i)=>'ABCD'[i]+'. '+x)};assert.equal(permuteChoice(labeled,[1,0,2,3],scope).options[0],'一心一意')});
test('approved bank permutations publish and persist with correct student grading; later tampering is blocked',async()=>{const directory=mkdtempSync(join(tmpdir(),'choice-layout-')),service=createClassroom({directory,setupCode:'qa'});try{const {token}=await service.call('teacherRegister',{email:'layout@example.com',password:'password123',setupCode:'qa'}),call=(name,data)=>service.call(name,data,token),action=data=>call('classroomAction',{...data,requestId:crypto.randomUUID()});const {classId}=await action({type:'createClass',name:'測試班',grade:scope.grade});for(let i=0;i<8;i++){const {record}=await call('questionBank',{operation:'save',record:{...scope,source:'原創',rights:'原創教學',question:{...q,prompt:`生活情境${i+1}：小明專心讀書，用哪個成語形容？`}}});await call('questionBank',{operation:'review',id:record.id,revision:record.revision,confirmed:true})}const result=await call('teacherAI',{...scope,classId,mode:'bankQuestions',count:8,material:'選擇題8題',practicePurpose:'new'});assert.deepEqual(choiceDistribution(result.questions),{A:2,B:2,C:2,D:2});assert(result.questions.every(x=>hasQuestionReview(x,scope)));const assignment={...scope,id:'paper',title:'成語練習',practicePurpose:'new',questions:result.questions};await action({type:'saveAssignment',classId,assignment:{...assignment,status:'draft'}});const saved=(await call('state',{})).state.assignments[0];assert.deepEqual(saved.questions.map(x=>x.answer),result.questions.map(x=>x.answer));await action({type:'saveAssignment',classId,assignment:{...assignment,status:'published'}});await call('setClassOpen',{open:true});await action({type:'registration',classId,open:true});const code=(await call('state',{})).state.classes.find(c=>c.id===classId).code;const student=await service.call('studentAccess',{code,name:'小安',birthday:'0305',register:true});const before=(await service.call('state',{},student.token)).state;assert(before.assignments[0].questions.every(x=>!x.answer&&!x.explanation));await service.call('classroomAction',{type:'submit',assignmentId:'paper',answers:result.questions.map(x=>x.answer),requestId:crypto.randomUUID()},student.token);const after=(await service.call('state',{},student.token)).state;assert(after.submissions[0].choiceResults.every(x=>x.correct));assert.deepEqual(after.submissions[0].choiceResults.map(x=>x.answer),result.questions.map(x=>x.answer));const tampered={...result.questions[0],explanation:'任意更改'};tampered.teacherReview=questionReviewContent(tampered,scope);await assert.rejects(action({type:'saveAssignment',classId,assignment:{...assignment,id:'bad',practicePurpose:'review',reviewPercent:100,status:'published',questions:[tampered]}}),/重新確認/)}finally{service.close();rmSync(directory,{recursive:true,force:true})}});

test('replacement balancing never touches retained positions or their receipts',()=>{const retained={...q,teacherReview:questionReviewContent(q,scope)},questions=[retained,q,q,q,q,q,q,q];const result=balanceChoices(questions,scope,Math.random,[1,2,3,4,5,6,7]);assert.equal(result.questions[0],retained);assert.deepEqual(result.choiceLayout.counts,{A:2,B:2,C:2,D:2});assert(!result.choiceLayout.changed.includes(0))});

import {verifyArithmeticQuestion} from '../functions/arithmetic.mjs';
test('numeric answer and executable arithmetic explanation stay consistent after permutation',()=>{const original=verifyArithmeticQuestion({type:'choice',prompt:'計算12+5',options:['14','17','18','19'],answer:'B',explanation:''});const changed=permuteChoice(original,[1,0,2,3],{subject:'數學'});assert.equal(changed.answer,'A');assert.deepEqual(verifyArithmeticQuestion(changed),changed);assert(isChoicePermutation(original,changed))});
test('direct AI all-B output is balanced before returning and never auto-approved',async()=>{const directory=mkdtempSync(join(tmpdir(),'choice-ai-'));let calls=0;const service=createClassroom({directory,setupCode:'qa',gemini:async()=>{calls++;return JSON.stringify({questions:Array.from({length:8},(_,i)=>({...q,prompt:`生活情境${i+1}：小明專心讀書，用哪個成語形容？`}))})}});try{const {token}=await service.call('teacherRegister',{email:'layout@example.com',password:'password123',setupCode:'qa'}),call=(name,data)=>service.call(name,data,token);await call('saveTeacherKey',{key:'test-fake-key-not-real-123456789'});const {classId}=await call('classroomAction',{type:'createClass',name:'測試班',grade:scope.grade,requestId:crypto.randomUUID()});const result=await call('teacherAI',{...scope,classId,mode:'questions',count:8,material:'選擇題8題',practicePurpose:'new'});assert.equal(calls,1);assert.deepEqual(choiceDistribution(result.questions),{A:2,B:2,C:2,D:2});assert(result.questions.every(x=>!x.teacherReview&&x.options['ABCD'.indexOf(x.answer)]==='一心一意'))}finally{service.close();rmSync(directory,{recursive:true,force:true})}});
