import test from'node:test';import assert from'node:assert/strict';import{seedState,migrateCollection,applyAction}from'../functions/domain.mjs';import{studentView}from'../functions/views.mjs';import{FURNITURE}from'../functions/furniture.mjs';import{decorationModel}from'../src/decoration-models.mjs';import{roomDraftReducer,initialRoomDraft}from'../src/room-draft.mjs';
const plan={title:'小宇海洋館',description:'我把海洋收藏放在不同高度。',goal:'搭配海洋小角落',wishes:['whale'],completed:false};
const act=(s,a,role='student',studentId='s1')=>applyAction(s,{studentId,requestId:crypto.randomUUID(),...a},{role,studentId});
const prepared=()=>act(migrateCollection(seedState()),{type:'saveCreativePlan',plan});
test('plans validate wishes, preserve balances/rooms, and reject foreign student mutation',()=>{const s=migrateCollection(seedState()),next=act(s,{type:'saveCreativePlan',plan});assert.deepEqual(next.rooms,s.rooms);assert.equal(next.students[0].balance,s.students[0].balance);assert.deepEqual(next.students[0].creativePlan,plan);assert.throws(()=>act(s,{type:'saveCreativePlan',plan:{...plan,wishes:['fake']}}));assert.throws(()=>act(s,{type:'saveCreativePlan',plan:{...plan,title:''}}));assert.throws(()=>applyAction(s,{type:'saveCreativePlan',studentId:'s2',plan,requestId:'forged'},{role:'student',studentId:'s1'}))});
test('all free furniture is valid without event/coins, placement limits and toy heights enforced',()=>{let s=prepared();s.classes[0].eventActive=false;const decorations=FURNITURE.map((f,i)=>({id:'f'+i,kind:f.id,x:0,y:.1,z:f.surface==='wall'?-1.86:0,rotation:0,scale:1,variant:'frost'}));s=act(s,{type:'saveRoom',room:{...s.rooms.s1,decorations,placements:s.rooms.s1.placements.map(p=>({...p,y:.8}))}});assert.equal(s.rooms.s1.decorations.length,12);assert.equal(s.rooms.s1.placements[0].y,.8);for(const f of FURNITURE){const m=decorationModel(f.id);assert(m.children.length);m.traverse(o=>{if(o.isMesh)assert([...o.geometry.attributes.position.array].every(Number.isFinite))})}assert.throws(()=>act(s,{type:'saveRoom',room:{...s.rooms.s1,placements:[{...s.rooms.s1.placements[0],y:Infinity}]}}));assert.throws(()=>act(s,{type:'saveRoom',room:{...s.rooms.s1,decorations:Array.from({length:9},(_,i)=>({...decorations[0],id:'dup'+i}))}}))});
test('pending and returned exhibits remain private; approval exposes only same-class curated snapshots',()=>{let s=prepared();s.classes.push({id:'c2'});s.students[2].classId='c2';s=act(s,{type:'submitExhibit',room:{malicious:true}});assert.equal(studentView(s,'s2').exhibits.length,0);assert.equal(studentView(s,'s1').exhibits[0].status,'pending');const id=s.exhibits[0].id;assert.throws(()=>act(s,{type:'reviewExhibit',exhibitId:id,status:'approved'}));s=act(s,{type:'reviewExhibit',exhibitId:id,status:'approved',note:'private teacher note'},'teacher');const peer=studentView(s,'s2').exhibits[0];assert(peer);assert.equal(peer.studentId,undefined);assert.equal(peer.note,undefined);assert.equal(peer.inventory[0].studentId,undefined);assert.equal(peer.inventory[0].earnedAt,undefined);assert(!peer.room.malicious);assert.equal(studentView(s,'s3').exhibits.length,0);const snapshot=structuredClone(peer.room);s=act(s,{type:'saveRoom',room:{...s.rooms.s1,wall:'blue'}});assert.deepEqual(studentView(s,'s2').exhibits[0].room,snapshot);s=act(s,{type:'reviewExhibit',exhibitId:id,status:'changes',note:'可以說明展示主題'},'teacher');assert.equal(studentView(s,'s2').exhibits.length,0);assert.equal(studentView(s,'s1').exhibits[0].note,'可以說明展示主題')});
test('reposting needs new approval, stale approval fails, withdrawal is owned and retries idempotent',()=>{let s=act(prepared(),{type:'submitExhibit'}),id=s.exhibits[0].id;s=act(s,{type:'reviewExhibit',exhibitId:id,status:'approved'},'teacher');s=act(s,{type:'submitExhibit'});assert.equal(s.exhibits.length,1);assert.equal(studentView(s,'s2').exhibits.length,0);assert.throws(()=>act(s,{type:'reviewExhibit',exhibitId:id,status:'approved'},'teacher'));assert.throws(()=>applyAction(s,{type:'withdrawExhibit',studentId:'s1',requestId:'foreign'},{role:'student',studentId:'s2'}));s=act(s,{type:'withdrawExhibit'});assert.equal(s.exhibits.length,0);const action={type:'submitExhibit',studentId:'s1',requestId:'repeat'};s=applyAction(s,action,{role:'student',studentId:'s1'});assert.deepEqual(applyAction(s,action,{role:'student',studentId:'s1'}),s)});
test('undo keeps edits dirty and old polling cannot erase the restored draft',()=>{const room={wall:'mint',placements:[]};let s=initialRoomDraft(room);s=roomDraftReducer(s,{type:'edit',change:{wall:'blue'}});s=roomDraftReducer(s,{type:'edit',change:{wall:'pink'}});s=roomDraftReducer(s,{type:'undo'});assert.equal(s.draft.wall,'blue');assert(s.dirty);s=roomDraftReducer(s,{type:'sync',room});assert.equal(s.draft.wall,'blue')});
