import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,writeFileSync,rmSync}from'node:fs';import{tmpdir}from'node:os';import{join}from'node:path';import{classroomHttp}from'../desktop/http.mjs';
test('desktop HTTP requires allowed origin and uses HttpOnly sessions without exposing tokens',async()=>{const dir=mkdtempSync(join(tmpdir(),'class-http-'));writeFileSync(join(dir,'index.html'),'test classroom');let token;const service={setupCode:null,call:async(name,data,incoming)=>{token=incoming;return name==='teacherLogin'?{token:'test-token'}:{ok:true}}};const port=14389,server=classroomHttp(service,{webRoot:dir,port});try{await new Promise((resolve,reject)=>{server.once('error',reject);server.listen(port,'127.0.0.1',resolve)});const url='http://127.0.0.1:'+port;let r=await fetch(url+'/');assert.equal(await r.text(),'test classroom');r=await fetch(url+'/api/teacherLogin',{method:'POST',headers:{Origin:'https://untrusted.example','Content-Type':'application/json'},body:'{}'});assert.equal(r.status,403);r=await fetch(url+'/api/teacherLogin',{method:'POST',headers:{Origin:url,'Content-Type':'application/json'},body:'{}'});assert.equal(r.status,200);assert.match(r.headers.get('set-cookie'),/HttpOnly/);assert.match(r.headers.get('set-cookie'),/SameSite=Strict/);assert.deepEqual(await r.json(),{ok:true});r=await fetch(url+'/api/state',{method:'POST',headers:{Origin:url,'Content-Type':'application/json',Cookie:'tc-session=test-token'},body:'{}'});assert.equal(token,'test-token');assert.equal(r.status,200);r=await fetch(url+'/server.key');assert.equal(r.status,404)}finally{await new Promise(resolve=>server.close(resolve));rmSync(dir,{recursive:true,force:true})}});

test('JSON bank uploads preserve Chinese characters split across network chunks',async()=>{
 const {request}=await import('node:http');const {setImmediate}=await import('node:timers/promises');
 const port=14390,origin=`http://127.0.0.1:${port}`,server=classroomHttp({setupCode:null,call:async(name,data)=>({received:data})},{webRoot:tmpdir(),port});
 try{await new Promise((resolve,reject)=>{server.once('error',reject);server.listen(port,'127.0.0.1',resolve)});
 const expected={operation:'import',question:'國語成語與數學單位'},body=Buffer.from(JSON.stringify(expected));
 const response=new Promise((resolve,reject)=>{const req=request(origin+'/api/questionBank',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'}},res=>{let raw='';res.on('data',chunk=>raw+=chunk);res.on('end',()=>resolve(JSON.parse(raw)))});req.on('error',reject);(async()=>{for(let i=0;i<body.length;i++){req.write(body.subarray(i,i+1));await setImmediate()}req.end()})().catch(reject)});
 assert.deepEqual((await response).received,expected);
 }finally{await new Promise(resolve=>server.close(resolve))}
});
