import test from 'node:test';import assert from 'node:assert/strict';
import {applyAction,seedState} from '../functions/domain.mjs';import {caseTemplate,caseKey,badgeEligibility} from '../functions/detective.mjs';import {studentView} from '../functions/views.mjs';import {applyErasures,selectData} from '../desktop/data-lifecycle.mjs';import {parseDetective} from '../desktop/detective-ai.mjs';
const image='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jXioAAAAASUVORK5CYII=';
const teacher={role:'teacher'},actor={role:'student',studentId:'s1'};
function fixture(type='choice',policy='complete'){let state=seedState();state.assignments=[{id:'task',classId:'c1',status:'published',title:'成語',grade:'國小三年級',subject:'國語／國文',unit:'成語',questions:[{type,prompt:'專心的成語？',options:['一心一意','虎頭蛇尾','歡天喜地','刻舟求劍'],answer:type==='choice'?'A':'一心一意',explanation:'專注'}]}];const action=(a,who=teacher)=>state=applyAction(state,{...a,requestId:crypto.randomUUID()},who);action({type:'saveCharacter',classId:'c1',character:{name:'小探員',source:'原創',rights:true,image}});action({type:'saveCase',case:{...caseTemplate(state.assignments[0]),assignmentId:'task',characterId:state.characters[0].id,status:'published',reviewed:true,policy,threshold:60}});const c=state.detectiveCases[0];return {get state(){return state},action,c,finish(){action({type:'caseAnswer',studentId:'s1',caseId:c.id,index:0,answer:type==='choice'?'A':'專心'},actor);action({type:'finishCase',studentId:'s1',caseId:c.id,choice:0,reason:'依據全部線索'},actor)}}}
test('teacher publication requires rights, narrative review, immutable tasks and coherent stage count',()=>{const f=fixture();assert.throws(()=>f.action({type:'saveCase',case:{...f.c,title:'偷偷修改'}}),/不可修改/);assert.throws(()=>f.action({type:'saveCharacter',classId:'c1',character:{name:'x',source:'x',image,rights:false}}),/權限/);assert.throws(()=>f.action({type:'saveCharacter',classId:'c1',character:{name:'x',source:'x',image:'data:image/svg+xml;base64,AAAA',rights:true}}),/PNG/);assert.throws(()=>parseDetective(JSON.stringify({...caseTemplate(f.state.assignments[0]),stages:[]}),f.state.assignments[0]),/場景/)});
test('student projection hides solution, future clues, other progress and private character sources',()=>{const f=fixture(),v=studentView(f.state,'s1');assert.equal(v.detectiveCases[0].solution,undefined);assert.equal(v.detectiveCases[0].ending,undefined);assert.equal(v.detectiveCases[0].stages[0].clue,undefined);assert.equal(v.characters,undefined);f.finish();assert(studentView(f.state,'s1').detectiveCases[0].ending);assert.equal(Object.keys(studentView(f.state,'s2').caseProgress).length,0)});
test('case ownership and sequence are enforced; normal submission cannot bypass investigation',()=>{const f=fixture();assert.throws(()=>f.action({type:'caseAnswer',studentId:'s2',caseId:f.c.id,index:0,answer:'A'},actor),/自己/);assert.throws(()=>f.action({type:'caseAnswer',studentId:'s1',caseId:f.c.id,index:1,answer:'A'},actor),/進度/);assert.throws(()=>f.action({type:'submit',studentId:'s1',assignmentId:'task',answers:['A']},actor),/偵探社/);assert.throws(()=>f.action({type:'claimBadge',studentId:'s1',caseId:f.c.id},actor),/結案/)});
test('retrying answers, completion and reward never duplicates submissions or badges',()=>{const f=fixture();f.action({type:'caseAnswer',studentId:'s1',caseId:f.c.id,index:0,answer:'A'},actor);f.action({type:'caseAnswer',studentId:'s1',caseId:f.c.id,index:0,answer:'A'},actor);assert.equal(f.state.caseProgress[caseKey('s1',f.c.id)].answers.length,1);assert.throws(()=>f.action({type:'finishCase',studentId:'s1',caseId:f.c.id,choice:1,reason:'猜測'},actor),/不符/);for(let i=0;i<3;i++){f.action({type:'finishCase',studentId:'s1',caseId:f.c.id,choice:0,reason:'證據'},actor);f.action({type:'claimBadge',studentId:'s1',caseId:f.c.id},actor)}assert.equal(f.state.submissions.length,1);assert.equal(f.state.badges.length,1);assert.equal(f.state.ledger.length,0)});
test('open-ended score threshold requires teacher review; client cannot provide score or badge selection',()=>{const f=fixture('short','score');f.finish();assert.throws(()=>f.action({type:'claimBadge',studentId:'s1',caseId:f.c.id,score:100},actor),/等待/);f.action({type:'review',submissionId:f.state.submissions[0].id,score:50,feedback:'請補強',reward:0});assert.throws(()=>f.action({type:'claimBadge',studentId:'s1',caseId:f.c.id},actor),/門檻/);f.action({type:'updateReview',submissionId:f.state.submissions[0].id,score:80,feedback:'已補充',itemFeedback:['已補充']});f.action({type:'claimBadge',studentId:'s1',caseId:f.c.id,style:'forged'},actor);assert.notEqual(f.state.badges[0].style,'forged')});
test('display only owned badges; deletion/export includes private progress and earned badges',()=>{const f=fixture();f.finish();f.action({type:'claimBadge',studentId:'s1',caseId:f.c.id},actor);const id=f.state.badges[0].id;assert.throws(()=>f.action({type:'displayBadges',studentId:'s2',badgeIds:[id]},{role:'student',studentId:'s2'}),/自己/);f.action({type:'displayBadges',studentId:'s1',badgeIds:[id]},actor);const state={teacher:{uid:'t'},workspace:f.state};assert.equal(selectData(state,{kind:'student',id:'s1'}).badges.length,1);const erased=applyErasures(structuredClone(state),[{owner:'t',students:['s1'],classes:[]}]);assert.equal(erased.workspace.badges.length,0);assert.equal(Object.keys(erased.workspace.caseProgress).length,0);assert(!erased.workspace.badgeDisplays.s1)});
test('revoking character removes cases, progress and badge images but preserves learning records',()=>{const f=fixture();f.finish();f.action({type:'claimBadge',studentId:'s1',caseId:f.c.id},actor);assert.throws(()=>f.action({type:'deleteCharacter',characterId:f.c.characterId}),/確認/);f.action({type:'deleteCharacter',characterId:f.c.characterId,confirmed:true});assert.equal(f.state.badges.length,0);assert.equal(f.state.detectiveCases.length,0);assert.equal(f.state.submissions.length,1)});

test('reward status distinguishes awaiting grading, below threshold and eligible without trusting browser',()=>{const f=fixture('short','score'),student=f.state.students.find(x=>x.id==='s1');f.finish();assert.match(badgeEligibility(f.state,student,f.c).message,/等待老師/);f.action({type:'review',submissionId:f.state.submissions[0].id,score:55,feedback:'再練習',reward:0});assert.match(badgeEligibility(f.state,student,f.c).message,/未達/);f.action({type:'updateReview',submissionId:f.state.submissions[0].id,score:80,feedback:'完成',itemFeedback:['完成']});assert.equal(badgeEligibility(f.state,student,f.c).ready,true)});
test('same character collection draws unowned styles and stops after all three',()=>{const f=fixture();const student=f.state.students.find(x=>x.id==='s1');for(let i=0;i<4;i++){let c=f.c;if(i){f.state.assignments.push({...structuredClone(f.state.assignments[0]),id:'task'+i});f.action({type:'saveCase',case:{...caseTemplate(f.state.assignments.at(-1)),assignmentId:'task'+i,characterId:f.state.characters[0].id,status:'published',reviewed:true}});c=f.state.detectiveCases.at(-1)}f.action({type:'caseAnswer',caseId:c.id,studentId:'s1',index:0,answer:'A'},actor);f.action({type:'finishCase',caseId:c.id,studentId:'s1',choice:0,reason:'證據'},actor);if(i<3)f.action({type:'claimBadge',caseId:c.id,studentId:'s1'},actor);else{assert.match(badgeEligibility(f.state,student,c).message,/已集滿/);assert.throws(()=>f.action({type:'claimBadge',caseId:c.id,studentId:'s1'},actor),/已集滿/)}}assert.equal(new Set(f.state.badges.map(b=>b.style)).size,3);assert.equal(f.state.submissions.length,4)});

test('draft narrative stays private and atomic publication rolls back invalid story',()=>{
 const f=fixture();f.state.assignments[0].status='draft';f.state.assignments[0].presentation='detective';f.state.detectiveCases[0].status='draft';
 assert.equal(studentView(f.state,'s1').assignments.length,0);assert.equal(studentView(f.state,'s1').detectiveCases.length,0);
 const assignment={...f.state.assignments[0],status:'published'};
 assert.throws(()=>f.action({type:'saveAssignment',classId:'c1',assignment,detectiveCase:{...f.c,reviewed:false}}),/確認/);
 assert.equal(f.state.assignments[0].status,'draft');assert.equal(f.state.detectiveCases[0].status,'draft');
 f.action({type:'saveAssignment',classId:'c1',assignment,detectiveCase:{...f.c,reviewed:true}});
 assert.equal(f.state.assignments.length,1);assert.equal(f.state.assignments[0].status,'published');assert.equal(studentView(f.state,'s1').detectiveCases.length,1);
});
test('archiving blocks new work, protects ongoing investigations, and keeps earned rewards',()=>{
 const f=fixture();assert.throws(()=>f.action({type:'archiveAssignment',assignmentId:'task'},actor),/教師|老師/);
 f.action({type:'caseAnswer',studentId:'s1',caseId:f.c.id,index:0,answer:'A'},actor);
 assert.throws(()=>f.action({type:'archiveAssignment',assignmentId:'task'}),/正在調查/);
 f.finish();f.action({type:'archiveAssignment',assignmentId:'task'});assert(f.state.assignments[0].archivedAt);
 f.action({type:'claimBadge',studentId:'s1',caseId:f.c.id},actor);assert.equal(f.state.badges.length,1);
 f.action({type:'archiveAssignment',assignmentId:'task',archived:false});assert.equal(f.state.assignments[0].archivedAt,undefined);
});

test('story generation requires exploration beats while legacy cases remain readable',()=>{
 const task={title:'測試',questions:[{type:'choice',prompt:'Q'}]},legacy=caseTemplate(task);
 assert.throws(()=>parseDetective(JSON.stringify(legacy),task),/場景|故事/);
 const story={...legacy,stages:legacy.stages.map(s=>({...s,location:'準備室',objective:'找出物品去向',inspect:'翻開留言簿',discovery:'紙頁記錄了離開前的行動。'}))};
 assert.equal(parseDetective(JSON.stringify(story),task).stages[0].inspect,'翻開留言簿');
 const f=fixture();f.state.detectiveCases[0].stages[0]={...f.c.stages[0],...story.stages[0]};const view=studentView(f.state,'s1').detectiveCases[0];assert.equal(view.stages[0].location,'準備室');assert.equal(view.stages[0].clue,undefined);assert.equal(view.solution,undefined);
});

test('story validation reports safe field location without exposing generated text',()=>{
 const task={title:'測試',questions:[{}]},story={...caseTemplate(task),stages:[{scene:'對話',clue:'證據',hint:'提示',location:'現場',objective:'查明',inspect:'查看',discovery:'發現'}]};
 assert.throws(()=>parseDetective('{',task),e=>e.code==='failed-precondition'&&e.message.includes('格式'));
 const missing=structuredClone(story);delete missing.stages[0].discovery;
 assert.throws(()=>parseDetective(JSON.stringify(missing),task),e=>e.code==='failed-precondition'&&e.message.includes('第 1 站／故事發現'));
 const long=structuredClone(story);long.stages[0].hint='秘密'.repeat(151);
 assert.throws(()=>parseDetective(JSON.stringify(long),task),e=>e.code==='failed-precondition'&&e.message.includes('提示')&&!e.message.includes('秘密'));
 assert.equal(parseDetective('```json\n'+JSON.stringify(story)+'\n```',task).title,story.title);
});
