import test from'node:test';import assert from'node:assert/strict';import{DatabaseSync}from'node:sqlite';import{createQuestionBank}from'../desktop/question-bank.mjs';import{checkExtensionDiversity,spreadIdiomRecords}from'../desktop/extension-diversity.mjs';
const scope={grade:'國小三年級',subject:'國文',unit:'能了解基礎成語',material:'選擇題10題',count:10};
const words=['一心一意','虎頭蛇尾','歡天喜地','胸有成竹','畫蛇添足','守株待兔','井底之蛙','半途而廢','刻舟求劍','興高采烈'];
const q=(word,i)=>({type:'choice',prompt:`第${i}個生活情境，哪個成語符合描述？`,options:[word,'以上皆非','無法判斷','其他詞語'],answer:'A',explanation:`本題以「${word}」為主要考點。`});
test('changed wording cannot disguise repetition; distractors do not count as coverage',()=>{assert.throws(()=>checkExtensionDiversity([q(words[0],0),q(words[1],1)],Array.from({length:8},(_,i)=>({...q(words[i%2],i+2),targetConcept:words[i+2]})),scope),/考點過度集中/);assert.equal(checkExtensionDiversity([],words.map(q),scope).unique,10)});
test('explicit focused drills may repeat named idioms but ordinary broad requests cannot',()=>{const rows=Array.from({length:10},(_,i)=>q(words[0],i));assert.throws(()=>checkExtensionDiversity([],rows,scope),/考點過度集中/);assert.equal(checkExtensionDiversity([],rows,scope,'只練一心一意，選擇題10題').focused,true);assert.equal(checkExtensionDiversity([],rows,{...scope,subject:'數學'}),null)});
test('source selection spreads distinct idioms before repeating one',()=>{const rows=[{id:'a',question:q(words[0],0)},{id:'b',question:q(words[0],1)},{id:'c',question:q(words[1],2)}];assert.deepEqual(spreadIdiomRecords(rows,scope).map(x=>x.id),['a','c','b'])});
test('RAG retries concentrated extensions once and exposes coverage without granting approval',async()=>{const db=new DatabaseSync(':memory:');try{const bank=createQuestionBank(db),sources=words.slice(0,2).map((word,i)=>bank.save({...scope,unit:'成語',source:'教師自編',rights:'原創教學',question:q(word,i)}));let calls=0;const result=await bank.generate(scope,async prompt=>{calls++;assert.match(prompt,/不是僅重考來源题的成語|不是僅重考來源題的成語/);if(calls===2)assert.match(prompt,/上次輸出未通過/);return JSON.stringify({questions:Array.from({length:8},(_,i)=>({...q(calls===1?words[i%2]:words[i+2],i+2),targetConcept:words[i+2],sourceIds:[sources[0].id]}))})});assert.equal(calls,2);assert.equal(result.questions.length,10);assert.equal(result.retrieval.coverage.unique,10);assert.equal(result.questions[2].teacherReview,undefined);
let failed=0;await assert.rejects(bank.generate(scope,async()=>{failed++;return JSON.stringify({questions:Array.from({length:8},(_,i)=>({...q(words[0],i+2),sourceIds:[sources[0].id]}))})}),/考點分布仍未達要求/);assert.equal(failed,2)}finally{db.close()}});
