import test from 'node:test';import assert from 'node:assert/strict';import {requestGemini,questionSchema} from '../functions/gemini.mjs';
const args={key:'test-key-not-a-real-secret-12345',model:'gemini-3.5-flash-lite',prompt:'測試教材'};
const reply=(text,finishReason='STOP')=>({ok:true,json:async()=>({candidates:[{finishReason,content:{parts:[{text:'內部思考',thought:true},{text}]}}]})});
test('Gemini request keeps key out of URL and requests structured questions',async()=>{let sent;const result=await requestGemini({...args,json:true,fetchImpl:async(url,options)=>{sent={url,options};return reply('{"questions":[]}')}});assert.equal(result,'{"questions":[]}');assert.equal(sent.url,'https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash-lite:generateContent');assert.ok(!sent.url.includes(args.key));assert.equal(sent.options.headers['x-goog-api-key'],args.key);const body=JSON.parse(sent.options.body);assert.deepEqual(body.generationConfig.responseJsonSchema,questionSchema);assert.equal(body.contents[0].parts[0].text,args.prompt);assert.equal(sent.options.signal.aborted,false)});
test('Gemini errors are actionable and never expose provider content or keys',async()=>{for(const [status,code] of [[400,'invalid-argument'],[401,'permission-denied'],[403,'permission-denied'],[404,'failed-precondition'],[429,'resource-exhausted'],[503,'unavailable']]){let calls=0;await assert.rejects(requestGemini({...args,fetchImpl:async()=>{calls++;return{ok:false,status,json:async()=>({error:{message:args.key}})}}}),e=>e.code===code&&!e.message.includes(args.key));assert.equal(calls,1,'no automatic quota-consuming retries')}});
test('Gemini rejects blocked, empty, truncated and incomplete responses',async()=>{for(const response of [reply('','STOP'),reply('partial','MAX_TOKENS'),reply('blocked','SAFETY'),reply('partial','OTHER'),{ok:true,json:async()=>({promptFeedback:{blockReason:'SAFETY'}})}])await assert.rejects(requestGemini({...args,fetchImpl:async()=>response}),e=>e.code==='failed-precondition')});
test('Gemini network failures and invalid JSON are sanitized',async()=>{for(const fetchImpl of [async()=>{throw new Error(args.key) },async()=>({ok:true,json:async()=>{throw new Error(args.key)}})])await assert.rejects(requestGemini({...args,fetchImpl}),e=>e.code==='unavailable'&&!e.message.includes(args.key))});
test('Gemini rejects malformed credentials and model paths before network access',async()=>{for(const override of [{key:''},{key:' ' .repeat(30)},{model:'../other?key=secret'}])await assert.rejects(requestGemini({...args,...override,fetchImpl:async()=>assert.fail('must not fetch')}),e=>e.code==='failed-precondition')});
test('upstream failures display HTTP status and model without exposing provider data',async()=>{
 for(const status of [500,502,503,504,418])await assert.rejects(requestGemini({...args,fetchImpl:async()=>({ok:false,status,json:async()=>assert.fail('do not read provider error body')})}),e=>e.code==='unavailable'&&e.message.includes(`HTTP ${status}`)&&e.message.includes(args.model)&&!e.message.includes(args.key));
});
test('JSON schema-in-prompt mode omits provider schema while retaining explicit format and JSON MIME type',async()=>{let body;await requestGemini({key:'test-api-key-not-real-1234567890',model:'gemini-3.5-flash-lite',prompt:'解析教學意圖',json:true,schemaMode:'json',schema:{type:'object',properties:{summary:{type:'string'}}},fetchImpl:async(url,options)=>{body=JSON.parse(options.body);return new Response(JSON.stringify({candidates:[{finishReason:'STOP',content:{parts:[{text:'{"summary":"成語"}'}]}}]}),{status:200})}});assert.equal(body.generationConfig.responseMimeType,'application/json');assert.equal(body.generationConfig.responseJsonSchema,undefined);assert.match(body.contents[0].parts[0].text,/summary/)});
