import test from'node:test';import assert from'node:assert/strict';import{samePracticeQuestion,practicePolicy,assertPracticeQuestions,selectPracticeRecords}from'../functions/question-history.mjs';import{createClassroom}from'../desktop/service.mjs';import{mkdtempSync,rmSync}from'node:fs';import{tmpdir}from'node:os';import{join}from'node:path';
const q={type:'choice',prompt:'哪個成語表示專心？',options:['一心一意','虎頭蛇尾','歡天喜地','刻舟求劍'],answer:'A',explanation:'一心一意表示專心。'};
const assignment={id:'old',classId:'c1',status:'published',subject:'國文',unit:'成語',questions:[q]};
const state={classes:[{id:'c1'},{id:'c2'}],assignments:[assignment,{...assignment,id:'draft',status:'draft'},{...assignment,id:'other',classId:'c2'}],submissions:[]};
test('question identity ignores numbering and option order, not quantities, operators or genuinely new contexts',()=>{assert(samePracticeQuestion(q,{...q,prompt:'第 2 題：哪個成語表示專心？',options:[...q.options].reverse(),answer:'D'}));assert(!samePracticeQuestion(q,{...q,prompt:'小明每天專心練習鋼琴，應以哪個成語形容？'}));assert(!samePracticeQuestion({prompt:'計算1.25+3'},{prompt:'計算125+3'}));assert(!samePracticeQuestion({prompt:'計算12+3'},{prompt:'計算12-3'}));assert(samePracticeQuestion(q,{...q,answer:'B'}));assert(!samePracticeQuestion(q,{...q,options:['專心致志','東張西望','七上八下','自言自語']}));});
test('history is class and subject scoped, excludes drafts and the current assignment',()=>{assert.equal(practicePolicy(state,{classId:'c1',subject:'國文'}).history.length,1);assert.equal(practicePolicy(state,{classId:'c1',subject:'數學'}).history.length,0);assert.equal(practicePolicy(state,{classId:'c1',subject:'國文',assignmentId:'old'}).history.length,0);assert.throws(()=>practicePolicy(state,{classId:'missing'}),/班級/)});
test('new practice excludes old items and review allows only the stated maximum',()=>{const policy=practicePolicy(state,{classId:'c1',subject:'國文'});assert.throws(()=>assertPracticeQuestions([q],policy),/本班/);const other={...q,prompt:'這個故事中，小明很專心，適合哪個成語？'};assert.doesNotThrow(()=>assertPracticeQuestions([other],policy));const result=selectPracticeRecords([{id:'old',question:q},{id:'new',question:other}],policy,2);assert.deepEqual(result.selected.map(x=>x.id),['new']);assert.equal(result.excluded,1);const review={...policy,purpose:'review',percent:25};assert.throws(()=>assertPracticeQuestions([q],review),/本班/);assert.doesNotThrow(()=>assertPracticeQuestions([q],review,4));assert.throws(()=>assertPracticeQuestions([q,q],{...review,percent:100}),/同一份/)});
test('remedial evidence requires real wrong choices in the selected unit; open questions and missing answers are not wrong',()=>{assert.throws(()=>practicePolicy(state,{classId:'c1',subject:'國文',unit:'成語',practicePurpose:'remedial'}),/尚無/);const workspace={...state,submissions:[{assignmentId:'old',answers:['B']}]};const policy=practicePolicy(workspace,{classId:'c1',subject:'國語',unit:'能了解基礎成語',practicePurpose:'remedial'});assert.equal(policy.wrong.length,1);assert.throws(()=>assertPracticeQuestions([q],policy),/本班/);assert.doesNotThrow(()=>assertPracticeQuestions([q],{...policy,allowRepeat:true}));assert.throws(()=>practicePolicy(workspace,{classId:'c2',subject:'國文',unit:'成語',practicePurpose:'remedial'}),/尚無/)});
test('real service excludes published content, ignores forged history, blocks stale publication and persists the teacher choices',async()=>{const directory=mkdtempSync(join(tmpdir(),'practice-history-')),service=createClassroom({directory,setupCode:'qa'});try{const {token}=await service.call('teacherRegister',{email:'history@example.com',password:'password123',setupCode:'qa'});const call=(name,data)=>service.call(name,data,token),action=data=>call('classroomAction',{...data,requestId:crypto.randomUUID()});const {classId}=await action({type:'createClass',name:'測試班',grade:'國小三年級'}),other=(await action({type:'createClass',name:'另一班',grade:'國小三年級'})).classId;const scope={grade:'國小三年級',subject:'國文',unit:'成語'};const {record}=await call('questionBank',{operation:'save',record:{...scope,source:'自編',rights:'原創授權',question:q}});await call('questionBank',{operation:'review',id:record.id,revision:record.revision,confirmed:true});const request={...scope,classId,mode:'bankQuestions',count:1,material:'選擇題1題',practicePurpose:'new'};const first=await call('teacherAI',request);assert.equal(first.questions.length,1);const draft={...scope,id:'one',title:'練習',questions:first.questions,practicePurpose:'new',requirements:'選擇題1題',generationMode:'bankQuestions',questionCount:1};await action({type:'saveAssignment',classId,assignment:{...draft,status:'draft'}});assert.equal((await call('teacherAI',request)).questions.length,1);await action({type:'saveAssignment',classId,assignment:{...draft,status:'published'}});const second=await call('teacherAI',{...request,practicePolicy:{history:[],purpose:'review',percent:100}});assert.equal(second.questions.length,0);assert.equal(second.retrieval.excludedHistory,1);assert.equal((await call('teacherAI',{...request,classId:other})).questions.length,1);assert.equal((await call('teacherAI',{...request,practicePurpose:'review',reviewPercent:100})).questions.length,1);await assert.rejects(action({type:'saveAssignment',classId,assignment:{...draft,id:'two',status:'published'}}),/本班/);await action({type:'saveAssignment',classId,assignment:{...draft,id:'two',practicePurpose:'review',reviewPercent:100,status:'draft'}});const saved=(await call('state',{})).state.assignments.find(x=>x.id==='two');assert.equal(saved.reviewPercent,100);assert.equal(saved.requirements,'選擇題1題');assert.equal(saved.generationMode,'bankQuestions')}finally{service.close();rmSync(directory,{recursive:true,force:true})}});

import{DatabaseSync}from'node:sqlite';import{createQuestionBank}from'../desktop/question-bank.mjs';
test('RAG uses historical sources to develop new questions and retries historical repeats once',async()=>{const db=new DatabaseSync(':memory:');try{const bank=createQuestionBank(db),scope={grade:'國小三年級',subject:'國文',unit:'成語',material:'選擇題1題',count:1};const source=bank.save({...scope,source:'原創',rights:'原創供教學使用',question:q});const policy=practicePolicy(state,{classId:'c1',subject:'國文'});let calls=0;const result=await bank.generate({...scope,practicePolicy:policy},async prompt=>{calls++;assert.match(prompt,/avoidQuestions/);return JSON.stringify({questions:[{...q,prompt:calls===1?q.prompt:'小華寫功課時完全不受周圍聲音影響，可以用哪個成語形容？',sourceIds:[source.id],targetConcept:'一心一意'}]})});assert.equal(calls,2);assert.equal(result.retrieval.excludedHistory,1);assert.equal(result.retrieval.generated,1);assert.equal(result.questions[0].teacherReview,undefined);let failures=0;const flagged=await bank.generate({...scope,practicePolicy:policy},async()=>{failures++;return JSON.stringify({questions:[{...q,sourceIds:[source.id],targetConcept:'一心一意'}]})});assert.match(flagged.retrieval.historyConflict,/第 1/);assert.equal(flagged.questions[0].teacherReview,undefined);assert.equal(failures,2)}finally{db.close()}});

test('partial assembly respects the percentage of actual questions, but RAG may complete the missing new questions',()=>{const policy={...practicePolicy(state,{classId:'c1',subject:'國文'}),purpose:'review',percent:25},records=[{question:q},{question:{...q,prompt:'小美讀書時不受電視聲音影響，可用哪個成語形容？'}}];const partial=selectPracticeRecords(records,policy,4,{choice:4});assert.equal(partial.repeats,0);assert.equal(partial.selected.length,1);assert.equal(partial.remaining.choice,3);assert.doesNotThrow(()=>assertPracticeQuestions(partial.selected.map(r=>r.question),policy));assert.equal(selectPracticeRecords(records,policy,4,{choice:4},{completeLater:true}).repeats,1)});

test('bare decimal calculations and numeric answer options are never stripped as question numbers',()=>{assert(!samePracticeQuestion({prompt:'1.25 + 3 = ?'},{prompt:'25 + 3 = ?'}));assert(!samePracticeQuestion({...q,options:['1.25','2','3','4']},{...q,options:['2.25','2','3','4']}));});
test('replacement replaces only conflicting slots, preserves reviewed questions, and reports shortages atomically',async()=>{const directory=mkdtempSync(join(tmpdir(),'replace-history-')),service=createClassroom({directory,setupCode:'qa'});try{const {token}=await service.call('teacherRegister',{email:'replace@example.com',password:'password123',setupCode:'qa'}),call=(name,data)=>service.call(name,data,token),action=data=>call('classroomAction',{...data,requestId:crypto.randomUUID()});const {classId}=await action({type:'createClass',name:'換題班',grade:'國小三年級'}),scope={grade:'國小三年級',subject:'國文',unit:'成語'},questions=[q,{...q,prompt:'比賽還沒開始就充分準備，可以用哪個成語形容？',options:['胸有成竹','歡天喜地','刻舟求劍','虎頭蛇尾']},{...q,prompt:'小華專注讀書而沒有注意周圍的聲音，可用哪個成語形容？'}];const approved=[];for(const question of questions){const {record}=await call('questionBank',{operation:'save',record:{...scope,source:'原創',rights:'原創教學',question}});await call('questionBank',{operation:'review',id:record.id,revision:record.revision,confirmed:true})}
 const initial=await call('teacherAI',{...scope,classId,mode:'bankQuestions',count:3,material:'選擇題3題'});const old=initial.questions.find(x=>x.prompt===q.prompt),kept=initial.questions.find(x=>x.prompt===questions[1].prompt);await action({type:'saveAssignment',classId,assignment:{...scope,id:'old',title:'上次',status:'published',practicePurpose:'new',questions:[old]}});
 const data={...scope,classId,mode:'replaceRepeated',generationMode:'bankQuestions',practicePurpose:'new',questions:[old,kept],material:'選擇題2題'};const result=await call('teacherAI',data);assert.deepEqual(result.replaced,[0]);assert.equal(result.questions[0].prompt,questions[2].prompt);assert.deepEqual(result.questions[1],kept);await action({type:'saveAssignment',classId,assignment:{...scope,id:'new',title:'新題',status:'published',practicePurpose:'new',questions:result.questions}});const shortage=await call('teacherAI',data);assert.equal(shortage.shortage,true);assert.equal(shortage.questions,undefined);assert.deepEqual(shortage.replaced,[]);
 }finally{service.close();rmSync(directory,{recursive:true,force:true})}});

test('direct AI retries duplicates once and returns an explicitly flagged editable draft that cannot publish',async()=>{const directory=mkdtempSync(join(tmpdir(),'repeat-ai-'));let calls=0;const service=createClassroom({directory,setupCode:'qa',gemini:async()=>{calls++;return JSON.stringify({questions:[q]})}});try{const {token}=await service.call('teacherRegister',{email:'repeat@example.com',password:'password123',setupCode:'qa'}),call=(name,data)=>service.call(name,data,token),action=data=>call('classroomAction',{...data,requestId:crypto.randomUUID()});await call('saveTeacherKey',{key:'fake-test-key-never-real-123456789'});const {classId}=await action({type:'createClass',name:'測試班',grade:'國小三年級'}),scope={classId,grade:'國小三年級',subject:'國文',unit:'成語',practicePurpose:'new'};await action({type:'saveAssignment',classId,assignment:{...scope,id:'old',title:'舊題',status:'published',questions:[q]}});const result=await call('teacherAI',{...scope,mode:'questions',material:'選擇題1題',count:1});assert.equal(calls,2);assert.match(result.retrieval.historyConflict,/第 1/);assert.equal(result.questions[0].teacherReview,undefined);await assert.rejects(action({type:'saveAssignment',classId,assignment:{...scope,id:'new',title:'新題',status:'published',questions:result.questions}}),/替換重複題/)}finally{service.close();rmSync(directory,{recursive:true,force:true})}});
