import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';
import {createQuestionBank} from '../desktop/question-bank.mjs';import {applyAction,seedState} from '../functions/domain.mjs';import {questionReviewContent,hasQuestionReview} from '../functions/question-review.mjs';import {studentView} from '../functions/views.mjs';
const scope={grade:'國小三年級',subject:'數學',unit:'整數加法',textbook:'自編',semester:'上學期',difficulty:'一般'};
const row=(extra={})=>({...scope,tags:['加法'],source:'教師自編',url:'',rights:'自編授權課堂及 AI 參考',question:{type:'choice',prompt:'計算 23 + 14 的結果為何？',options:['37','47','57','67'],answer:'A',explanation:'23+14=37'},...extra});
function fixture(){const db=new DatabaseSync(':memory:'),bank=createQuestionBank(db);return {bank,close:()=>db.close()}}
function approved(bank,input=row()){const r=bank.save(input);bank.review({id:r.id,revision:r.revision,confirmed:true});return bank.get(r.id)}
const newQuestion=(sourceIds,prompt='計算 34 + 25 的結果為何？')=>({type:'short',prompt,answer:'59',explanation:'34+25=59',sourceIds});
const publish=(question,fields={})=>applyAction(seedState(),{type:'saveAssignment',requestId:crypto.randomUUID(),classId:'c1',assignment:{...scope,...fields,title:'RAG任務',status:'published',questions:[question]}},{role:'teacher'});
test('imports are pending, all-or-nothing, deduplicate and do not trust imported approval',()=>{const f=fixture();try{assert.deepEqual(f.bank.importRows([{...row(),status:'approved',reviewedAt:1},row()]),{imported:1,skipped:1});assert.equal(f.bank.retrieve(scope).length,0);assert.throws(()=>f.bank.importRows([row({unit:'新單元'}),{bad:true}]));assert.equal(f.bank.list().total,1)}finally{f.close()}});
test('retrieval restricts grade, subject, version, semester, difficulty, relevance and status',()=>{const f=fixture();try{const good=approved(f.bank);approved(f.bank,row({grade:'國小四年級'}));approved(f.bank,row({subject:'自然科學'}));approved(f.bank,row({textbook:'其他'}));approved(f.bank,row({semester:'下學期'}));approved(f.bank,row({difficulty:'進階'}));approved(f.bank,row({unit:'長度測量',tags:['公尺']}));assert.deepEqual(f.bank.retrieve(scope).map(r=>r.id),[good.id]);f.bank.retire({id:good.id,revision:good.revision});assert.equal(f.bank.retrieve(scope).length,0)}finally{f.close()}});
test('editing approved content resets status and rejects stale edits or review receipts',()=>{const f=fixture();try{const r=approved(f.bank);const changed=f.bank.save({...r,unit:'加法練習'});assert.equal(changed.status,'pending');assert.equal(changed.revision,2);assert.equal(f.bank.getVersion(r.id,1).unit,r.unit);assert.throws(()=>f.bank.review({id:r.id,revision:1,confirmed:true}),/已更新/);assert.throws(()=>f.bank.save(r),/已更新/);assert.equal(f.bank.retrieve(scope).length,0)}finally{f.close()}});
test('enough bank questions avoids Gemini and empty retrieval never generates ungrounded questions',async()=>{const f=fixture();try{let calls=0;const ai=()=>{calls++;throw Error()};await assert.rejects(f.bank.generate({...scope,count:2},ai),/找不到符合範圍/);approved(f.bank);const result=await f.bank.generate({...scope,count:1},ai);assert.equal(calls,0);assert.equal(result.questions[0].provenance.kind,'bank');assert.equal(hasQuestionReview(result.questions[0],scope),true);assert.doesNotThrow(()=>publish(result.questions[0]));}finally{f.close()}});
test('shortage generates only missing questions grounded in server selected citations and no auto approval',async()=>{const f=fixture();try{const r=approved(f.bank);let sent;const result=await f.bank.generate({...scope,count:3,material:'混合題型'},async(prompt,json,schema)=>{sent={prompt,json,schema};return JSON.stringify({questions:[newQuestion([r.id]),newQuestion([r.id],'計算 42 + 17 的結果為何？')]})});assert.equal(sent.schema.properties.questions.minItems,2);assert.match(sent.prompt,/23 \+ 14/);assert.deepEqual(result.questions.map(q=>q.provenance.kind),['bank','rag','rag']);assert.equal(result.retrieval.generated,2);assert.equal(result.questions[1].teacherReview,undefined);assert.throws(()=>publish(result.questions[1]),/逐題確認/);const q=result.questions[1];q.teacherReview=questionReviewContent(q,scope);assert.doesNotThrow(()=>publish(q));assert.throws(()=>publish(q,{unit:'整數乘法'}),/逐題確認/);assert.throws(()=>publish({...q,explanation:'已變動'}),/逐題確認/)}finally{f.close()}});
test('rejects hallucinated citations, missing citations, duplicate generation and invalid arithmetic',async()=>{const f=fixture();try{const r=approved(f.bank);for(const q of [newQuestion(['unknown']),newQuestion([]),{...r.question,sourceIds:[r.id]},{...r.question,options:['1','2','3','4'],sourceIds:[r.id]}])await assert.rejects(f.bank.generate({...scope,count:2},async()=>JSON.stringify({questions:[q]})),/RAG 題目未通過/)}finally{f.close()}});
test('retiring source while AI is running invalidates the generated response',async()=>{const f=fixture();try{const r=approved(f.bank);await assert.rejects(f.bank.generate({...scope,count:2},async()=>{f.bank.retire({id:r.id,revision:r.revision});return JSON.stringify({questions:[newQuestion([r.id])]})}),/題庫已變動/)}finally{f.close()}});
test('student payload removes reference metadata and teacher review receipts containing answers',()=>{const q={type:'short',prompt:'說明兩個解法',answer:'教師專用答案',explanation:'秘密詳解',provenance:{kind:'rag',sources:[{id:'secret-id',revision:1,title:'單元',source:'教師私有',url:''}]}};const fields={...scope,subject:'綜合活動'};q.teacherReview=questionReviewContent(q,fields);const s=publish(q,fields);const json=JSON.stringify(studentView(s,'s1'));assert.doesNotMatch(json,/教師專用答案|秘密詳解|secret-id|teacherReview|provenance/)});
test('teacher library search includes pending records while RAG excludes them',()=>{const f=fixture();try{f.bank.save(row());assert.equal(f.bank.list({query:'加法'}).total,1);assert.equal(f.bank.list({query:'成語'}).total,0);assert.equal(f.bank.retrieve(scope).length,0)}finally{f.close()}});
test('Chinese subject aliases and learning-goal wording retrieve the approved idiom topic only',()=>{const f=fixture();try{const r=approved(f.bank,row({subject:'國語／國文',unit:'成語',tags:[],question:{type:'short',prompt:'興高采烈是什麼意思？',answer:'心情高興，興致很高。',explanation:'描述高興的樣子。'}}));const request={grade:scope.grade,subject:'國文',unit:'能了解基礎成語'};assert.deepEqual(f.bank.retrieve(request).map(q=>q.id),[r.id]);assert.equal(f.bank.list({subject:'國語'}).total,1);assert.equal(f.bank.retrieve({...request,unit:'能了解基礎分數'}).length,0);assert.equal(f.bank.retrieve({...request,grade:'國小四年級'}).length,0)}finally{f.close()}});
test('empty and pending banks explain what the teacher must do without calling AI',async()=>{const f=fixture();try{const ai=()=>{throw Error('must not call')};await assert.rejects(f.bank.generate(scope,ai),/題庫是空的/);f.bank.save(row());await assert.rejects(f.bank.generate(scope,ai),/尚未完成審核/)}finally{f.close()}});
test('8 choices and 2 applications overrides default total and checks the exact generated quota',async()=>{const f=fixture();try{const r=approved(f.bank);const request={...scope,count:3,material:'選擇題8題，應用題2題'};const generated=[...Array.from({length:7},(_,i)=>({...r.question,prompt:`第${i+1}種情境：計算 23 + 14 的結果為何？`,sourceIds:[r.id]})),...Array.from({length:2},(_,i)=>({type:'short',format:'application',prompt:`第${i+1}盒有23枝筆，又放進14枝，現在共幾枝？`,answer:'37',explanation:'23+14=37',sourceIds:[r.id]}))];const result=await f.bank.generate(request,async(prompt,json,schema)=>{assert.equal(schema.properties.questions.minItems,9);assert.match(prompt,/"choice":7,"application":2/);return JSON.stringify({questions:generated})});assert.equal(result.questions.length,10);assert.equal(result.questions.filter(q=>q.format==='application').length,2);const app=result.questions[8];app.teacherReview=questionReviewContent(app,scope);assert.equal(hasQuestionReview({...app,format:undefined},scope),false);await assert.rejects(f.bank.generate(request,async()=>JSON.stringify({questions:generated.map(q=>({...q,format:undefined}))})),/配額/)}finally{f.close()}});
