import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,rmSync} from 'node:fs';import {join} from 'node:path';import {tmpdir} from 'node:os';import {createClassroom} from '../desktop/service.mjs';
const row={grade:'國小三年級',subject:'國語／國文',unit:'成語',textbook:'',semester:'',difficulty:'一般',tags:['成語'],source:'教師自編',url:'',rights:'自編，供教學及 AI 參考',question:{type:'short',prompt:'說明「一心一意」的意思。',answer:'專心，沒有其他念頭。',explanation:'形容心思專注。'}};
test('teacher bank persists across restart, source retirement blocks publication and students cannot access bank',async()=>{
 const directory=mkdtempSync(join(tmpdir(),'rag-service-'));let service=createClassroom({directory,setupCode:'qa'});
 try{let {token}=await service.call('teacherRegister',{email:'rag@example.com',password:'password123',setupCode:'qa'});
 const call=(name,data)=>service.call(name,data,token);
 const {record}=await call('questionBank',{operation:'save',record:row});await call('questionBank',{operation:'review',id:record.id,revision:record.revision,confirmed:true});
 const {questions}=await call('teacherAI',{mode:'ragQuestions',...row,count:1,material:''});assert.equal(questions[0].provenance.kind,'bank');
 const {classId}=await call('classroomAction',{type:'createClass',name:'測試班',grade:row.grade,requestId:crypto.randomUUID()});await call('classroomAction',{type:'registration',classId,open:true,requestId:crypto.randomUUID()});await call('setClassOpen',{open:true});const state=await call('state',{});const code=state.state.classes[0].code;const student=await service.call('studentAccess',{code,name:'測試同學',birthday:'0101',register:true});
 for(const operation of ['list','save','import','review','retire','webLibrary','prepareWebBatch','importPrepared','importDrafts','confirmSelection','resourceKeyStatus','saveResourceKey','deleteResourceKey','searchResources','curriculumCoverage'])await assert.rejects(service.call('questionBank',{operation,record:row},student.token),e=>e.status===403);
 await assert.rejects(service.call('teacherAI',{mode:'ragQuestions',...row,count:1},student.token),e=>e.status===403);
 const assignment={...row,title:'成語練習',status:'draft',questions};await call('classroomAction',{type:'saveAssignment',classId,assignment,requestId:crypto.randomUUID()});
 service.close();service=createClassroom({directory});({token}=await service.call('teacherLogin',{email:'rag@example.com',password:'password123'}));
 assert.equal((await call('questionBank',{operation:'list'})).counts.approved,1);assert.equal((await call('teacherAI',{mode:'ragQuestions',...row,count:1})).questions.length,1);
 await call('questionBank',{operation:'retire',id:record.id,revision:record.revision});await assert.rejects(call('classroomAction',{type:'saveAssignment',classId,assignment:{...assignment,status:'published'},requestId:crypto.randomUUID()}),/來源已更新或停用/);
 }finally{service.close();rmSync(directory,{recursive:true,force:true})}
});
test('bulk prepared import persists only pending records and skips duplicate imports',async()=>{const directory=mkdtempSync(join(tmpdir(),'prepared-import-'));let service=createClassroom({directory,setupCode:'qa'});try{const {token}=await service.call('teacherRegister',{email:'import@example.com',password:'password123',setupCode:'qa'});const call=data=>service.call('questionBank',data,token);const first=await call({operation:'importPrepared'});assert(first.imported>=0);const second=await call({operation:'importPrepared'});assert.equal(second.imported,0);assert.equal(second.skipped,first.imported+first.skipped);const result=await call({operation:'list'});assert.equal(result.counts.approved||0,0);assert.equal(result.counts.pending||0,first.imported)}finally{service.close();rmSync(directory,{recursive:true,force:true})}});
test('supplemental AI preparation persists issues without automatically importing or approving them',async()=>{
 const {preparedLibraryRows,supplementalDraftRows}=await import('../desktop/web-question-library.mjs');const source=supplementalDraftRows()[0];
 const directory=mkdtempSync(join(tmpdir(),'supplement-resume-'));let calls=0;const service=createClassroom({directory,setupCode:'qa',gemini:async({prompt})=>{
  calls++;assert(prompt.startsWith('整理已有來源題'));const inputs=JSON.parse(prompt.split('來源資料：')[1]);const all=new Map(preparedLibraryRows().map(r=>[r.id,r]));
  return JSON.stringify({items:inputs.map(x=>({id:x.id,grade:all.get(x.id).record.grade,unit:'測試範圍',tags:['測試'],solvedAnswer:all.get(x.id).originalAnswer,answerUnit:'',explanation:'本題為隔離測試用的來源整理回應，依據題目已知條件列式計算並核對結果；實際內容仍需教師審核。',usable:false,reason:'隔離測試保留為疑義，不進入可用題庫'}))});
 }});try{const {token}=await service.call('teacherRegister',{email:'resume@example.com',password:'password123',setupCode:'qa'});await service.call('saveTeacherKey',{key:'mock-key-never-real-secret-12345'},token);const first=await service.call('questionBank',{operation:'prepareWebBatch'},token);assert.equal(calls,1);assert.equal(first.processed,20);assert.equal(first.needsCheck,20);const issues=await service.call('questionBank',{operation:'webLibrary',filters:{kind:'issues',query:source.record.question.prompt.slice(0,20)}},token);assert(issues.records.some(r=>r.id===source.id));assert.equal((await service.call('questionBank',{operation:'list'},token)).total,0);
 }finally{service.close();rmSync(directory,{recursive:true,force:true})}
});
