import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {createQuestionBank} from '../desktop/question-bank.mjs';import {interpretIntent,selectRelevant} from '../desktop/rag-intent.mjs';import {parsePreparation,preparationPrompt} from '../desktop/library-preparation.mjs';
const data={grade:'國小三年級',subject:'國文',unit:'看生活故事選出合適的四字詞',material:'選擇題1題',count:1};
const intent={summary:'認識常見成語的情境用法',queries:['成語'],constraints:['避免文言文'],counts:{choice:1,short:0,application:0,work:0},needsClarification:false,clarification:''};
test('AI intent precedes retrieval; semantic candidate selection is restricted to server IDs and scope',async()=>{const db=new DatabaseSync(':memory:');try{const bank=createQuestionBank(db);const r=bank.save({grade:data.grade,subject:'國語／國文',unit:'成語',source:'自編',rights:'原創供課堂使用',question:{type:'choice',prompt:'做事專心可以用哪個成語？',options:['一心一意','半途而廢','畫蛇添足','守株待兔'],answer:'A',explanation:'一心一意表示專心致志。'}});bank.review({id:r.id,revision:r.revision,confirmed:true});let calls=[];const result=await bank.generateWithIntent(data,async(prompt)=>{calls.push(prompt);if(prompt.startsWith('任務：解析'))return JSON.stringify(intent);assert.match(prompt,/候選題相關性/);assert.match(prompt,/一心一意/);return JSON.stringify({ids:[r.id],reason:'原題對應專心的成語概念，符合指定年級及要求'})});assert.equal(calls.length,2);assert.equal(result.questions.length,1);assert.equal(result.questions[0].provenance.kind,'bank');assert.equal(result.retrieval.intent.total,1);assert.equal(result.retrieval.intent.queries[0],'成語');}finally{db.close()}});
test('intent rejects changed explicit quota and missing/ambiguous scope',async()=>{await assert.rejects(interpretIntent(data,async()=>JSON.stringify({...intent,counts:{choice:0,short:1,application:0,work:0}})),/配額/);await assert.rejects(interpretIntent(data,async()=>JSON.stringify({...intent,needsClarification:true,clarification:'請指定想練習的單元'})),/請補充/);await assert.rejects(interpretIntent({...data,grade:'高中'},async()=>{throw Error('must not call')}),/年級/)});
test('semantic selection cannot invent IDs or duplicate source references',async()=>{for(const ids of [['fake'],['one','one']])await assert.rejects(selectRelevant(intent,data,[{id:'one',question:{}}],async()=>JSON.stringify({ids,reason:'相關'})),/來源/)});
const source={id:'one',subject:'自然科學',subset:'junior_science_exam',split:'test',row:3,sourceUrl:'https://example.com/source.csv',question:{type:'choice',prompt:'哪一種動物屬於哺乳類？',options:['鯨魚','青蛙','鯉魚','蝴蝶'],answer:'A',explanation:''}};
const item={id:'one',grade:'國中一年級',unit:'動物分類',tags:['哺乳類'],difficulty:'基礎',solvedAnswer:'A',explanation:'鯨魚用肺呼吸，母體會分泌乳汁哺育幼體，因此屬於哺乳類；青蛙、鯉魚與蝴蝶則分屬其他類群。',usable:true,reason:''};
test('preparation independently solves without exposing source answer and preserves original wording',()=>{assert.doesNotMatch(preparationPrompt([source]),/"answer"/);const r=parsePreparation(JSON.stringify({items:[item]}),[source])[0];assert.equal(r.status,'prepared');assert.equal(r.record.question.answer,'A');assert.equal(r.record.question.prompt,source.question.prompt);assert.equal(r.record.grade,'國中一年級');assert.equal(r.record.status,undefined)});
test('answer disagreement, missing context and incomplete batches cannot become prepared bank records',()=>{for(const patch of [{solvedAnswer:'B'},{usable:false,reason:'缺少必要圖片'},{explanation:'答案為A'}])assert.equal(parsePreparation(JSON.stringify({items:[{...item,...patch}]}),[source])[0].status,'needs-check');assert.throws(()=>parsePreparation(JSON.stringify({items:[]}),[source]),/題數/);assert.throws(()=>parsePreparation(JSON.stringify({items:[{...item,id:'fake'}]}),[source]),/ID/)});
test('a malformed grade is isolated without losing other valid questions in the same preparation batch',()=>{const other={...source,id:'two'};const results=parsePreparation(JSON.stringify({items:[item,{...item,id:'two',grade:'高中一年級'}]}),[source,other]);assert.deepEqual(results.map(r=>r.status),['prepared','needs-check']);assert.equal(results[1].record.grade,'')});

test('bare JSON arrays still require the exact complete source ID set',()=>{assert.equal(parsePreparation(JSON.stringify([item]),[source])[0].status,'prepared');assert.throws(()=>parsePreparation(JSON.stringify([item,item]),[source,{...source,id:'two'}]),/ID/)});

test('an explanation conclusion conflicting with the answer is quarantined',()=>{const r=parsePreparation(JSON.stringify({items:[{...item,explanation:item.explanation+'故選 D。'}]}),[source])[0];assert.equal(r.status,'needs-check');assert.match(r.issue,/結論/)});
