import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {createTeachingSources} from '../desktop/teaching-sources.mjs';import {createQuestionBank} from '../desktop/question-bank.mjs';import {createClassroom} from '../desktop/service.mjs';import {hasQuestionReview} from '../functions/question-review.mjs';import {cleanResourceLinks} from '../functions/open-data.mjs';import {studentView} from '../functions/views.mjs';
const scope={grade:'國小五年級',subject:'資訊科技',unit:'網路安全',material:'選擇題1題',count:1};
const intent={summary:'辨識不明連結與保護個資',queries:['網路安全'],constraints:['適合國小五年級'],counts:{choice:1,short:0,application:0,work:0},needsClarification:false,clarification:''};
function model({badQuote=false,badVerdict=false,unknownSource=false}={}){return async prompt=>{
 if(prompt.startsWith('任務：解析'))return JSON.stringify(intent);
 if(prompt.startsWith('獨立核對'))return JSON.stringify({items:[{index:1,supported:!badVerdict,inScope:true,unambiguous:true,explanationCorrect:true,reason:badVerdict?'答案無來源支持':'符合引用'}]});
 const payload=JSON.parse(prompt.split('\n資料：')[1]),source=payload.references.find(r=>r.kind==='question');assert(source);return JSON.stringify({questions:[{type:'choice',prompt:'陌生人傳來索取帳號密碼的連結，你應該如何處理？',options:['拒絕提供並向可信任的大人求助','提供密碼','轉傳密碼','付款取得獎品'],answer:'A',explanation:'不向陌生人提供帳號密碼，遇到可疑訊息向可信任的大人求助。',sourceIds:[unknownSource?'invented':source.id],evidence:[{id:source.id,quote:badQuote?'這是一段根本不在官方原文的虛構引文':source.body.slice(0,30)}]}]});
}}
test('official files retain provenance, question answers and knowledge categories without false approval',()=>{const t=createTeachingSources();const info=t.info();assert.equal(info.counts.question,440);assert.equal(info.counts.knowledge,5383);assert(info.counts.link>0);const r=t.search(scope);assert(r.length);assert(r.every(r=>r.reviewStatus==='unreviewed'&&r.kind!=='link'&&r.snapshot.length===64));assert.equal(t.search({...scope,subject:'國語',unit:'基礎成語'}).length,0);assert.equal(t.search({...scope,subject:'數學',unit:'網路安全'}).length,0);assert(t.search({...scope,subject:'自然',unit:'臺灣黑熊'}).length>0);assert.equal(t.search({...scope,textbook:'指定版本'}).length,0);assert.equal(t.search({...scope,semester:'上學期'}).length,0);});
test('resource links cannot masquerade as answer evidence and canonical URLs defeat forged metadata',()=>{const t=createTeachingSources();const rows=t.search(scope,{queries:['網路'],linksOnly:true});assert(rows.length);const r=rows[0];assert.throws(()=>t.resolve([t.citation(r)],scope));const l=t.resolveLink({...r,title:'fake',url:'https://evil.example'},scope);assert.equal(l.title,r.title);assert.equal(l.url,r.url);assert.equal(cleanResourceLinks([l]).length,1);assert.throws(()=>t.resolveLink(r,{...scope,subject:'數學'}));assert.throws(()=>t.resolveLink({...r,snapshot:'0'.repeat(64)},scope));assert.throws(()=>cleanResourceLinks([{...l,url:'https://video.cloud.edu.tw@evil.example/x'}]));});
test('empty teacher bank can develop grounded questions, confirm once and reuse without AI',async()=>{const db=new DatabaseSync(':memory:');try{const teaching=createTeachingSources(db),bank=createQuestionBank(db,{teaching});const result=await bank.generateWithIntent(scope,model());assert.equal(result.retrieval.grounded,1);const q=result.questions[0];assert.equal(q.provenance.kind,'grounded');assert(!hasQuestionReview(q,scope));assert.throws(()=>bank.assertPublicationSource(q,scope));const approved=bank.confirmSelection({question:q,scope,confirmed:true,requestId:crypto.randomUUID()});assert.equal(approved.record.originKind,'grounded');assert.equal(approved.record.derivedFrom[0].id,q.provenance.sources[0].id);assert(hasQuestionReview(approved.question,scope));const reused=bank.quickQuestions(scope);assert.equal(reused.questions.length,1);assert(hasQuestionReview(reused.questions[0],scope));bank.assertPublicationSource(reused.questions[0],scope);assert.equal(bank.quickQuestions({...scope,subject:'國語'}).questions.length,0);}finally{db.close()}});
test('fabricated evidence, invented IDs and independent review failures never enter question bank',async()=>{for(const opts of [{badQuote:true},{badVerdict:true},{unknownSource:true}]){const db=new DatabaseSync(':memory:');try{const bank=createQuestionBank(db,{teaching:createTeachingSources(db)});await assert.rejects(()=>bank.generateWithIntent(scope,model(opts)));assert.equal(bank.list().total,0)}finally{db.close()}}});
test('development cannot silently change explicit question quotas or invent unrelated content',async()=>{const db=new DatabaseSync(':memory:');try{const bank=createQuestionBank(db,{teaching:createTeachingSources(db)});await assert.rejects(()=>bank.generateWithIntent({...scope,material:'選擇題2題'},model()),/配額/);await assert.rejects(()=>bank.generateWithIntent({...scope,subject:'國語',unit:'成語'},model()),/沒有符合/);assert.equal(bank.quickQuestions(scope).questions.length,0)}finally{db.close()}});
test('unknown and cross-subject references cannot be teacher-confirmed as official evidence',()=>{const db=new DatabaseSync(':memory:');try{const teaching=createTeachingSources(db),bank=createQuestionBank(db,{teaching}),r=teaching.search(scope)[0];const q={type:'short',prompt:'說明網路安全。',answer:'保護帳密。',explanation:'不可隨意提供帳密。',provenance:{kind:'grounded',sources:[teaching.citation(r)]}};assert.throws(()=>bank.confirmSelection({question:q,scope:{...scope,subject:'自然'},confirmed:true,requestId:crypto.randomUUID()}),/範圍/);assert.throws(()=>bank.confirmSelection({question:{...q,provenance:{kind:'grounded',sources:[{id:'fake',revision:1}]}},scope,confirmed:true,requestId:crypto.randomUUID()}),/不存在/)}finally{db.close()}});
test('archived content remains available after bundled snapshot changes',()=>{const db=new DatabaseSync(':memory:');try{const t=createTeachingSources(db),r=t.search(scope)[0];const empty=createTeachingSources(db,{catalog:{sources:[],records:[],audit:{}}});assert.equal(empty.get(r.id).body,r.body);assert.equal(empty.search(scope).length,0);assert.equal(empty.resolve([t.citation(r)],scope)[0].id,r.id)}finally{db.close()}});
test('teacher resource search reuses parsed concepts; references persist but source answers do not leak to students',async()=>{const directory=mkdtempSync(join(tmpdir(),'teaching-service-'));const service=createClassroom({directory,setupCode:'test'});try{const {token}=await service.call('teacherRegister',{email:'teach@example.com',password:'password123',setupCode:'test'});const call=(operation,data={})=>service.call('questionBank',{operation,...data},token);const act=data=>service.call('classroomAction',{requestId:crypto.randomUUID(),...data},token);const {classId}=await act({type:'createClass',name:'網路班',grade:scope.grade});const resources=await call('learningResources',{filters:{...scope,query:'我要小朋友保護自己',queries:['網路安全']}});assert(resources.records.length);assert(resources.records.some(r=>r.id.startsWith('41560:')));const r=resources.records.find(r=>r.id.startsWith('41560:'));const source=createTeachingSources().search(scope)[0];const q={type:'short',prompt:'如何保護自己的帳密？',answer:'不分享帳密。',explanation:'帳密不應交給陌生人。',provenance:{kind:'grounded',sources:[createTeachingSources().citation(source)]}};const approved=await call('confirmSelection',{question:q,scope,confirmed:true,requestId:crypto.randomUUID()});await act({type:'saveAssignment',classId,assignment:{id:'official',...scope,title:'網路安全',status:'published',questions:[approved.question],resourceLinks:[r]}});const state=(await service.call('state',{},token)).state;assert.equal(state.assignments[0].resourceLinks[0].source,'中小學資訊素養教學教材');const view=studentView({...state,students:[{id:'test-student',classId}]},'test-student');assert(!JSON.stringify(view.assignments).includes(source.id));assert(!('answer' in view.assignments[0].questions[0]));assert.equal(view.assignments[0].resourceLinks[0].id,r.id);await assert.rejects(()=>call('learningResources',{filters:{...scope,queries:['x'.repeat(101)]}}));}finally{service.close();rmSync(directory,{recursive:true,force:true})}});
