import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {createQuestionBank} from '../desktop/question-bank.mjs';
import {seedState,migrateCollection,applyAction} from '../functions/domain.mjs';
const row={grade:'國小三年級',subject:'數學',unit:'整數加法',textbook:'自編',semester:'上學期',difficulty:'一般',tags:['加法'],source:'教師自編',rights:'自編授權課堂及 AI 參考',question:{type:'choice',prompt:'計算 23 + 14 的結果為何？',options:['37','47','57','67'],answer:'A',explanation:'23+14=37'}};
test('one-step bank approval is atomic, retry-safe and rejects stale edits',()=>{const db=new DatabaseSync(':memory:');try{const bank=createQuestionBank(db),args={record:row,confirmed:true,requestId:'approval_123'};assert.throws(()=>bank.saveReviewed({...args,confirmed:false}));assert.equal(bank.list().total,0);assert.throws(()=>bank.saveReviewed({...args,record:{...row,rights:'待教師確認'}}));assert.equal(bank.list().total,0);const result=bank.saveReviewed(args);assert.equal(result.record.status,'approved');assert.deepEqual(bank.saveReviewed(args),result);assert.equal(bank.list().total,1);bank.save({...result.record,unit:'加法練習'});assert.throws(()=>bank.saveReviewed(args));assert.throws(()=>bank.saveReviewed({...args,record:result.record,requestId:'approval_456'}));}finally{db.close()}});
test('publishing grading and student analysis together preserves single token award',()=>{let s=migrateCollection(seedState());const task={id:'ux-task',title:'計算練習',questions:[row.question]};s.assignments=[task];const student=s.students[0];s.submissions=[{id:'ux-sub',studentId:student.id,assignmentId:task.id,status:'pending',answers:task.questions.map(()=> 'B')}];const before=student.balance,action={type:'review',submissionId:'ux-sub',requestId:'ux-review',score:0,reward:2,feedback:'請再試試看。',itemFeedback:task.questions.map(()=> '請參考詳解。'),analysis:'你可以先找出題目中的關鍵條件。'};const next=applyAction(s,action,{role:'teacher'});assert.equal(next.students[0].balance,before+2);assert.equal(next.submissions[0].publishedAnalysis,action.analysis);assert.equal(next.teacherAIResults['ux-sub'].studentFeedback.value,action.analysis);assert.deepEqual(applyAction(next,action,{role:'teacher'}),next);const updated=applyAction(next,{...action,type:'updateReview',requestId:'ux-update',analysis:'先把條件畫出來，再練習一題。'},{role:'teacher'});assert.equal(updated.students[0].balance,before+2);assert.equal(updated.submissions[0].publishedAnalysis,'先把條件畫出來，再練習一題。');assert.equal(s.students[0].balance,before);});
test('room layout and introduction save atomically and reject invalid plans',()=>{const s=migrateCollection(seedState()),snapshot=structuredClone(s),plan={title:'我的海洋館',description:'不同高度的收藏',goal:'佈置海洋館',wishes:['whale'],completed:false},action={type:'saveRoom',studentId:'s1',requestId:'ux-room',room:{...s.rooms.s1,wall:'blue'},plan},actor={role:'student',studentId:'s1'};const next=applyAction(s,action,actor);assert.equal(next.rooms.s1.wall,'blue');assert.deepEqual(next.students[0].creativePlan,plan);assert.throws(()=>applyAction(s,{...action,plan:{...plan,title:''}},actor));assert.deepEqual(s,snapshot);assert.deepEqual(applyAction(next,action,actor),next);});
