import {chromium,expect} from '@playwright/test';import assert from 'node:assert/strict';import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join,resolve} from 'node:path';import {createClassroom} from '../desktop/service.mjs';import {classroomHttp} from '../desktop/http.mjs';
const directory=mkdtempSync(join(tmpdir(),'rag-browser-'));let calls=0;const service=createClassroom({directory,setupCode:'qa',gemini:async({prompt,schema})=>{calls++;if(prompt.startsWith('任務：解析出題意圖'))return JSON.stringify({summary:'理解並運用基礎成語',queries:['成語'],constraints:['國小三年級生活情境'],counts:{choice:0,short:3,application:0,work:0},needsClarification:false,clarification:''});if(prompt.startsWith('任務：核對RAG候選題相關性')){const data=JSON.parse(prompt.slice(prompt.indexOf('資料：')+3));return JSON.stringify({ids:data.candidates.map(c=>c.id),reason:'題目對應成語意義與情境用法'})}const references=JSON.parse(prompt.slice(prompt.indexOf('資料：')+3)).references;return JSON.stringify({questions:Array.from({length:schema.properties.questions.minItems},(_,i)=>({type:'short',prompt:`請用「一心一意」描述你${i?'練習樂器':'閱讀課本'}時的情形。`,answer:'用專注的情境表達一心一意。',explanation:'情境應表現專心，沒有其他念頭。',sourceIds:[references[0].id]}))})}});
const login=await service.call('teacherRegister',{email:'rag-qa@example.com',password:'password123',setupCode:'qa'});await service.call('saveTeacherKey',{key:'test-key-not-real-secret-123456'},login.token);const {classId}=await service.call('classroomAction',{type:'createClass',name:'RAG測試班',grade:'國小三年級',requestId:crypto.randomUUID()},login.token);
const server=classroomHttp(service,{webRoot:resolve('dist-desktop'),port:4191});await new Promise(r=>server.listen(4191,'127.0.0.1',r));const browser=await chromium.launch({channel:'chrome',headless:true});
try{const page=await browser.newPage({viewport:{width:1280,height:900}});await page.context().addCookies([{name:'tc-session',value:login.token,url:'http://127.0.0.1:4191',httpOnly:true,sameSite:'Strict'}]);await page.goto('http://127.0.0.1:4191');
 await page.getByRole('button',{name:/教學與出題/}).click();await page.getByRole('button',{name:'建立學習任務'}).click();
 const initial=page.getByRole('dialog');await initial.getByLabel('任務名稱').fill('保留我的草稿');
 // Dialog padding targets the dialog itself, just like its backdrop. Only geometry distinguishes them.
 const bounds=await initial.boundingBox();await page.mouse.click(bounds.x+8,bounds.y+8);await expect(initial).toBeVisible();await expect(initial.getByLabel('任務名稱')).toHaveValue('保留我的草稿');
 await page.mouse.move(bounds.x+8,bounds.y+8);await page.mouse.down();await page.mouse.move(2,2);await page.mouse.up();await expect(initial).toBeVisible();
 await page.setViewportSize({width:390,height:844});const mobileBounds=await initial.boundingBox();await page.mouse.click(mobileBounds.x+8,mobileBounds.y+8);await expect(initial).toBeVisible();await expect(initial.getByLabel('任務名稱')).toHaveValue('保留我的草稿');await page.setViewportSize({width:1280,height:900});
await initial.getByLabel('單元與學習目標').fill('能了解基礎成語');await initial.getByLabel('教材或出題要求（不含學生個資）').fill('選擇題8題，應用題2題');await expect(initial.getByText('已辨識題型配額，共 10 題（優先於下方總題數）。')).toBeVisible();await initial.getByRole('button',{name:'題庫組卷與 AI 延伸'}).click();await expect(initial.getByRole('alert')).toContainText('題庫是空的');assert.equal(calls,0);
 await initial.getByRole('button',{name:'開啟教師題庫（保留目前草稿）'}).click();await page.getByRole('dialog').last().getByRole('button',{name:'關閉',exact:true}).click();await expect(initial.getByLabel('任務名稱')).toHaveValue('保留我的草稿');await page.mouse.click(2,2);await expect(initial).not.toBeVisible();await page.getByRole('button',{name:/教師題庫/}).click();
 await page.getByRole('button',{name:'瀏覽已收集的網路題庫'}).click();await expect(page.locator('.web-library')).toContainText('810 題來源文字題');await page.getByLabel('網路題庫關鍵字').fill('迫不及待');await page.getByRole('button',{name:'搜尋網路題庫資料'}).click();await expect(page.locator('.web-library')).toContainText('國小三年級');await expect(page.locator('.web-library')).toContainText('原卷未附答案');await page.getByRole('button',{name:'選取此題，補齊資料'}).first().click();await expect(page.locator('.bank-editor').getByLabel('年級',{exact:true})).toHaveValue('國小三年級');await expect(page.locator('.bank-editor').getByRole('textbox',{name:'詳解',exact:true})).not.toHaveValue('');await page.locator('.bank-editor').getByRole('button',{name:'關閉編輯'}).click();await page.getByLabel('網路題庫關鍵字').fill('');await page.locator('.web-library').getByLabel('資料類型').selectOption('questions');await page.getByRole('button',{name:'選取此題，補齊資料'}).first().click();const bankEditor=page.locator('.bank-editor');await expect(bankEditor.getByLabel('年級',{exact:true})).toHaveValue('');await expect(bankEditor.getByLabel('單元',{exact:true})).toHaveValue('');await expect(bankEditor.getByLabel('詳解',{exact:true})).toHaveValue('');await bankEditor.getByRole('button',{name:'關閉編輯'}).click();
 await page.locator('.web-library').getByLabel('資料類型').selectOption('sources');await page.locator('.web-library').getByLabel('來源年級').selectOption('3');await page.getByLabel('網路題庫關鍵字').fill('成語');await page.getByRole('button',{name:'搜尋網路題庫資料'}).click();await expect(page.locator('.web-library')).toContainText('三年級成語測驗題目');await expect(page.locator('.web-library')).toContainText('著作權所有');
 await page.setViewportSize({width:390,height:844});await page.locator('.web-library').scrollIntoViewIfNeeded();await page.screenshot({path:'work/web-library-mobile.png'});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'web library mobile overflow');await page.setViewportSize({width:1280,height:900});
 await page.getByText('匯入／匯出題庫（JSON）',{exact:true}).click();
 const row={grade:'國小三年級',subject:'國語／國文',unit:'成語',textbook:'',semester:'',difficulty:'一般',tags:['成語'],source:'教師自編',url:'',rights:'自編供教學及 AI 參考',question:{type:'short',prompt:'請說明「一心一意」的意思。',answer:'專注，沒有其他念頭。',explanation:'用來形容心思專注。'}};
 await page.getByLabel('題庫 JSON',{exact:true}).fill(JSON.stringify({records:[row]}));await page.getByRole('button',{name:'匯入為待審核題目'}).click();await expect(page.getByRole('status')).toContainText('已匯入 1 題');
 await page.getByRole('button',{name:'查看／編輯／審核'}).click();await page.getByRole('checkbox',{name:/我已核對題意/}).check();await page.getByRole('button',{name:'確認正確，加入可用題庫'}).click();await expect(page.getByRole('status')).toContainText('此題已審核');await page.getByRole('button',{name:'關閉編輯'}).click();await page.screenshot({path:'work/rag-bank.png',fullPage:true});
 await page.getByRole('button',{name:/教學與出題/}).click();await page.getByRole('button',{name:'建立學習任務'}).click();const dialog=page.getByRole('dialog');await dialog.getByLabel('任務名稱').fill('RAG 成語練習');await dialog.getByLabel('單元與學習目標').fill('能了解基礎成語');await dialog.getByLabel('科目（可自訂）').fill('國文');await dialog.getByLabel('出題數量').selectOption('3');await dialog.getByRole('button',{name:'題庫組卷與 AI 延伸'}).click();await expect(dialog.getByRole('status').filter({hasText:'題庫原題'})).toContainText('題庫原題 1 題，AI 延伸 2 題',{timeout:150000});assert.equal(calls,3);
 const publish=dialog.getByRole('button',{name:'審閱完成，發布任務'});await expect(publish).toBeDisabled();await expect(dialog.getByLabel('確認第1題正確性')).toBeChecked();await expect(dialog.getByLabel('確認第2題正確性')).not.toBeChecked();
 await dialog.locator('.question-origin').nth(1).getByText('查看參考來源（1）').click();await dialog.locator('.question-origin').nth(1).getByRole('button',{name:'查看題庫原題與答案'}).click();await expect(dialog.locator('.bank-reference')).toContainText('請說明「一心一意」的意思');
 await dialog.getByLabel('確認第2題正確性').check();await dialog.getByLabel('確認第3題正確性').check();await expect(publish).toBeEnabled();await dialog.getByLabel('第2題解析與提示').fill('修改後仍需老師核對。');await expect(dialog.getByLabel('確認第2題正確性')).not.toBeChecked();await expect(publish).toBeDisabled();await dialog.getByLabel('確認第2題正確性').check();
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'work/rag-review-mobile.png',fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'mobile overflow');await dialog.getByRole('button',{name:'保存草稿'}).click();await expect(dialog).not.toBeVisible();
 await page.getByRole('button',{name:'繼續編輯'}).click();await expect(page.getByLabel('確認第2題正確性')).toBeChecked();await page.getByRole('button',{name:'審閱完成，發布任務'}).click();await expect(page.getByRole('dialog')).not.toBeVisible();const state=await service.call('state',{},login.token);assert.equal(state.state.assignments[0].status,'published');assert.equal(state.state.assignments[0].questions[1].provenance.kind,'rag');console.log('Real local HTTP + browser + mock Gemini: import/review, RAG original+extension, reference viewing, per-question approval, edit invalidation, saved review/reopen, mobile layout and publication passed.');
}finally{await browser.close();await new Promise(r=>server.close(r));service.close();rmSync(directory,{recursive:true,force:true})}
