import {useUnsavedChanges} from './unsaved-changes.mjs';
import React,{useEffect,useState,lazy,Suspense}from'react';
import{CREATIVE_THEMES}from'../functions/creative-room.mjs';import{TOYS,MACHINES}from'../functions/domain.mjs';import{prizePool}from'../functions/machine.mjs';
const Room=lazy(()=>import('./World.jsx').then(m=>({default:m.RoomWorld})));
export const blankCreativePlan={title:'我的創作房間',description:'',goal:'',wishes:[],completed:false};
export function CreativePlan({student,inventory,act,busy,value,onChange}){
 const[localPlan,setPlan]=useState(student.creativePlan||blankCreativePlan),[dirty,setDirty]=useState(false),[message,setMessage]=useState('');
 const plan=value||localPlan;
 useUnsavedChanges(!onChange&&dirty);
 useEffect(()=>{if(!onChange&&!dirty)setPlan(student.creativePlan||blankCreativePlan)},[JSON.stringify(student.creativePlan)]);
 const edit=c=>{if(onChange)onChange({...plan,...c});else{setPlan(p=>({...p,...c}));setDirty(true)}setMessage('')};
 return <section className="panel creative-plan"><div><div className="eyebrow">MY NEXT IDEA / 我的下一個點子</div><h2>這次，想打造什麼？</h2><p>你可以隨時改變想法，沒有期限，也不影響代幣或成績。</p></div><fieldset disabled={busy}><div className="form-grid"><label className="field">房間名稱<input aria-label="房間名稱" maxLength={40} value={plan.title} onChange={e=>edit({title:e.target.value})}/></label><label className="field">找個起點<select aria-label="創作靈感" defaultValue="" onChange={e=>{if(e.target.value)edit({goal:e.target.value,completed:false})}}><option value="">選一個靈感，也能自己寫</option>{CREATIVE_THEMES.map(t=><option key={t}>{t}</option>)}</select></label></div><label className="field">我的創作目標<input aria-label="我的創作目標" maxLength={120} placeholder="例如：用展示架打造海洋觀察角" value={plan.goal} onChange={e=>edit({goal:e.target.value,completed:false})}/></label><label className="field">作品介紹<textarea aria-label="作品介紹" maxLength={200} placeholder="介紹你的設計巧思；投稿時會和房間一起送老師審核。" value={plan.description} onChange={e=>edit({description:e.target.value})}/></label><label><input type="checkbox" checked={plan.completed} onChange={e=>edit({completed:e.target.checked})}/> 我覺得這次目標完成了</label><details className="creative-wishes"><summary>我的收藏願望 · {plan.wishes.length}/6</summary><p>標記想收藏的寶物；這不會花代幣，也不保證夾取結果。</p><div className="wish-grid">{TOYS.map(t=>{const has=inventory.some(i=>i.kind===t.id),machine=MACHINES.find(m=>prizePool(m.id).includes(t.id));return <label key={t.id}><input type="checkbox" checked={plan.wishes.includes(t.id)} disabled={!plan.wishes.includes(t.id)&&plan.wishes.length>=6} onChange={e=>edit({wishes:e.target.checked?[...plan.wishes,t.id]:plan.wishes.filter(k=>k!==t.id)})}/><span><b>{t.name}</b><small>{has?'已收藏':machine?.name}</small></span></label>})}</div></details>{!onChange&&<button className="primary" disabled={!dirty||!plan.title.trim()} onClick={async()=>{if(await act({type:'saveCreativePlan',studentId:student.id,plan},{message:'創作計畫已保存'})){setDirty(false);setMessage('計畫已保存')}}}>保存創作計畫</button>}{onChange&&<p className="fine">名稱、介紹與目標會與房間佈置一起保存，請使用預覽下方的保存按鈕。</p>}<span role="status"> {!onChange&&dirty?'尚未保存':message}</span></fieldset></section>
}
export function ClassExhibition({teacher=false,student,students=[],activeClass,classes=[],setClassId,exhibits=[],act,busy}){
 const[opened,setOpened]=useState(null),[note,setNote]=useState(''),[message,setMessage]=useState('');
 const list=exhibits.filter(e=>e.classId===activeClass?.id&&(teacher||e.status==='approved'||e.mine||e.studentId===student?.id));
 const own=list.find(e=>e.mine||(!teacher&&e.studentId===student?.id)),focused=list.find(e=>e.id===opened);
 useEffect(()=>{setOpened(null);setNote('');setMessage('')},[activeClass?.id]);
 const run=async(a,msg)=>{if(await act(a,{message:msg})){setMessage(msg);setOpened(null);setNote('')}};
 return <section className="class-exhibition"><div className="page-title"><div><div className="eyebrow">CLASS EXHIBITION / 班級小策展</div><h1>每個房間，都有自己的故事。</h1><p>自願投稿、老師審核、本班欣賞。沒有按讚或收藏數量排行榜。</p></div></div>{!teacher&&student&&<div className="panel exhibit-submit"><h2>分享我的房間</h2><p>先到寶物房保存創作計畫與佈置，再送出。投稿只使用已保存的房間，不會公開姓名與學習資料；名稱及介紹請勿填寫個資。更新投稿會撤下舊作品，重新由老師審核。</p><button className="primary" disabled={busy||!student.creativePlan?.title} onClick={()=>run({type:'submitExhibit',studentId:student.id},'已送老師審核；通過後本班才能看見')}>{own?'用已保存房間重新投稿':'投稿已保存的房間'}</button>{own&&<button disabled={busy} onClick={()=>run({type:'withdrawExhibit',studentId:student.id},'作品已撤回')}>撤回我的作品</button>}{!student.creativePlan?.title&&<p>請先到「我的寶物房」保存房間名稱與創作計畫。</p>}{own?.note&&<p>老師建議：{own.note}</p>}</div>}<p role="status">{message}</p><div className="exhibit-grid">{list.map(e=><article className="panel" key={e.id}><span className={'assessment-status '+(e.status==='approved'?'reviewed':e.status==='pending'?'pending':'not-started')}>{({approved:'本班展出',pending:'待老師審核',changes:'請修改後再投稿'})[e.status]}</span><h2>{e.title}</h2><p>{e.description||'作者還沒有填寫介紹。'}</p><small>{teacher?students.find(s=>s.id===e.studentId)?.name||'學生':e.authorLabel||(e.studentId===student?.id?'我的作品':'同班創作者')}</small><button onClick={()=>{setOpened(e.id);setNote(e.note||'')}}>查看作品：{e.title}</button></article>)}</div>{!list.length&&<div className="panel"><p>{teacher?'本班還沒有投稿作品。':'還沒有展出作品。你可以先完成自己的創作，再邀請老師策展。'}</p></div>}{focused&&<div className="panel exhibit-detail"><button onClick={()=>setOpened(null)}>關閉作品預覽</button><h2>{focused.title}</h2><p>{focused.description}</p><Suspense fallback={<p>正在準備投稿房間…</p>}><Room key={focused.id} room={focused.room} inventory={focused.inventory}/></Suspense><p className="fine">這是投稿時保存的房間，可拖曳旋轉欣賞。作者後來的修改不會直接改動這件作品。</p>{teacher&&<fieldset disabled={busy}><label className="field">給作者的建議<textarea aria-label="作品審核建議" maxLength={200} value={note} onChange={e=>setNote(e.target.value)}/></label><div className="exhibit-actions">{focused.status==='pending'&&<button className="primary" onClick={()=>run({type:'reviewExhibit',exhibitId:focused.id,status:'approved',note},'已核准在本班展出')}>核准本班展出</button>}<button onClick={()=>run({type:'reviewExhibit',exhibitId:focused.id,status:'changes',note},'已退回作者，作品不再對本班展示')}>{focused.status==='approved'?'撤下並給修改建議':'請修改後再投稿'}</button></div></fieldset>}</div>}</section>
}
