import React,{useState} from 'react';
export default function CurriculumResources({cloud}){
 const [open,setOpen]=useState(false),[coverage,setCoverage]=useState(null),[grade,setGrade]=useState(3),[subject,setSubject]=useState(''),[query,setQuery]=useState(''),[key,setKey]=useState(''),[configured,setConfigured]=useState(false),[results,setResults]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const call=(operation,data={})=>cloud.questionBank({operation,...data});
 async function run(fn){if(busy)return;setBusy(true);setError('');try{await fn()}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function load(g=grade,s=subject,page=0){setCoverage(await call('curriculumCoverage',{filters:{grade:g,subject:s,query:'',page}}))}
 async function search(page=1){const result=await call('searchResources',{query,page});setResults({...result,query})}
 return <section className="panel"><h2>108 課綱與教學資源</h2><p>以通用學習內容規劃跨版本教學。先確認各科題庫缺口，再找來源；課綱索引與搜尋結果不計入已審核題數。</p>
 {!open?<button disabled={busy} onClick={()=>run(async()=>{await load();const s=await call('resourceKeyStatus');setConfigured(s.configured);setOpen(true)})}>開啟課綱與資源中心</button>:<>
 <div className="form-grid"><label className="field"><span>課綱年級</span><select disabled={busy} value={grade} onChange={e=>{const g=Number(e.target.value);setGrade(g);run(()=>load(g))}}>{[3,4,5,6,7,8,9].map(g=><option key={g} value={g}>{g<7?'國小'+g:'國中'+(g-6)}年級</option>)}</select></label><label className="field"><span>課綱科目</span><select disabled={busy} value={subject} onChange={e=>{setSubject(e.target.value);run(()=>load(grade,e.target.value))}}><option value="">全部科目</option>{coverage?.matrix.map(r=><option key={r.subject}>{r.subject}</option>)}</select></label></div>
 <p className="notice">{coverage?.notice}</p><div style={{overflowX:'auto'}}><table style={{minWidth:560}}><thead><tr><th>科目</th><th>已審核題</th><th>待審核題</th><th>規劃主題</th><th>課綱代碼</th></tr></thead><tbody>{coverage?.matrix.filter(r=>!subject||r.subject===subject).map(r=><tr key={r.subject}><td>{r.subject}</td><td>{r.approved}</td><td>{r.pending}</td><td>{r.planningTopics}</td><td>{r.standardCodes}</td></tr>)}</tbody></table></div>
 <details><summary>查看通用主題與活動參考（{coverage?.total||0} 項）</summary>{coverage?.topics.map(t=><article key={t.id} className="panel"><h3>{t.name}</h3><p>{t.subject} · 建議 {t.grades.join('、')} 年級</p><p>{t.description}</p><p>觀察重點：{t.evidence.join('；')}</p><p>活動參考：{t.assessmentPrompt.replaceAll('{{name}}','學生')}</p><p className="fine">社群整理，未經本平台課綱對應審核。來源：<a href={coverage.sources.find(s=>s.id===t.sourceId)?.url} target="_blank" rel="noreferrer">tw-taxonomy（CC BY 4.0）</a></p><button type="button" onClick={()=>setQuery(t.name)}>以此主題準備資源搜尋</button></article>)}{!coverage?.total&&<p>此範圍尚未整理通用主題，不表示已完整支援。</p>}<div className="button-row"><button disabled={busy||!coverage?.page} onClick={()=>run(()=>load(grade,subject,coverage.page-1))}>主題上一頁</button><span>第 {(coverage?.page||0)+1} 頁</span><button disabled={busy||((coverage?.page||0)+1)*20>=(coverage?.total||0)} onClick={()=>run(()=>load(grade,subject,coverage.page+1))}>主題下一頁</button></div></details>
 <h3>教育大市集官方搜尋</h3><p>申請送出不代表已核准。請在原站「會員中心 → 資料設定 → API應用服務」確認取得金鑰，再填入下方。這與 Gemini 金鑰不同。</p><p><a href="https://market.cloud.edu.tw/member/apiapply.jsp" target="_blank" rel="noreferrer">教育大市集 API 申請與狀態 ↗</a></p>
 <form onSubmit={e=>{e.preventDefault();run(async()=>{await call('saveResourceKey',{key});setKey('');setConfigured(true);setNotice('金鑰已加密儲存於老師電腦，尚未驗證連線。')})}}><label className="field"><span>教育大市集 API Key</span><input type="password" autoComplete="off" value={key} maxLength={512} onChange={e=>setKey(e.target.value)} placeholder={configured?'已儲存；輸入新金鑰可更換':'原站核發後填入'}/></label><div className="button-row"><button disabled={busy||!key.trim()}>加密儲存教育大市集金鑰</button><button type="button" disabled={busy||!configured} onClick={()=>run(async()=>{await call('deleteResourceKey');setConfigured(false);setNotice('已移除教育大市集金鑰。')})}>移除金鑰</button></div></form>
 <form onSubmit={e=>{e.preventDefault();run(()=>search())}}><label className="field"><span>教育資源關鍵字</span><input value={query} maxLength={100} onChange={e=>setQuery(e.target.value)} placeholder="例如：三年級 成語、分數、電路"/></label><button disabled={busy||!configured||!query.trim()}>搜尋官方教學資源</button></form><p className="fine">只傳送此處的關鍵字與頁碼給教育大市集，不會自動附上學生資料。上方年級與科目是本機盤點條件，不會代替外部搜尋結果的逐筆範圍核對。附件須確認授權及內容後，另行拆題並審核。</p>
 {results&&<><p>「{results.query}」第 {results.page}／{results.totalPages} 頁，這些是來源資料，不是新增題目。</p>{results.records.map((r,i)=><article className="panel" key={r.id+'-'+i}><h3>{r.title}</h3><p>授權：{r.license}</p><p>年級：{r.grades.join('、')||'未提供'} · 領域：{r.domains.join('、')||'未提供'}</p><p>{r.description}</p>{r.url&&<a href={r.url} target="_blank" rel="noreferrer">查閱來源 ↗</a>}{r.attachments.map((a,j)=><p key={j}><a href={a.url} target="_blank" rel="noreferrer">附件：{a.name} ↗</a></p>)}</article>)}{!results.records.length&&<p>沒有查到來源，請調整關鍵字。</p>}<div className="button-row"><button disabled={busy||results.page<=1||query!==results.query} onClick={()=>run(()=>search(results.page-1))}>來源上一頁</button><button disabled={busy||results.page>=results.totalPages||query!==results.query} onClick={()=>run(()=>search(results.page+1))}>來源下一頁</button></div></>}
 </>}{notice&&<p role="status">{notice}</p>}{busy&&<p role="status">處理中…</p>}{error&&<p role="alert">{error}</p>}</section>
}
