import React,{useState} from 'react';
export default function CurriculumResources({cloud,onChooseScope,onImported}){
 const [open,setOpen]=useState(false),[coverage,setCoverage]=useState(null),[grade,setGrade]=useState(3),[subject,setSubject]=useState(''),[query,setQuery]=useState(''),[key,setKey]=useState(''),[configured,setConfigured]=useState(false),[results,setResults]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[target,setTarget]=useState(36),[topicQuery,setTopicQuery]=useState(''),[paperMaterial,setPaperMaterial]=useState('選擇題8題，應用題2題'),[paperRounds,setPaperRounds]=useState(3);
 const call=(operation,data={})=>cloud.questionBank({operation,...data});
 async function run(fn){if(busy)return;setBusy(true);setError('');try{await fn()}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function load(g=grade,s=subject,page=0,n=target,q=topicQuery){setCoverage(await call('curriculumCoverage',{filters:{grade:g,subject:s,query:q,page,target:n,material:paperMaterial,rounds:paperRounds}}))}
 async function search(page=1){const result=await call('searchResources',{query,page});setResults({...result,query})}
 return <section className="panel"><h2>108 課綱與教學資源</h2><p>以通用學習內容規劃跨版本教學。先確認各科題庫缺口，再找來源；課綱索引與搜尋結果不計入已審核題數。</p>
 {!open?<button disabled={busy} onClick={()=>run(async()=>{await load();const s=await call('resourceKeyStatus');setConfigured(s.configured);setOpen(true)})}>開啟課綱與資源中心</button>:<>
 <div className="form-grid"><label className="field"><span>課綱年級</span><select disabled={busy} value={grade} onChange={e=>{const g=Number(e.target.value);setGrade(g);run(()=>load(g))}}>{[3,4,5,6,7,8,9].map(g=><option key={g} value={g}>{g<7?'國小'+g:'國中'+(g-6)}年級</option>)}</select></label><label className="field"><span>課綱科目</span><select disabled={busy} value={subject} onChange={e=>{setSubject(e.target.value);run(()=>load(grade,e.target.value))}}><option value="">全部科目</option>{coverage?.matrix.map(r=><option key={r.subject}>{r.subject}</option>)}</select></label></div>
 <form className="form-grid" onSubmit={e=>{e.preventDefault();run(()=>load())}}><label className="field"><span>尋找通用單元</span><input maxLength={100} value={topicQuery} onChange={e=>setTopicQuery(e.target.value)}/></label><label className="field"><span>每單元規劃題量</span><input type="number" min={1} max={200} required value={target} onChange={e=>setTarget(e.target.value===''?'':Number(e.target.value))}/></label><label className="field"><span>每份題型配額</span><input required maxLength={150} value={paperMaterial} onChange={e=>setPaperMaterial(e.target.value)} placeholder="選擇題8題，應用題2題"/></label><label className="field"><span>連續不重題份數</span><input required type="number" min={1} max={6} value={paperRounds} onChange={e=>setPaperRounds(e.target.value===''?'':Number(e.target.value))}/></label><button disabled={busy}>更新覆蓋盤點</button></form><p className="fine">預設 36 題是三次各 10 題加換題餘量的規劃值，可調整；實作型課程應另依任務數規劃，並核對題型與難度。</p><p className="notice">{coverage?.notice}</p><div style={{overflowX:'auto'}}><table style={{minWidth:560}}><thead><tr><th>科目</th><th>已審核題</th><th>待審核題</th><th>未對應單元</th><th>題量達標／供題單元</th><th>隨附已整理／待補／疑義</th></tr></thead><tbody>{coverage?.matrix.filter(r=>!subject||r.subject===subject).map(r=><tr key={r.subject}><td>{r.subject}</td><td>{r.approved}</td><td>{r.pending}</td><td>{r.unmapped}</td><td>{r.outsideScope?'本次未選用':`${r.quantityMet}／${r.demandTopics}`}</td><td>{r.packagedPrepared}／{r.packagedDrafts}／{r.packagedIssues}</td></tr>)}</tbody></table></div>
 <details><summary>查看通用主題與活動參考（{coverage?.total||0} 項）</summary>{coverage?.topics.map(t=><article key={t.id} className="panel"><h3>{t.name}</h3><p>{t.subject} · 建議 {t.grades.join('、')} 年級</p><p>{t.description}</p><p className={'assessment-status '+(t.counts.approved?'reviewed':'pending')}>{t.coverageStatus==='outside-scope'?'本次未選用語種，保留擴充規劃':t.coverageStatus==='cross-unit-competency'?'跨單元能力：隨各單元評量，不重複設題量配額':t.coverageStatus==='needs-language-scope'?'語種／腔調與教材缺口':t.shortage?`已核准 ${t.counts.approved} 題，距規劃量尚缺 ${t.shortage} 題`:'題量達標，仍須核對考點與難度'}</p><p>待審核 {t.counts.pending} 題 · 已核准題型：選擇 {t.counts.byType.choice}、簡答 {t.counts.byType.short}、應用 {t.counts.byType.application}、實作 {t.counts.byType.work}</p><p>本版隨附本單元候選：資料齊備 {t.candidates.ready}、待補教材／資料 {t.candidates.activities}、疑義 {t.candidates.issues}。尚未匯入或核准者不計入上方可用量。</p>{t.supply&&<p className="notice">依「{coverage.supplyPlan.material}」試算：已核准題可連續組 {t.supply.approved.papers}／{coverage.supplyPlan.rounds} 份；含待審與隨附候選的預估上限 {t.supply.potential.papers} 份。{!t.supply.approved.complete&&`下一份尚缺：${Object.entries(t.supply.approved.missingByType).map(([k,n])=>`${({choice:'選擇',short:'簡答',application:'應用',work:'實作'})[k]} ${n} 題`).join('、')}。`}此試算排除相同或高度相似題，未扣除個別班級歷史；候選未核准前不可直接發布。</p>}<p>已核准難度：{Object.entries(t.counts.byDifficulty).map(([key,n])=>`${key} ${n} 題`).join('、')||'尚無'}</p>{t.evidence.length>0&&<p>觀察重點：{t.evidence.join('；')}</p>}<div className="button-row"><button type="button" onClick={()=>onChooseScope?.({grade:grade<7?'國小'+['','','','三','四','五','六'][grade]+'年級':'國中'+['一','二','三'][grade-7]+'年級',subject:t.subject,topicId:t.id})}>查看本單元題庫</button><button type="button" disabled={busy||!t.candidates.ready} onClick={()=>run(async()=>{const r=await call('importCurriculumUnit',{filters:{grade,subject:t.subject},topicId:t.id});setNotice(`本單元已加入 ${r.imported} 題待審核，略過 ${r.skipped} 題既有資料；尚未核准。`);await load();await onImported?.()})}>加入本單元候選題（待審核）</button></div>{t.assessmentPrompt&&<p>活動參考：{t.assessmentPrompt.replaceAll('{{name}}','學生')}</p>}<p className="fine">{t.notice} 來源：<a href={coverage.sources.find(s=>s.id===t.sourceId)?.url} target="_blank" rel="noreferrer">{coverage.sources.find(s=>s.id===t.sourceId)?.publisher||'來源說明'}</a></p><button type="button" onClick={()=>setQuery(t.name)}>以此主題準備資源搜尋</button></article>)}{!coverage?.total&&<p>此範圍尚未整理通用主題，不表示已完整支援。</p>}<div className="button-row"><button disabled={busy||!coverage?.page} onClick={()=>run(()=>load(grade,subject,coverage.page-1))}>主題上一頁</button><span>第 {(coverage?.page||0)+1} 頁</span><button disabled={busy||((coverage?.page||0)+1)*20>=(coverage?.total||0)} onClick={()=>run(()=>load(grade,subject,coverage.page+1))}>主題下一頁</button></div></details>
 <h3>教育大市集官方搜尋</h3><p>申請送出不代表已核准。請在原站「會員中心 → 資料設定 → API應用服務」確認取得金鑰，再填入下方。這與 Gemini 金鑰不同。</p><p><a href="https://market.cloud.edu.tw/member/apiapply.jsp" target="_blank" rel="noreferrer">教育大市集 API 申請與狀態 ↗</a></p>
 <form onSubmit={e=>{e.preventDefault();run(async()=>{await call('saveResourceKey',{key});setKey('');setConfigured(true);setNotice('金鑰已加密儲存於老師電腦，尚未驗證連線。')})}}><label className="field"><span>教育大市集 API Key</span><input type="password" autoComplete="off" value={key} maxLength={512} onChange={e=>setKey(e.target.value)} placeholder={configured?'已儲存；輸入新金鑰可更換':'原站核發後填入'}/></label><div className="button-row"><button disabled={busy||!key.trim()}>加密儲存教育大市集金鑰</button><button type="button" disabled={busy||!configured} onClick={()=>run(async()=>{await call('deleteResourceKey');setConfigured(false);setNotice('已移除教育大市集金鑰。')})}>移除金鑰</button></div></form>
 <form onSubmit={e=>{e.preventDefault();run(()=>search())}}><label className="field"><span>教育資源關鍵字</span><input value={query} maxLength={100} onChange={e=>setQuery(e.target.value)} placeholder="例如：三年級 成語、分數、電路"/></label><button disabled={busy||!configured||!query.trim()}>搜尋官方教學資源</button></form><p className="fine">只傳送此處的關鍵字與頁碼給教育大市集，不會自動附上學生資料。上方年級與科目是本機盤點條件，不會代替外部搜尋結果的逐筆範圍核對。附件須確認授權及內容後，另行拆題並審核。</p>
 {results&&<><p>「{results.query}」第 {results.page}／{results.totalPages} 頁，這些是來源資料，不是新增題目。</p>{results.records.map((r,i)=><article className="panel" key={r.id+'-'+i}><h3>{r.title}</h3><p>授權：{r.license}</p><p>年級：{r.grades.join('、')||'未提供'} · 領域：{r.domains.join('、')||'未提供'}</p><p>{r.description}</p>{r.url&&<a href={r.url} target="_blank" rel="noreferrer">查閱來源 ↗</a>}{r.attachments.map((a,j)=><p key={j}><a href={a.url} target="_blank" rel="noreferrer">附件：{a.name} ↗</a></p>)}</article>)}{!results.records.length&&<p>沒有查到來源，請調整關鍵字。</p>}<div className="button-row"><button disabled={busy||results.page<=1||query!==results.query} onClick={()=>run(()=>search(results.page-1))}>來源上一頁</button><button disabled={busy||results.page>=results.totalPages||query!==results.query} onClick={()=>run(()=>search(results.page+1))}>來源下一頁</button></div></>}
 </>}{notice&&<p role="status">{notice}</p>}{busy&&<p role="status">處理中…</p>}{error&&<p role="alert">{error}</p>}</section>
}
