import React,{useState} from 'react';
export default function DataManagement({cloud,data,activeClass,notify}){
 const [target,setTarget]=useState('class'),[studentId,setStudentId]=useState(''),[preview,setPreview]=useState(null),[password,setPassword]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const students=data.students.filter(s=>s.classId===activeClass?.id),scope=target==='class'?{kind:'class',id:activeClass?.id}:{kind:'student',id:studentId};
 function reset(){setPreview(null);setConfirmed(false);setPassword('');setError('')}
 async function run(fn){if(busy)return;setBusy(true);setError('');try{await fn()}catch(e){setError(e.message)}finally{setBusy(false)}}
 function download(value){const blob=new Blob([JSON.stringify(value,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='學習有爪-教學資料-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 return <section className="panel data-management" key={activeClass?.id}><h2>學生與班級資料管理</h2><p>匯出與刪除需要重新驗證老師密碼。帳號復原及完整加密備份，請到桌面啟動中心「帳號與備份」。</p><fieldset disabled={busy||!activeClass}><label className="field"><span>資料範圍</span><select aria-label="資料管理範圍" value={target} onChange={e=>{setTarget(e.target.value);reset()}}><option value="class">目前班級全部資料</option><option value="student">一位學生</option></select></label>{target==='student'&&<label className="field"><span>學生</span><select aria-label="資料管理學生" value={studentId} onChange={e=>{setStudentId(e.target.value);reset()}}><option value="">請選擇學生</option>{students.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>}<button disabled={!scope.id} onClick={()=>run(async()=>{const result=await cloud.dataAdmin({operation:'preview',scope});setPreview({...result,scope,requestId:crypto.randomUUID()});setConfirmed(false);setPassword('')})}>預覽資料範圍</button></fieldset>
 {preview&&<div className="notice"><strong>{preview.label}</strong><p>{preview.students} 位學生、{preview.submissions} 份作答、{preview.inventory} 件收藏、{preview.exhibits} 件展示。刪除還包括登入、代幣與遊戲紀錄、回饋、AI 分析、房間與私人方案。刪除班級也移除該班任務。</p><p>刪除會清除本程式管理的所有舊備份，避免保留已刪資料。自行匯出的檔案與第三方已收到的內容不會被遠端刪除；共用題庫及教材中的自由文字需另行核對。</p><label className="field"><span>老師目前密碼</span><input aria-label="資料管理老師密碼" type="password" autoComplete="current-password" value={password} disabled={busy} onChange={e=>setPassword(e.target.value)}/></label><div className="button-row"><button disabled={busy||!password} onClick={()=>run(async()=>{download(await cloud.dataAdmin({operation:'export',scope:preview.scope,password}));setPassword('');notify('教學資料已匯出，檔案含學生資料，請妥善保管')})}>匯出教學資料 JSON</button></div><label className="ai-confirm"><input type="checkbox" checked={confirmed} disabled={busy} onChange={e=>setConfirmed(e.target.checked)}/>我已核對範圍並處理需要保存的資料，確認刪除上述資料及管理中的舊備份。</label>{cloud.classOpen&&<p>請先結束課堂，才能刪除資料。</p>}<button disabled={busy||!password||!confirmed||cloud.classOpen} onClick={()=>run(async()=>{const result=await cloud.dataAdmin({operation:'delete',scope:preview.scope,password,confirmed:true,revision:preview.revision,requestId:preview.requestId});setPassword('');if(result.cleanupPending){setError('主要資料已刪除，但舊備份清理未完成。請重啟程式完成清理；自行匯出的副本需自行刪除。');setPreview(null)}else{reset();notify('資料已刪除；管理中的舊備份已清除')}})}>刪除已確認的資料</button></div>}{busy&&<p role="status">正在處理，請勿關閉頁面…</p>}{error&&<p role="alert" className="notice error">{error}</p>}</section>
}
