import {useDesktop} from './desktop';
import {useEffect,useState,useRef} from 'react';
import {initializeApp} from 'firebase/app';
import {getAuth,signInWithEmailAndPassword,createUserWithEmailAndPassword,sendEmailVerification,sendPasswordResetEmail,signInWithCustomToken,onAuthStateChanged,signOut} from 'firebase/auth';
import {getFirestore,doc,onSnapshot} from 'firebase/firestore';
import {getFunctions,httpsCallable} from 'firebase/functions';
import {initializeAppCheck,ReCaptchaV3Provider,getToken} from 'firebase/app-check';
import {uid} from '../functions/domain.mjs';
import {createGrantRetry} from './grant-retry.mjs';
export const desktopMode=import.meta.env.VITE_DESKTOP==='true';
export const configured=desktopMode||!!import.meta.env.VITE_FIREBASE_PROJECT_ID;
let auth,db,functions,appCheck;
const backendUrl=import.meta.env.VITE_BACKEND_URL?.replace(/\/$/,'');
if(configured&&!desktopMode){const app=initializeApp({apiKey:import.meta.env.VITE_FIREBASE_API_KEY,authDomain:import.meta.env.VITE_FIREBASE_AUTH_DOMAIN,projectId:import.meta.env.VITE_FIREBASE_PROJECT_ID,appId:import.meta.env.VITE_FIREBASE_APP_ID});auth=getAuth(app);db=getFirestore(app);functions=getFunctions(app,'asia-east1');if(import.meta.env.VITE_RECAPTCHA_SITE_KEY)appCheck=initializeAppCheck(app,{provider:new ReCaptchaV3Provider(import.meta.env.VITE_RECAPTCHA_SITE_KEY),isTokenAutoRefreshEnabled:true});}
function useCloudFirebase(){const grants=useRef(createGrantRetry());const[user,setUser]=useState(null),[role,setRole]=useState(null),[state,setState]=useState(null),[loading,setLoading]=useState(configured),[error,setError]=useState('');
 useEffect(()=>{if(!configured)return;let stop=()=>{};let generation=0;const unsub=onAuthStateChanged(auth,async u=>{const current=++generation;stop();setUser(u);setState(null);setRole(null);setError('');if(!u){setLoading(false);return}setLoading(true);try{const token=await u.getIdTokenResult();if(current!==generation)return;const r=token.claims.teacher&&token.claims.email_verified?'teacher':token.claims.student?'student':'pending';setRole(r);if(r==='pending'){setLoading(false);return}stop=onSnapshot(doc(db,r==='teacher'?'workspaces':'studentViews',u.uid),snap=>{setState(snap.exists()?snap.data().state:r==='teacher'?{version:1,classes:[],students:[],ledger:[],inventory:[],rooms:{},assignments:[],submissions:[],sessions:[],processed:[]}:null);setLoading(false)},e=>{setError(e.message);setLoading(false)})}catch(e){setError(e.message);setLoading(false)}});return()=>{generation++;unsub();stop()}},[]);
 const call=async(name,data)=>{if(!backendUrl)return (await httpsCallable(functions,name)(data)).data;if(!appCheck)throw new Error('網站驗證尚未設定，請聯絡管理者');const attestation=await getToken(appCheck);const token=auth.currentUser?await auth.currentUser.getIdToken():null;let response;try{response=await fetch(backendUrl+'/'+name,{method:'POST',headers:{'Content-Type':'application/json','X-Firebase-AppCheck':attestation.token,...(token?{Authorization:'Bearer '+token}:{})},body:JSON.stringify(data),signal:AbortSignal.timeout(90000)})}catch{throw new Error('免費主機可能正在喚醒，請稍候約一分鐘再試')}let result;try{result=await response.json()}catch{throw new Error('服務正在啟動，請稍後重試')}if(!response.ok||result.error)throw Object.assign(new Error(result.error?.message||'服務暫時無法完成'),{status:response.status});return result.data};
 return{user,role,state,loading,error,login:(email,password)=>signInWithEmailAndPassword(auth,email.trim(),password),registerTeacher:async(email,password)=>{const result=await createUserWithEmailAndPassword(auth,email.trim(),password);await sendEmailVerification(result.user)},resetPassword:email=>sendPasswordResetEmail(auth,email.trim()),studentAccess:async data=>{const result=await call('studentAccess',data);await signInWithCustomToken(auth,result.token)},logout:()=>signOut(auth),action:action=>grants.current(user?.uid,action,data=>call('classroomAction',data)),join:(code,name)=>call('joinClass',{code,name}),saveKey:key=>call('saveTeacherKey',{key}),deleteKey:()=>call('deleteTeacherKey',{}),testKey:()=>call('testTeacherKey',{}),generate:data=>call('teacherAI',{...data,requestId:uid()}),keyStatus:()=>call('teacherKeyStatus',{})};
}

export const useFirebase=desktopMode?useDesktop:useCloudFirebase;
