import React,{useEffect,useRef,useState} from 'react';
export function ResourceLinks({links=[]}){return links.length>0&&<section className="open-data-links"><h3>教學與補強資源</h3>{links.map(r=><article key={r.id}><a href={r.url} target="_blank" rel="noopener noreferrer">{r.title} ↗</a><small>{r.source||'愛學網'} {r.duration&&'· '+r.duration} · 開啟外部網站</small></article>)}<p className="fine">開啟教材不代表完成任務；完成老師指定的練習並經批閱後才獲得獎勵。</p></section>}
export function ResourcePicker({cloud,grade,subject,initialQuery='',requirements='',intent=null,value=[],onChange}){
 const[query,setQuery]=useState(initialQuery),[result,setResult]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');const version=useRef(0);
 useEffect(()=>{version.current++;setQuery(initialQuery);setResult(null);setError('');setBusy(false)},[grade,subject,initialQuery,requirements]);useEffect(()=>()=>{version.current++},[]);
 if(!cloud.desktop)return null;
 async function search(useAI){const v=++version.current;setBusy(true);setError('');try{const r=await cloud.questionBank({operation:'learningResources',filters:{grade,subject,unit:initialQuery||query,query,material:requirements,useAI,queries:query===initialQuery?intent?.queries:undefined}});if(v===version.current)setResult(r)}catch(e){if(v===version.current)setError(e.message)}finally{if(v===version.current)setBusy(false)}}
 return <details className="open-data-panel"><summary>相關教學／補強教材（已選 {value.length}/3）</summary><p>沿用本次學習目標尋找教材，找不到時不影響題目發布。教材清單不代表已讀取影片全文，附給學生前請預覽。</p><label className="field"><span>教材學習概念</span><input maxLength={100} value={query} onChange={e=>{setQuery(e.target.value);setResult(null);version.current++;setBusy(false)}}/></label><div className="button-row"><button type="button" disabled={busy||!query.trim()} onClick={()=>search(false)}>{busy?'搜尋中…':'搜尋相關教材'}</button><button type="button" disabled={busy||!query.trim()} onClick={()=>search(true)}>AI 理解目標並找教材</button></div>{intent?.summary&&<p className="fine">出題理解：{intent.summary}</p>}<ResourceLinks links={value}/>{value.map(r=><button type="button" data-dirty="true" key={r.id} onClick={()=>onChange(value.filter(x=>x.id!==r.id))}>移除：{r.title}</button>)}{error&&<p role="alert">{error}</p>}{result&&<><p role="status">{result.total?`找到 ${result.total} 筆候選，顯示前 ${result.records.length} 筆。`:'沒有符合範圍的教材；可修改關鍵字，題目仍能單獨發布。'}</p>{result.intent&&<p>{result.intent.summary}</p>}{result.records.map(r=><article className="open-data-result" key={r.id}><a href={r.url} target="_blank" rel="noopener noreferrer">{r.title} ↗</a><p>{r.reason}</p><small>{r.duration} · {r.subjects.join('、')} · 來源授權：{r.license}</small><p>{r.description.slice(0,240)}</p><button type="button" data-dirty="true" disabled={value.length>=3||value.some(x=>x.id===r.id)} onClick={()=>onChange([...value,r])}>{value.some(x=>x.id===r.id)?'已選取':'附上此教材'}</button></article>)}</>}</details>
}
export function SchoolContext({cloud,activeClass,act}){
 const[saved,setSaved]=useState(activeClass.schoolContext||{mode:'unspecified'}),[mode,setMode]=useState(saved.mode),[stage,setStage]=useState('primary'),[query,setQuery]=useState(''),[records,setRecords]=useState([]),[selected,setSelected]=useState(saved.id||''),[busy,setBusy]=useState(false),[error,setError]=useState('');const version=useRef(0);useEffect(()=>()=>{version.current++},[]);
 return <details className="panel"><summary>教學背景（選填，不影響出題）</summary><p>可選學校、跨校線上班或不指定，不影響學生登入或題庫範圍。</p><label className="field">班級教學情境<select value={mode} onChange={e=>setMode(e.target.value)}><option value="unspecified">不指定學校</option><option value="mixed">跨校線上班</option><option value="school">單一學校</option></select></label>{mode==='school'&&<><div className="form-grid"><label className="field">查詢學制<select value={stage} onChange={e=>{setStage(e.target.value);setRecords([]);setSelected('');version.current++}}><option value="primary">國小</option><option value="junior">國中</option></select></label><label className="field">查詢校名<input value={query} maxLength={80} onChange={e=>{setQuery(e.target.value);setRecords([]);setSelected('');version.current++}}/></label></div><button type="button" disabled={busy} onClick={async()=>{const v=++version.current;setBusy(true);setError('');try{const r=await cloud.questionBank({operation:'schoolSearch',filters:{stage,query,year:115}});if(v===version.current)setRecords(r.records)}catch(e){setError(e.message)}finally{setBusy(false)}}}>查詢115學年度名錄</button><label className="field">選擇學校<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">請選擇</option>{saved.id&&!records.some(r=>r.id===saved.id)&&<option value={saved.id}>{saved.county} · {saved.name}</option>}{records.map(r=><option key={r.id} value={r.id}>{r.county} · {r.name}</option>)}</select></label><p className="fine">最多顯示40筆，請輸入校名縮小範圍。找不到可選「不指定學校」。學校背景為教師自行選擇，不代表身分已驗證。</p></>}<button type="button" disabled={busy||(mode==='school'&&!selected)} onClick={async()=>{setBusy(true);const result=await act({type:'schoolContext',classId:activeClass.id,schoolContext:{mode,id:selected}},{message:'已保存教學背景'});if(result)setSaved({mode,id:selected,...records.find(r=>r.id===selected)});setBusy(false)}}>保存教學背景</button>{error&&<p role="alert">{error}</p>}</details>
}
export function OpenDataStatus({cloud}){
 const[info,setInfo]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');const alive=useRef(true);useEffect(()=>{alive.current=true;cloud.questionBank({operation:'openDataInfo'}).then(r=>{if(alive.current)setInfo(r)}).catch(e=>{if(alive.current)setError(e.message)});return()=>{alive.current=false}},[]);
 return <section className="panel"><h2>官方開放資料</h2><p>題庫原題、可引用知識與教材連結分開管理。只有符合教學目標的內容才參與檢索；學校名錄僅用於選填背景。</p>{info?.teaching&&<div><p>官方原題參考 {info.teaching.counts.question} 筆 · 知識內容 {info.teaching.counts.knowledge} 筆 · 資訊素養教材連結 {info.teaching.counts.link} 筆</p><p className="fine">以上不是已核准題數。官方內容延伸題需確認一次，之後可從題庫重用。新增教學內容隨程式版本更新；下方更新按鈕只更新愛學網與名錄。</p>{info.teaching.sources.map(s=><p key={s.id}><a href={s.url} target="_blank" rel="noreferrer">{s.title}</a> · {s.checkedDate} · 版本 {s.sha256.slice(0,12)}</p>)}<p className="fine">氣象 PDF 尚待時效與圖表內容審定；古蹟資料下載未完成，本版未作為出題來源。</p></div>}{info?.sources.map(s=><p key={s.id}><a href={s.url} target="_blank" rel="noreferrer">{({'6087':'國民小學名錄','6088':'國民中學名錄','6318':'國家教育研究院愛學網'})[s.id]} ↗</a> · 查核日期 {s.checkedDate}<small className="fine"> · 來源版本 {s.sha256.slice(0,12)}</small></p>)}<button type="button" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{const r=await cloud.questionBank({operation:'refreshOpenData'});if(alive.current)setInfo(r)}catch(e){if(alive.current)setError('更新未完成，保留原資料。'+e.message)}finally{if(alive.current)setBusy(false)}}}>{busy?'正在下載並驗證三份官方資料…':'更新愛學網與名錄快照'}</button>{error&&<p role="alert">{error}</p>}<p className="fine">目前國小來源固定為115學年度，跨年度來源變更由版本更新調整。資料更新不會改寫已發布題目。{info&&`愛學網快照 ${info.resourceCount} 筆，並非可用題數。`}</p></section>
}
