import {useUnsavedChanges} from './unsaved-changes.mjs';
import {OpenDataStatus} from './OpenData.jsx';
import CurriculumResources from './CurriculumResources.jsx';
import WebQuestionLibrary from './WebQuestionLibrary.jsx';
import {inspectMathQuestion,mathReviewContent} from '../functions/math-verification.mjs';
import React,{useEffect,useState,useRef} from 'react';
import {GRADES,SUBJECTS} from '../functions/domain.mjs';
import {hasQuestionReview,questionReviewContent} from '../functions/question-review.mjs';
function TeachingEvidence({cloud,refs}){
 const [rows,setRows]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);const alive=useRef(true);useEffect(()=>{alive.current=true;return()=>{alive.current=false}},[]);
 return <details><summary>本題核准時的官方內容來源</summary>{refs.map(r=><p key={r.id}><a href={r.url} target="_blank" rel="noreferrer">{r.title} · {r.source}</a></p>)}<button type="button" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{const result=await Promise.all(refs.map(r=>cloud.questionBank({operation:'teachingSource',id:r.id})));if(alive.current)setRows(result.map(r=>r.record))}catch(e){if(alive.current)setError(e.message)}finally{if(alive.current)setBusy(false)}}}>讀取核准時的來源快照</button>{error&&<p role="alert">{error}</p>}{rows?.map(r=><p key={r.id} style={{whiteSpace:'pre-wrap'}}>{r.title} · {r.locator}\n{r.body}</p>)}</details>
}
export function QuestionReview({question,scope,index,onChange,cloud,onReviewBusy}){
 const alive=useRef(true),request=useRef(null);const [reviewSource,setReviewSource]=useState(null),[confirmedHere,setConfirmedHere]=useState(false),[confirming,setConfirming]=useState(false),[confirmError,setConfirmError]=useState('');
 useEffect(()=>{alive.current=true;return()=>{alive.current=false}},[]);
 const [references,setReferences]=useState(null),[referenceError,setReferenceError]=useState(''),[loading,setLoading]=useState(false);
 const shownSource=reviewSource||question.provenance;
 useEffect(()=>{setReferences(null);setReferenceError('')},[JSON.stringify(shownSource?.sources||[])]);
 if(!question.provenance)return null;
 const mathCheck=inspectMathQuestion(question,scope.subject);
 const kind=shownSource.kind,approved=hasQuestionReview(question,scope)&&(!cloud?.questionBank||question.provenance.kind==='bank');
 async function confirm(checked){
  if(!checked){onChange({...question,teacherReview:undefined});return}
  if(confirming)return;setConfirmError('');setConfirming(true);onReviewBusy?.(true);
  try{const result=inspectMathQuestion(question,scope.subject);if(result.status==='invalid')throw Error('請先修正數學檢查發現的問題，再確認本題。');const q=result.status==='verified'?result.question:question;
   if(cloud?.questionBank){
    const teachingScope=Object.fromEntries(['grade','subject','unit','textbook','semester','difficulty'].map(k=>[k,scope[k]||'']));const hash=questionReviewContent(q,teachingScope);
    if(request.current?.hash!==hash)request.current={hash,id:crypto.randomUUID()};
    const response=await cloud.questionBank({operation:'confirmSelection',question:q,scope:teachingScope,confirmed:true,requestId:request.current.id});
    if(alive.current){setReviewSource(current=>current||question.provenance);setConfirmedHere(true);onChange(response.question)}
   }else {setReviewSource(current=>current||question.provenance);setConfirmedHere(true);onChange({...q,teacherReview:questionReviewContent(q,scope),...(result.status!=='not-applicable'?{mathReview:mathReviewContent(q,scope.subject)}:{})})};
  }catch(e){if(alive.current)setConfirmError(e.message)}finally{if(alive.current)setConfirming(false);onReviewBusy?.(false)}
 }
 return <div className={'question-origin '+(approved?'approved':'pending')}><strong>{kind==='grounded'?'官方教學內容衍生題':kind==='data'?'歷史資料模板（非 AI 生成）':kind==='rag'?'AI 延伸題':kind==='bank'?'題庫原題':'AI 生成題'} · {approved?'教師已確認':'待教師確認'}</strong>
 <p>{kind==='grounded'?'新題以官方內容為參考，經引用與 AI 檢查，尚須確認適齡性、題意及答案；AI 檢查不等於教師核准。':kind==='rag'?'此題在相同學習範圍內延伸；來源提供範圍與難度參考，新增考點不一定出現在原題。新題答案與詳解仍需確認。':'修改題目或教學範圍後，需要重新核對。'}</p>
 {!!shownSource.sources?.length&&<details><summary>查看參考來源（{shownSource.sources.length}）</summary><ul>{shownSource.sources.map(s=><li key={s.id}><b>{s.title}</b> · {s.source} · 第 {s.revision} 版{s.url&&<a href={s.url} target="_blank" rel="noreferrer"> 原始來源 ↗</a>}<small>題庫 ID：{s.id}</small></li>)}</ul>{cloud?.questionBank&&!['data','grounded'].includes(kind)&&<button type="button" disabled={loading} onClick={async()=>{setLoading(true);setReferenceError('');try{setReferences(await Promise.all(shownSource.sources.map(async s=>{const {record,snapshot}=await cloud.questionBank({operation:'get',id:s.id,revision:s.revision});return {record: snapshot||record,current:record,expected:s.revision}})))}catch(e){setReferenceError(e.message)}finally{setLoading(false)}}}>{loading?'載入中…':'查看題庫原題與答案'}</button>}{cloud?.questionBank&&kind==='grounded'&&<button type="button" disabled={loading} onClick={async()=>{setLoading(true);setReferenceError('');try{setReferences(await Promise.all(shownSource.sources.map(async s=>{const {record}=await cloud.questionBank({operation:'teachingSource',id:s.id});return {record,current:{revision:1},expected:1}})))}catch(e){setReferenceError(e.message)}finally{setLoading(false)}}}>查看實際引用的官方內容</button>}{referenceError&&<p role="alert">{referenceError}</p>}{references?.map(({record:r,current,expected})=><div className="bank-reference" key={r.id}>{(current.revision!==expected||current.status==='retired')&&<b>此來源已更新或停用，請重新組卷。</b>}{r.originKind==='grounded'&&r.derivedFrom?.length>0&&<TeachingEvidence cloud={cloud} refs={r.derivedFrom}/>}<p>{r.locator}</p>{r.body&&<p style={{whiteSpace:'pre-wrap'}}>{r.body}</p>}<p>{r.question?.prompt}</p>{r.question?.options?.map((o,i)=><p key={i}>{'ABCD'[i]}. {o}</p>)}{current.status==='pending'&&<p>此來源於載入時仍待審核；可重新查看來源取得最新狀態。</p>}{r.question?<><p><b>原題答案：</b>{r.question.answer}</p><p><b>原題詳解：</b>{r.question.explanation||'未提供'}</p></>:<p className="fine">{r.kind==='question'?'官方原題未提供詳解，新題詳解需另行核對。':'以上為官方知識內容，並非已核准題目。'}</p>}</div>)}</details>}
 {(!approved||confirmedHere)&&<label><input type="checkbox" disabled={confirming||approved||mathCheck.status==='invalid'} aria-label={`確認第${index+1}題正確性`} checked={approved} onChange={e=>confirm(e.target.checked)}/>{mathCheck.status==='needs-review'?'我已確認本題符合範圍、條件足夠、列式符合題意、答案與單位正確、詳解每一步合理，並有權用於教學與 AI 參考。':'我已確認本題符合範圍，題意、答案、單位與詳解正確，並有權用於教學與 AI 參考。'}{cloud?.questionBank?'確認後自動存入已核准題庫，不必另外按存入。下次使用相同題目不必重複確認。':''}</label>}
 {confirming&&<p role="status">正在同步核准本題…</p>}{confirmError&&<p role="alert">{confirmError}</p>}
 {cloud?.questionBank&&approved&&<p className="fine">本題沿用題庫核准，不必再次勾選。修改內容或適用範圍才需要重新確認。</p>}</div>
}
const blank=()=>({grade:GRADES[0],subject:'數學',unit:'',textbook:'',semester:'',difficulty:'一般',tags:[],source:'教師自編',url:'',rights:'原創題目，由教師提供作教學使用。',question:{type:'short',prompt:'',answer:'',explanation:''}});
const template={format:'learning-claw-question-bank-v1',records:[{...blank(),unit:'整數加法',tags:['加法','整數'],source:'學習有爪自編格式範例',rights:'本格式範例為專案自編，可供教學使用；匯入後仍須教師審核。',question:{type:'choice',prompt:'計算 23 + 14 的結果為何？',options:['27','37','47','36'],answer:'B',explanation:'個位 3+4=7，十位 2+1=3，所以是 37。'}}]};
function download(name,data){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function Field({label,children}){return <label className="field"><span>{label}</span>{children}</label>}
export default function QuestionBank({cloud}){
 const [result,setResult]=useState({records:[],counts:{},total:0,page:0}),[filters,setFilters]=useState({}),[editor,setEditor]=useState(null),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[json,setJson]=useState(''),[topics,setTopics]=useState([]);
 const saveRequest=useRef(null);useUnsavedChanges(!!editor?._dirty);
 async function refresh(f=filters){const data=await cloud.questionBank({operation:'list',filters:f});setResult(data)}
 useEffect(()=>{if(!cloud.questionBank)return;let stale=false;cloud.questionBank({operation:'list',filters}).then(r=>{if(!stale)setResult(r)}).catch(e=>{if(!stale)setError(e.message)});return()=>{stale=true}},[filters,cloud.questionBank?true:false]);
 async function run(fn){if(busy)return;setBusy(true);setError('');setMessage('');try{await fn()}catch(e){setError(e.message)}finally{setBusy(false)}}
 useEffect(()=>{if(!editor||!cloud.questionBank){setTopics([]);return}let stale=false;cloud.questionBank({operation:'curriculumTopics',filters:{grade:GRADES.indexOf(editor.grade)+3,subject:editor.subject}}).then(r=>{if(!stale)setTopics(r.topics)}).catch(()=>{if(!stale)setTopics([])});return()=>{stale=true}},[editor?.grade,editor?.subject]);
 function change(key,value){setConfirmed(false);setEditor(e=>({...e,[key]:value,...(['grade','subject'].includes(key)?{curriculumTopicIds:[]}:{}),_dirty:true}))}
 function qchange(key,value){change('question',{...editor.question,[key]:value})}
 const open=r=>{if(editor?._dirty&&!window.confirm('題庫內容尚未保存，確定放棄修改？'))return;setEditor(structuredClone(r));setConfirmed(false);setMessage('');setError('')};
 if(!cloud.questionBank)return <div className="panel"><h1>RAG 教師題庫</h1><p>請使用 Mac／Windows 圖形教師程式開啟此功能。題庫儲存在老師電腦，本頁不會把示範資料當成正式題庫。</p></div>;
 return <><div className="page-title"><div><div className="eyebrow">QUESTION LIBRARY / 教師備課本</div><h1>教師題庫</h1><p>已核准題供快速組卷重複使用；新題確認一次後，加入可用題庫。</p></div><button className="primary" onClick={()=>open(blank())} disabled={busy}>＋ 新增題目</button></div>
 <div className="bank-counts"><span>已審核 <b>{result.counts.approved||0}</b></span><span>待審核 <b>{result.counts.pending||0}</b></span><span>已停用 <b>{result.counts.retired||0}</b></span></div>
 <div className="notice">日常快速組卷只使用已核准題；待審核題留在「開發新題」流程。新題在出題畫面確認後同步核准，下次原題可直接使用，不必重新勾選。修改內容或範圍後重新確認；題庫隨教室資料一起備份。</div>
 {error&&<p className="notice error" role="alert">{error}</p>}{message&&<p className="notice" role="status">{message}</p>}
 <details className="panel bank-maintenance"><summary>題庫來源、課綱盤點與匯入工具</summary> {cloud.desktop&&<OpenDataStatus cloud={cloud}/>}
 <CurriculumResources cloud={cloud} onImported={refresh} onChooseScope={scope=>{setFilters({...scope,page:0});setTimeout(()=>document.querySelector('.bank-filters')?.scrollIntoView({block:'start',behavior:'smooth'}),0)}}/>
 <WebQuestionLibrary cloud={cloud} onImported={refresh} onChoose={r=>{open(r);setMessage('已選取網路題目，請在下方編輯區核對年級、單元、答案與詳解，再儲存及審核。');setTimeout(()=>document.querySelector('.bank-editor')?.scrollIntoView({block:'start',behavior:'smooth'}),0)}}/>
 <details className="panel bank-import"><summary>匯入／匯出題庫（JSON）</summary><p>每次最多 100 題、檔案小於 900 KB。所有匯入題目重新列為待審核；相同範圍的重複題會略過。這一版不直接解析 PDF、圖片或 Word。</p><div className="button-row"><button onClick={()=>download('題庫格式範例.json',template)}>下載格式範例</button><button onClick={()=>download('題庫本頁匯出.json',{format:template.format,records:result.records})}>匯出目前這一頁</button><label>選擇 JSON 檔案 <input type="file" accept=".json,application/json" onChange={e=>run(async()=>{const file=e.target.files?.[0];if(!file)return;if(file.size>900000)throw Error('檔案超過 900 KB，請分批匯入');setJson(await file.text())})}/></label></div><Field label="題庫 JSON"><textarea rows={6} value={json} onChange={e=>setJson(e.target.value)} placeholder="貼上格式範例中的 records 資料"/></Field><button disabled={busy||!json.trim()} onClick={()=>run(async()=>{if(new Blob([json]).size>900000)throw Error('內容太大，請分批匯入');const parsed=JSON.parse(json);const data=await cloud.questionBank({operation:'import',records:Array.isArray(parsed)?parsed:parsed.records});setMessage(`已匯入 ${data.imported} 題（待審核），略過 ${data.skipped} 題重複內容。`);setJson('');await refresh()})}>匯入為待審核題目</button></details>
</details>
 {filters.topicId&&<p className="notice">正在查看指定單元題庫。<button onClick={()=>setFilters({...filters,topicId:undefined,page:0})}>清除單元篩選</button></p>}<div className="form-grid bank-filters"><Field label="搜尋單元／題目／標籤"><input maxLength={100} value={filters.query||''} onChange={e=>setFilters({...filters,query:e.target.value,page:0})} placeholder="例如：整數加法、成語"/></Field><Field label="篩選科目"><input maxLength={30} value={filters.subject||''} onChange={e=>setFilters({...filters,subject:e.target.value,topicId:undefined,page:0})} placeholder="完整科目名稱，不填表示全部"/></Field><Field label="篩選年級"><select value={filters.grade||''} onChange={e=>setFilters({...filters,grade:e.target.value,topicId:undefined,page:0})}><option value="">全部年級</option>{GRADES.map(g=><option key={g}>{g}</option>)}</select></Field><Field label="篩選狀態"><select value={filters.status||''} onChange={e=>setFilters({...filters,status:e.target.value,page:0})}><option value="">全部狀態</option><option value="approved">已審核</option><option value="pending">待審核</option><option value="retired">已停用</option></select></Field></div>
 {editor&&<form className="panel bank-editor" onSubmit={e=>{e.preventDefault();run(async()=>{const approve=e.nativeEvent.submitter?.value==='approve';const { _dirty,...input}=editor;const signature=JSON.stringify(input);if(saveRequest.current?.signature!==signature)saveRequest.current={signature,id:crypto.randomUUID()};const {record}=await cloud.questionBank(approve?{operation:'saveReviewed',record:input,confirmed,requestId:saveRequest.current.id}:{operation:'save',record:input});setEditor(record);setConfirmed(false);setMessage(approve?'已保存並加入可用題庫，下次組卷不必重複確認。':'草稿已保存，尚未核准。');await refresh()})}}><fieldset disabled={busy}><div className="section-head"><h2>{editor.id?'編輯／審核題目':'新增題庫題目'}</h2><button type="button" onClick={()=>{if(!editor?._dirty||window.confirm('題庫內容尚未保存，確定放棄修改？'))setEditor(null)}}>關閉編輯</button></div><div className="form-grid"><Field label="年級"><select required aria-label="年級" value={editor.grade} onChange={e=>change('grade',e.target.value)}><option value="" disabled>請確認題目適用年級</option>{GRADES.map(g=><option key={g}>{g}</option>)}</select></Field><Field label="科目"><input required maxLength={30} list="bank-subjects" value={editor.subject} onChange={e=>change('subject',e.target.value)}/><datalist id="bank-subjects">{SUBJECTS.map(s=><option key={s}>{s}</option>)}</datalist></Field><Field label="對應通用單元（供覆蓋盤點）"><select value={editor.curriculumTopicIds?.[0]||''} onChange={e=>change('curriculumTopicIds',e.target.value?[e.target.value]:[])}><option value="">尚未對應（不計入單元完整度）</option>{topics.filter(t=>t.status!=='needs-language-scope').map(t=><option value={t.id} key={t.id}>{t.name}</option>)}</select></Field><p className="fine">選擇與本題實際考點相符的單元。儲存及審核後才計入可用題數；年級／科目改變時會清除對應。</p><Field label="單元"><input required maxLength={100} value={editor.unit} onChange={e=>change('unit',e.target.value)}/></Field><Field label="教材版本（選填）"><input maxLength={50} value={editor.textbook} onChange={e=>change('textbook',e.target.value)} placeholder="例如：自編、康軒、翰林"/></Field><Field label="學期（選填）"><select value={editor.semester} onChange={e=>change('semester',e.target.value)}><option value="">不指定</option><option>上學期</option><option>下學期</option></select></Field><Field label="難度"><select value={editor.difficulty} onChange={e=>change('difficulty',e.target.value)}><option>基礎</option><option>一般</option><option>進階</option></select></Field></div><Field label="知識標籤（以逗號分隔，最多 15 個）"><input maxLength={500} value={editor._tagText??(editor.tags||[]).join(',')} onChange={e=>{setConfirmed(false);setEditor({...editor,_dirty:true,_tagText:e.target.value,tags:e.target.value.split(/[,，]/).map(s=>s.trim()).filter(Boolean)})}}/></Field>
 <Field label="題型"><select value={editor.question.type} onChange={e=>change('question',{...editor.question,type:e.target.value,...(e.target.value==='choice'?{options:['','','',''],answer:'A'}:{options:undefined,answer:''})})}><option value="choice">選擇題</option><option value="short">簡答題</option><option value="work">作品／實作說明</option></select></Field><Field label="題目"><textarea required maxLength={2000} value={editor.question.prompt} onChange={e=>qchange('prompt',e.target.value)}/></Field>
 {editor.question.type==='choice'&&editor.question.options.map((v,i)=><Field key={i} label={`選項 ${'ABCD'[i]}`}><input required maxLength={500} value={v} onChange={e=>qchange('options',editor.question.options.map((x,j)=>j===i?e.target.value:x))}/></Field>)}<Field label="標準答案／評分規準">{editor.question.type==='choice'?<select value={editor.question.answer} onChange={e=>qchange('answer',e.target.value)}>{['A','B','C','D'].map(x=><option key={x}>{x}</option>)}</select>:<textarea required maxLength={2000} value={editor.question.answer} onChange={e=>qchange('answer',e.target.value)}/>}</Field>{editor.question.type!=='choice'&&<Field label="答案單位（選填）"><input maxLength={40} value={editor.question.answerUnit||''} onChange={e=>qchange('answerUnit',e.target.value)}/></Field>}<Field label="詳解"><textarea required maxLength={3000} value={editor.question.explanation} onChange={e=>qchange('explanation',e.target.value)}/></Field>
 <Field label="來源名稱"><input required maxLength={200} value={editor.source} onChange={e=>change('source',e.target.value)}/></Field><Field label="來源網址（選填）"><input type="url" maxLength={500} value={editor.url} onChange={e=>change('url',e.target.value)}/></Field><Field label="使用權利／授權說明"><textarea required maxLength={300} value={editor.rights} onChange={e=>change('rights',e.target.value)}/></Field><div className="question-origin"><label><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>我已核對題意、答案、詳解、適用範圍及使用權利。</label><div className="button-row"><button type="submit" value="draft">保存草稿</button><button type="submit" value="approve" className="primary" disabled={!confirmed}>確認並加入可用題庫</button></div></div></fieldset></form>}
 <div className="assignment-grid">{result.records.map(r=><article className="panel assignment" key={r.id}><div className="section-head"><span className="badge">{r.subject}</span><span className={'assessment-status '+(r.status==='approved'?'reviewed':r.status==='pending'?'pending':'draft')}>{r.status==='approved'?'已審核':r.status==='pending'?'待審核':'已停用'}</span></div><h3>{r.unit}</h3><p>{r.grade} · {r.textbook||'未指定版本'} · {r.difficulty}</p><p className="bank-prompt">{r.question.prompt}</p><small>{r.source} · 第 {r.revision} 版</small><div className="button-row"><button onClick={()=>open(r)}>查看／編輯／審核</button>{r.status!=='retired'&&<button disabled={busy} onClick={()=>run(async()=>{await cloud.questionBank({operation:'retire',id:r.id,revision:r.revision});if(editor?.id===r.id)setEditor(null);await refresh();setMessage('已停用，後續不再檢索此題。')})}>停用</button>}</div></article>)}</div>
 {!result.records.length&&<div className="empty"><b>尚無符合條件的題目</b><p>新增或匯入待審核題庫後，即可到「教學與出題」挑選本次題目，再逐題確認並同步核准。</p></div>}<div className="button-row bank-pages"><button disabled={!result.page||busy} onClick={()=>setFilters({...filters,page:result.page-1})}>上一頁</button><span>共 {result.total} 題 · 第 {result.page+1} 頁</span><button disabled={(result.page+1)*50>=result.total||busy} onClick={()=>setFilters({...filters,page:result.page+1})}>下一頁</button></div></>;
}
