import {roomSize,placementProblem,wallPlacement,freeFloorPlacement} from '../functions/room-space.mjs';
import {FURNITURE,FURNITURE_SERIES} from '../functions/furniture.mjs';
import React,{useState} from 'react';import{DECORATIONS,kitFor,DECOR_IDEAS}from'../functions/room-decorations.mjs';import{FESTIVALS,uid}from'../functions/domain.mjs';
export default function RoomDecorations({student,activeClass,room,selected,onSelect,onChange,onClaim,busy,furniture=false}){
 const [filter,setFilter]=useState('all'),[surface,setSurface]=useState('all'),[notice,setNotice]=useState('');
 const catalog=furniture?FURNITURE:DECORATIONS;const owned=[...new Set([...(furniture?FURNITURE.map(f=>f.id):student.decorationKinds||[]),...(room.decorations||[]).map(d=>d.kind)])],kit=!furniture&&activeClass.eventActive?kitFor(activeClass.festival):[],items=room.decorations||[];
 const shown=catalog.filter(d=>owned.includes(d.id)&&(filter==='all'||(furniture?d.series===filter:d.festival===filter))&&(surface==='all'||d.surface===surface)),ideas=DECOR_IDEAS[filter==='all'?activeClass.festival:filter]||[];
 return <div className="room-decoration-tools"><h3>{furniture?'免費家具工作坊':'我的節慶物件'}</h3><p className="fine">{furniture?'家具免費使用，不用領取或花代幣。':'領取不扣代幣、不改房間。'}選物件加入後，可點場景移動、調整大小與角度，在預覽下方按「確認擺放並保存」。每種最多 8 件，全房最多 32 件。</p>{kit.length>0&&<button className="primary" disabled={busy||kit.every(k=>owned.includes(k))} onClick={onClaim}>{kit.every(k=>owned.includes(k))?'本期物件已領取':`免費領取${FESTIVALS[activeClass.festival].short}物件`}</button>}{kit.length>0&&<p className="fine">本期 {kit.length} 款，尚未領取 {kit.filter(k=>!owned.includes(k)).length} 款；已領過舊版物件也可補領新增款式。</p>}{!furniture&&!kit.length&&<p>目前沒有開放領取；已領取物件仍可自由使用。</p>}{!furniture&&<details className="decor-ideas"><summary>找一點佈置靈感</summary>{ideas.map(i=><div key={i.title}><b>{i.title}</b><p>{i.text}</p></div>)}<p className="fine">只是搭配提示，不會自動放進房間。你也可以跨節慶混搭。</p></details>}<div className="decor-filters">{furniture&&<label>家具系列<select aria-label="家具系列" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">全部系列</option>{Object.entries(FURNITURE_SERIES).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>}{!furniture&&<label>節慶<select aria-label="物件節慶" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">全部收藏</option>{Object.entries(FESTIVALS).filter(([id])=>id!=='none').map(([id,f])=><option key={id} value={id}>{f.short}</option>)}</select></label>}<label>種類<select aria-label="物件種類" value={surface} onChange={e=>setSurface(e.target.value)}><option value="all">全部種類</option><option value="wall">牆飾與吊飾</option><option value="floor">擺件與盆景</option></select></label></div><p className="fine">{shown.length} 款可用{furniture?' · 可重複擺放':` · 已領取 ${owned.filter(k=>DECORATIONS.some(d=>d.id===k)).length} 款`}</p>{notice&&<p role="status">{notice}</p>}<div className="decor-catalog">{shown.map(d=><button key={d.id} aria-label={`加入${d.name}`} disabled={items.length>=32||items.filter(x=>x.kind===d.id).length>=8} onClick={()=>{let item={id:uid(),kind:d.id,x:0,y:.07,z:.6,rotation:0,scale:1,variant:'classic'};if(d.surface==='wall')item={...item,...wallPlacement(room,'back',0,1.8)};else if(d.solid){const free=freeFloorPlacement(room,item);if(!free){setNotice('暫無足夠地面空間，請先移動或收回家具。');return}item=free;}setNotice('');onChange([...items,item]);onSelect(item.id)}}><img src={`/decorations/${d.id}.png`} alt="" loading="lazy"/><b>{d.name}</b><small>{d.surface==='wall'?'牆面':'地板／展示台'} · 已放 {items.filter(x=>x.kind===d.id).length}/8</small></button>)}</div>{!owned.length&&<p>老師開放活動後，先領取物件再開始佈置。</p>}{owned.length>0&&!shown.length&&<p>這個篩選沒有物件，試試其他節慶或種類。</p>}<h4>房間裡的物件 · {items.length}/32</h4><div className="decor-placed">{items.map((d,i)=><button key={d.id} aria-pressed={selected===d.id} onClick={()=>onSelect(selected===d.id?null:d.id)}>{[...DECORATIONS,...FURNITURE].find(x=>x.id===d.kind)?.name} #{i+1}</button>)}</div><p className="fine">收回不會失去物件。已領取的不同節慶物件可以混搭，活動結束後仍保留。</p></div>
}
