import React,{useState} from 'react';
import {SUBJECTS} from '../functions/domain.mjs';
export default function WebQuestionLibrary({cloud,onChoose,onImported}){
 const [result,setResult]=useState(null),[filters,setFilters]=useState({kind:'questions',subject:'',grade:'',query:'',page:0}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 async function load(next=filters){setBusy(true);setError('');try{setResult(await cloud.questionBank({operation:'webLibrary',filters:next}));setFilters(next)}catch(e){setError(e.message)}finally{setBusy(false)}}
 function choose(row){if(row.preparation){onChoose(structuredClone(row.preparation.record));return}onChoose({grade:'',subject:row.subject,unit:'',textbook:'',semester:'',difficulty:'一般',tags:[],source:`iKala TMMLU+／${row.subset}／${row.split} CSV第${row.row}列`,url:row.sourceUrl,rights:'發布者聲明 MIT License；保留 iKala TMMLU+ 來源及授權聲明。原始資料未標逐題年級、單元或詳解，須教師補齊核對。',question:structuredClone(row.question)});}
 return <section className="panel web-library"><h2>網路題庫資料庫</h2><p>已下載的文字題目與外部試卷來源分開列出。網路題目尚未完成課綱對應及教師審核，AI 整理提供建議年級、單元與詳解，仍須教師確認。</p>
 {!result?<button type="button" disabled={busy} onClick={()=>load({...filters,kind:'prepared'})}>瀏覽已收集的網路題庫</button>:<>
 <p className="notice">資料已補齊 {result.summary.preparedQuestions} 題（待教師審核）、缺詳解或範圍待核 {result.summary.draftQuestions||0} 題、有疑義 {result.summary.disputedQuestions} 題；國中 AI 整理進度 {result.summary.processedQuestions}/{result.summary.stagedQuestions}；另有 {result.summary.elementaryQuestions} 題國小原卷拆題。<br/>新來源已拆 {result.summary.supplementalQuestions||0} 題 · 已檢查 {result.summary.sourcePdfs||0} 份 PDF（{result.summary.sourcePdfPages||0} 頁），另有 {result.summary.heldPdfBlocks||0} 個題目區塊因圖表、版面或上下文需人工處理。<br/>{result.summary.stagedQuestions} 題原有來源文字題 · {result.summary.officialResources} 筆官方試卷來源 · 尚未完整涵蓋三至九年級全科。這些數量不代表已審核題目。</p>
 <div className="button-row"><button type="button" disabled={busy||!result.summary.preparedQuestions} onClick={async()=>{setBusy(true);setError('');try{const r=await cloud.questionBank({operation:'importPrepared'});setNotice(`已加入 ${r.imported} 題待審核、更新 ${r.updated||0} 題尚未手動修改的草稿，略過 ${r.skipped} 題重複；請核對AI建議年級與詳解後審核。`);await onImported?.()}catch(e){setError(e.message)}finally{setBusy(false)}}}>將資料已補齊的題目加入待審核題庫</button><button type="button" disabled={busy||(result.summary.processedQuestions>=result.summary.stagedQuestions&&!result.summary.draftQuestions)} onClick={async()=>{setBusy(true);setError('');try{const r=await cloud.questionBank({operation:'prepareWebBatch'});setNotice(`本批處理 ${r.processed} 題，${r.prepared||0} 題已補資料，${r.needsCheck||0} 題需核對；每批使用1次Gemini，不會自動審核。`);await load()}catch(e){setError(e.message)}finally{setBusy(false)}}}>用 AI 接續整理下一批（最多20題）</button><button type="button" disabled={busy||!result.summary.draftQuestions} onClick={async()=>{setBusy(true);setError('');try{const r=await cloud.questionBank({operation:'importDrafts'});setNotice(`已加入 ${r.imported} 題待補詳解草稿，略過 ${r.skipped} 題重複；可先組卷，補齊並確認前不可發布給學生。`);await onImported?.()}catch(e){setError(e.message)}finally{setBusy(false)}}}>將待補資料草稿加入題庫</button></div>{notice&&<p role="status">{notice}</p>}
 <div className="form-grid"><label className="field"><span>資料類型</span><select value={filters.kind} disabled={busy} onChange={e=>load({...filters,kind:e.target.value,page:0})}><option value="prepared">已整理（待教師審核）</option><option value="drafts">已拆題（待補詳解或範圍）</option><option value="issues">答案或資料有疑義</option><option value="papers">原卷處理進度（含缺圖／題組）</option><option value="questions">原始國中文字題（年級待核）</option><option value="sources">外部試卷來源（三至九年級）</option></select></label><label className="field"><span>網路題庫科目</span><select value={filters.subject} disabled={filters.kind==='papers'} onChange={e=>setFilters({...filters,subject:e.target.value,page:0})}><option value="">全部科目</option>{SUBJECTS.map(x=><option key={x}>{x}</option>)}</select></label>{filters.kind==='sources'&&<label className="field"><span>來源年級</span><select value={filters.grade} onChange={e=>setFilters({...filters,grade:e.target.value,page:0})}><option value="">全部年級</option>{[3,4,5,6,7,8,9].map(g=><option key={g} value={g}>{g<=6?'國小'+g:'國中'+(g-6)}年級</option>)}</select></label>}<label className="field"><span>網路題庫關鍵字</span><input maxLength={100} value={filters.query} onChange={e=>setFilters({...filters,query:e.target.value,page:0})}/></label></div>
 <button type="button" disabled={busy} onClick={()=>load({...filters,page:0})}>搜尋網路題庫資料</button>
 <div className="assignment-grid">{result.records.map(r=><article className="assignment panel" key={r.id}>{result.kind==='papers'?<><h3>{r.title}</h3><p>{r.pages} 頁 · 已拆出 {r.parsedQuestions} 題 · {r.heldBlocks} 個區塊需人工核對</p><p>{r.reason||'完成可獨立文字題拆分，答案與單元仍須教師審核。'}</p>{r.reasons.length>0&&<details><summary>查看未自動拆題原因</summary><ul>{r.reasons.map(reason=><li key={reason}>{reason}</li>)}</ul></details>}<p className="fine">{r.rights}</p><a href={r.url} target="_blank" rel="noreferrer">查看原卷（含圖片與題組） ↗</a></>:result.kind!=='sources'?<><span className="assessment-status pending">{r.preparation?r.preparation.status==='prepared'?'資料已補齊 · 待教師審核':r.preparation.status==='draft'?'已拆題 · 待補詳解／範圍':'需核對疑義':'年級／單元／詳解待整理'}</span><p>{r.subject} · 原資料範圍：{r.originalRange||'國中'}</p>{r.preparation?.notice&&<p className="fine">{r.preparation.notice}</p>}{r.preparation&&<p>建議範圍：{r.preparation.record.grade} · {r.preparation.record.unit}{r.preparation.issue&&<><br/>待核對：{r.preparation.issue}（AI答案 {r.preparation.aiSuggestedAnswer}，來源答案 {r.preparation.originalAnswer}）</>}</p>}<p className="bank-prompt">{r.question.prompt}</p><details><summary>查看選項與來源答案</summary>{(r.question.options||[]).map((x,i)=><p key={i}>{'ABCD'[i]}. {x}</p>)}<p>{r.answerOrigin||'資料集答案'}：{r.question.answer}（仍需核對）</p><p>{r.preparation?(r.preparation.record.question.explanation?'詳解草稿：'+r.preparation.record.question.explanation:'原來源未附完整詳解，尚待補齊並核對。'):'原資料未提供詳解。可用AI整理後再由教師核對，並非官方詳解。'}</p><a href={r.sourceUrl} target="_blank" rel="noreferrer">原始來源 ↗</a></details><button type="button" onClick={()=>choose(r)}>選取此題，補齊資料</button></>:<><h3>{r.title}</h3><p>{r.listings.map(x=>x.label).join('、')}</p><p>授權：{r.license||'尚待查閱'}</p><p>{r.requiresLogin?'來源提示下載需登入。':''}這是外部試卷連結，尚未拆成可出題的逐題資料。</p><a href={r.url} target="_blank" rel="noreferrer">開啟官方來源 ↗</a></>}</article>)}</div>
 {!result.total&&<p>目前收集的資料中沒有符合項目；這不表示網路上完全沒有題庫。</p>}
 <div className="button-row"><button type="button" disabled={busy||result.page===0} onClick={()=>load({...filters,page:result.page-1})}>網路題庫上一頁</button><span>共 {result.total} 筆 · 第 {result.page+1} 頁</span><button type="button" disabled={busy||(result.page+1)*20>=result.total} onClick={()=>load({...filters,page:result.page+1})}>網路題庫下一頁</button></div>
 <details><summary>其他已確認的題庫入口</summary>{result.portals.map(p=><p key={p.id}><a href={p.url} target="_blank" rel="noreferrer">{p.title} ↗</a>：{p.note}</p>)}</details>
 </>}{busy&&<p role="status">載入網路題庫資料…</p>}{error&&<p role="alert">{error}</p>}</section>;
}
