import React,{useState} from 'react';
import {SUBJECTS} from '../functions/domain.mjs';
export default function WebQuestionLibrary({cloud,onChoose}){
 const [result,setResult]=useState(null),[filters,setFilters]=useState({kind:'questions',subject:'',grade:'',query:'',page:0}),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function load(next=filters){setBusy(true);setError('');try{setResult(await cloud.questionBank({operation:'webLibrary',filters:next}));setFilters(next)}catch(e){setError(e.message)}finally{setBusy(false)}}
 function choose(row){onChoose({grade:'',subject:row.subject,unit:'',textbook:'',semester:'',difficulty:'一般',tags:[],source:`iKala TMMLU+／${row.subset}／${row.split} CSV第${row.row}列`,url:row.sourceUrl,rights:'發布者聲明 MIT License；保留 iKala TMMLU+ 來源及授權聲明。原始資料未標逐題年級、單元或詳解，須教師補齊核對。',question:structuredClone(row.question)});}
 return <section className="panel web-library"><h2>網路題庫資料庫</h2><p>已下載的文字題目與外部試卷來源分開列出。網路題目尚未完成課綱對應及教師審核，選取後請指定年級、單元並補寫詳解。</p>
 {!result?<button type="button" disabled={busy} onClick={()=>load()}>瀏覽已收集的網路題庫</button>:<>
 <p className="notice">{result.summary.stagedQuestions} 題待整理文字題 · {result.summary.officialResources} 筆官方試卷來源 · 尚未完整涵蓋三至九年級全科。這些數量不代表已審核題目。</p>
 <div className="form-grid"><label className="field"><span>資料類型</span><select value={filters.kind} disabled={busy} onChange={e=>load({...filters,kind:e.target.value,page:0})}><option value="questions">已下載文字題（國中範圍，年級待核）</option><option value="sources">外部試卷來源（三至九年級）</option></select></label><label className="field"><span>網路題庫科目</span><select value={filters.subject} onChange={e=>setFilters({...filters,subject:e.target.value,page:0})}><option value="">全部科目</option>{SUBJECTS.map(x=><option key={x}>{x}</option>)}</select></label>{filters.kind==='sources'&&<label className="field"><span>來源年級</span><select value={filters.grade} onChange={e=>setFilters({...filters,grade:e.target.value,page:0})}><option value="">全部年級</option>{[3,4,5,6,7,8,9].map(g=><option key={g} value={g}>{g<=6?'國小'+g:'國中'+(g-6)}年級</option>)}</select></label>}<label className="field"><span>網路題庫關鍵字</span><input maxLength={100} value={filters.query} onChange={e=>setFilters({...filters,query:e.target.value,page:0})}/></label></div>
 <button type="button" disabled={busy} onClick={()=>load({...filters,page:0})}>搜尋網路題庫資料</button>
 <div className="assignment-grid">{result.records.map(r=><article className="assignment panel" key={r.id}>{result.kind==='questions'?<><span className="assessment-status pending">年級／單元／詳解待整理</span><p>{r.subject} · 原資料範圍：國中</p><p className="bank-prompt">{r.question.prompt}</p><details><summary>查看選項與來源答案</summary>{r.question.options.map((x,i)=><p key={i}>{'ABCD'[i]}. {x}</p>)}<p>資料集答案：{r.question.answer}（仍需核對）</p><p>原資料未提供詳解，不會以 AI 猜測內容冒充原始詳解。</p><a href={r.sourceUrl} target="_blank" rel="noreferrer">原始 CSV 與固定版本 ↗</a></details><button type="button" onClick={()=>choose(r)}>選取此題，補齊資料</button></>:<><h3>{r.title}</h3><p>{r.listings.map(x=>x.label).join('、')}</p><p>授權：{r.license||'尚待查閱'}</p><p>{r.requiresLogin?'來源提示下載需登入。':''}這是外部試卷連結，尚未拆成可出題的逐題資料。</p><a href={r.url} target="_blank" rel="noreferrer">開啟官方來源 ↗</a></>}</article>)}</div>
 {!result.total&&<p>目前收集的資料中沒有符合項目；這不表示網路上完全沒有題庫。</p>}
 <div className="button-row"><button type="button" disabled={busy||result.page===0} onClick={()=>load({...filters,page:result.page-1})}>網路題庫上一頁</button><span>共 {result.total} 筆 · 第 {result.page+1} 頁</span><button type="button" disabled={busy||(result.page+1)*20>=result.total} onClick={()=>load({...filters,page:result.page+1})}>網路題庫下一頁</button></div>
 <details><summary>其他已確認的題庫入口</summary>{result.portals.map(p=><p key={p.id}><a href={p.url} target="_blank" rel="noreferrer">{p.title} ↗</a>：{p.note}</p>)}</details>
 </>}{busy&&<p role="status">載入網路題庫資料…</p>}{error&&<p role="alert">{error}</p>}</section>;
}
