import {createServer} from 'node:http';
import {readFile} from 'node:fs/promises';
import {resolve,sep,extname} from 'node:path';
export function classroomHttp(service,{webRoot,port=4180,publicOrigin=''}){
 const local=`http://127.0.0.1:${port}`,origins=new Set([local,`http://localhost:${port}`,...(publicOrigin?[new URL(publicOrigin).origin]:[])]),hosts=new Set([...origins].map(x=>new URL(x).host));const root=resolve(webRoot);const types={'.html':'text/html; charset=utf-8','.js':'text/javascript','.css':'text/css','.glb':'model/gltf-binary','.svg':'image/svg+xml','.png':'image/png','.wasm':'application/wasm'};
 return createServer(async(req,res)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','no-referrer');res.setHeader('X-Frame-Options','DENY');res.setHeader('Cache-Control','no-store');const send=(status,value)=>{res.writeHead(status,{'Content-Type':'application/json'});res.end(JSON.stringify(value))};if(!hosts.has(req.headers.host))return send(403,{error:'無效的主機名稱'});const url=new URL(req.url,local);
 if(url.pathname==='/api/meta'&&req.method==='GET')return send(200,{setupRequired:!!service.setupCode,publicOrigin});
 if(url.pathname.startsWith('/api/')){if(req.method!=='POST'||!origins.has(req.headers.origin)||!String(req.headers['content-type']).startsWith('application/json'))return send(403,{error:'不允許的請求來源'});try{const chunks=[];let bytes=0;for await(const chunk of req){bytes+=chunk.length;if(bytes>(['/api/questionBank','/api/classroomAction'].includes(url.pathname)?1000000:100000))return send(413,{error:'內容太大'});chunks.push(chunk)}const raw=Buffer.concat(chunks).toString('utf8');let data;try{data=JSON.parse(raw)}catch{return send(400,{error:'格式錯誤'})}const name=url.pathname.slice(5);const token=(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('tc-session='))?.slice(11)||'';const result=await service.call(name,data,token,'web');if(result?.token){res.setHeader('Set-Cookie',`tc-session=${result.token}; HttpOnly; SameSite=Strict; Path=/; Max-Age=28800${req.headers.origin.startsWith('https:')?'; Secure':''}`);return send(200,{ok:true})}if(name==='logout')res.setHeader('Set-Cookie','tc-session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0');return send(200,result)}catch(e){return send(e.status||400,{error:e.status||e.code?e.message:'操作無法完成，請重試'})}}
 if(!['GET','HEAD'].includes(req.method))return send(405,{error:'不支援此方法'});try{let path=decodeURIComponent(url.pathname);if(path==='/')path='/index.html';const file=resolve(root,'.'+path);if(!file.startsWith(root+sep))return send(403,{error:'不允許的路徑'});const body=await readFile(file);res.writeHead(200,{'Content-Type':types[extname(file)]||'application/octet-stream'});res.end(req.method==='HEAD'?undefined:body)}catch{send(404,{error:'找不到頁面'})}
 });
}
