import {DatabaseSync,backup} from 'node:sqlite';
import {randomBytes,scrypt as derive,createCipheriv,createDecipheriv,createHash} from 'node:crypto';
import {promisify} from 'node:util';
import {mkdirSync,existsSync,readFileSync,writeFileSync,unlinkSync,copyFileSync,rmSync,mkdtempSync,renameSync,statSync,readdirSync} from 'node:fs';
import {join,resolve} from 'node:path';
import {tmpdir} from 'node:os';
import {fileURLToPath} from 'node:url';
import {birthdayHash,birthdayMatches} from '../functions/student-credentials.mjs';
import {atomicJSON,readErasures,applyErasures,purgeManagedBackups,syncFile,syncDirectory} from './data-lifecycle.mjs';
const scrypt=promisify(derive),limit=100*1024*1024;
const hash=b=>createHash('sha256').update(b).digest('hex');
function password(p){if(typeof p!=='string'||p.length<8||p.length>128)throw Error('密碼需為 8–128 字元')}
function readState(db){const row=db.prepare("SELECT value FROM settings WHERE id='classroom'").get();if(!row)throw Error('不是有效的教室資料');const s=JSON.parse(row.value);if(!s.teacher?.uid||!s.teacher.hash||!s.workspace||!Array.isArray(s.workspace.students)||!Array.isArray(s.workspace.classes))throw Error('不是有效的教室資料');return s}
function saveState(db,s){db.prepare("UPDATE settings SET value=? WHERE id='classroom'").run(JSON.stringify(s))}
export function acquireDataLock(directory){mkdirSync(directory,{recursive:true,mode:0o700});const path=join(directory,'server.lock');if(existsSync(path)){const pid=Number(readFileSync(path,'utf8'));let live=true;if(Number.isInteger(pid)&&pid>0)try{process.kill(pid,0)}catch(e){if(e.code==='ESRCH')live=false}if(live)throw Error('教室服務仍在執行，請先自行停止服務');unlinkSync(path)}writeFileSync(path,String(process.pid),{flag:'wx',mode:0o600});return()=>{try{if(readFileSync(path,'utf8')===String(process.pid))unlinkSync(path)}catch{}}}
// A durable rollback journal covers the two-file DB/key replacement. On an
// interrupted restore the next start always returns to the previous pair.
function cleanupStages(directory){for(const entry of readdirSync(directory,{withFileTypes:true}))if(entry.isDirectory()&&/^(restore|backup)-stage-[A-Za-z0-9]{6}$/.test(entry.name))rmSync(join(directory,entry.name),{recursive:true,force:true});for(const name of ['classroom.sqlite','server.key'])rmSync(join(directory,'restore-old-'+name),{force:true})}
export function recoverInterruptedRestore(directory){const path=join(directory,'restore-journal.json');if(!existsSync(path)){cleanupStages(directory);return}const j=JSON.parse(readFileSync(path,'utf8'));if(j.version!==1)throw Error('還原紀錄無法辨識，請保留資料');for(const name of ['classroom.sqlite','server.key']){const old=join(directory,'restore-old-'+name),target=join(directory,name);if(j.hadData){if(!existsSync(old))throw Error('還原回退檔缺失，請勿啟動');copyFileSync(old,target);syncFile(target)}else rmSync(target,{force:true})}for(const suffix of ['-wal','-shm'])rmSync(join(directory,'classroom.sqlite'+suffix),{force:true});rmSync(path);syncDirectory(directory);cleanupStages(directory)}

async function verifyTeacher(directory,passwordValue){password(passwordValue);if(!existsSync(join(directory,'classroom.sqlite')))throw Error('尚未建立教師帳號');const db=new DatabaseSync(join(directory,'classroom.sqlite'));try{const s=readState(db);if(!await birthdayMatches(passwordValue,readFileSync(join(directory,'server.key')),s.teacher))throw Error('老師密碼不正確');return s}finally{db.close()}}
async function newRecovery(directory,owner,key){const code=randomBytes(20).toString('hex').toUpperCase().match(/.{1,5}/g).join('-');atomicJSON(join(directory,'recovery.json'),{owner,...await birthdayHash(code.replace(/-/g,''),key),createdAt:Date.now()});return code}
async function decryptBackup(file,pass){password(pass);if(statSync(file).size>limit*2)throw Error('備份超過支援大小');let pack;try{pack=JSON.parse(readFileSync(file,'utf8'));if(pack.format!=='learning-claw-encrypted-v1'||typeof pack.salt!=='string'||!/^[a-f0-9]{32}$/.test(pack.salt)||!/^[a-f0-9]{24}$/.test(pack.iv)||!/^[a-f0-9]{32}$/.test(pack.tag)||typeof pack.data!=='string'||pack.data.length>limit*2)throw Error();const key=await scrypt(pass,Buffer.from(pack.salt,'hex'),32);const decipher=createDecipheriv('aes-256-gcm',key,Buffer.from(pack.iv,'hex'));decipher.setAAD(Buffer.from(pack.format));decipher.setAuthTag(Buffer.from(pack.tag,'hex'));const data=JSON.parse(Buffer.concat([decipher.update(Buffer.from(pack.data,'base64')),decipher.final()]).toString('utf8'));if(data.version!==1||typeof data.database!=='string'||typeof data.key!=='string'||data.key.length!==64||!/^[a-f0-9]+$/.test(data.key))throw Error();const bytes=Buffer.from(data.database,'base64');if(bytes.length>limit||hash(bytes)!==data.digest||bytes.subarray(0,16).toString()!=='SQLite format 3\0')throw Error();return {...data,bytes,fingerprint:hash(readFileSync(file))}}catch{throw Error('備份密碼不正確、檔案損壞或版本不支援')}}
function stagedBackup(directory,data){const temp=mkdtempSync(join(directory,'restore-stage-'));try{writeFileSync(join(temp,'classroom.sqlite'),data.bytes,{mode:0o600});writeFileSync(join(temp,'server.key'),Buffer.from(data.key,'hex'),{mode:0o600});const db=new DatabaseSync(join(temp,'classroom.sqlite'));try{if(db.prepare('PRAGMA integrity_check').get().integrity_check!=='ok')throw Error('備份資料庫損壞');const s=readState(db);if(s.workspace.version!==1)throw Error('備份格式較新，請先更新程式');const erasures=[...readErasures(directory),...(Array.isArray(data.erasures)?data.erasures:[])];applyErasures(s,erasures);s.open=false;s.rates={};saveState(db,s);return {temp,state:s,erasures}}finally{db.close()}}catch(e){rmSync(temp,{recursive:true,force:true});throw e}}
export async function maintenance({directory,operation,password:currentPassword,backupPassword,code,newPassword,file,revision,confirmed}){
 const release=acquireDataLock(directory);let temp;
 try{recoverInterruptedRestore(directory);
  if(!['issueRecovery','resetPassword','exportBackup','previewRestore','restoreBackup'].includes(operation))throw Error('不支援的資料管理操作');
  // Persistent attempt limit also covers repeated launches of this offline utility.
  const ratePath=join(directory,'maintenance-rate.json');let rate=existsSync(ratePath)?JSON.parse(readFileSync(ratePath,'utf8')):{at:Date.now(),count:0};if(Date.now()-rate.at>15*60000)rate={at:Date.now(),count:0};if(rate.count>=10)throw Error('嘗試次數過多，請 15 分鐘後重試');atomicJSON(ratePath,{...rate,count:rate.count+1});
  const existing=existsSync(join(directory,'classroom.sqlite'));let state;
  if(operation==='resetPassword'){
   password(newPassword);if(typeof code!=='string'||code.length>100)throw Error('請填寫復原碼');const p=join(directory,'recovery.json');if(!existsSync(p))throw Error('尚未建立復原碼，無法重設密碼');const row=JSON.parse(readFileSync(p,'utf8')),key=readFileSync(join(directory,'server.key'));const db=new DatabaseSync(join(directory,'classroom.sqlite'));try{state=readState(db);if(row.owner!==state.teacher.uid||!await birthdayMatches(code.replace(/[-\s]/g,'').toUpperCase(),key,row))throw Error('復原碼不正確或已失效');const next=await birthdayHash(newPassword,key);const recoveryCode=await newRecovery(directory,state.teacher.uid,key);state.teacher={...state.teacher,...next};state.rates={};state.open=false;saveState(db,state);rmSync(ratePath,{force:true});return {recoveryCode,message:'密碼已重設，舊復原碼已失效。請保存新復原碼。'}}finally{db.close()}
  }
  if(existing)state=await verifyTeacher(directory,currentPassword);else if(!['previewRestore','restoreBackup'].includes(operation))throw Error('尚未建立教師帳號');
  if(operation==='issueRecovery'){const recoveryCode=await newRecovery(directory,state.teacher.uid,readFileSync(join(directory,'server.key')));rmSync(ratePath,{force:true});return {recoveryCode,message:'請將復原碼另行保存；舊復原碼已失效。'}}
  if(operation==='exportBackup'){
   password(backupPassword);if(!file||existsSync(file))throw Error('請選擇新的備份檔名，避免覆寫既有備份');temp=mkdtempSync(join(directory,'backup-stage-'));const db=new DatabaseSync(join(directory,'classroom.sqlite'));try{applyErasures(state,readErasures(directory));saveState(db,state);await backup(db,join(temp,'classroom.sqlite'))}finally{db.close()}
   const bytes=readFileSync(join(temp,'classroom.sqlite'));if(bytes.length>limit)throw Error('資料超過本版 100 MB 備份限制');const payload={version:1,createdAt:Date.now(),database:bytes.toString('base64'),digest:hash(bytes),key:readFileSync(join(directory,'server.key')).toString('hex'),erasures:readErasures(directory)};const salt=randomBytes(16),iv=randomBytes(12),key=await scrypt(backupPassword,salt,32),cipher=createCipheriv('aes-256-gcm',key,iv),format='learning-claw-encrypted-v1';cipher.setAAD(Buffer.from(format));const encrypted=Buffer.concat([cipher.update(JSON.stringify(payload)),cipher.final()]);writeFileSync(file,JSON.stringify({format,salt:salt.toString('hex'),iv:iv.toString('hex'),tag:cipher.getAuthTag().toString('hex'),data:encrypted.toString('base64')}),{flag:'wx',mode:0o600});atomicJSON(join(directory,'backup-status.json'),{at:payload.createdAt,bytes:statSync(file).size});rmSync(ratePath,{force:true});return {message:'加密備份已匯出，請分開保存備份與密碼。'};
  }
  const data=await decryptBackup(file,backupPassword),staged=stagedBackup(directory,data);temp=staged.temp;if(state&&state.teacher.uid!==staged.state.teacher.uid)throw Error('此備份屬於不同教師工作區，不能覆蓋目前資料');
  if(operation==='previewRestore'){rmSync(ratePath,{force:true});return {createdAt:data.createdAt,classes:staged.state.workspace.classes.length,students:staged.state.workspace.students.length,revision:data.fingerprint,message:'還原會取代目前課堂資料、清除管理中的舊備份，並產生新復原碼；依本機與備份所帶的刪除紀錄排除資料。若在全新電腦使用刪除前的舊備份，無法得知後來的刪除，請改用最新備份。'}}
  if(confirmed!==true||revision!==data.fingerprint)throw Error('請先預覽這份備份並確認還原');
  // Preserve the deletion ledger before swapping; a rollback must not resurrect data.
  atomicJSON(join(directory,'erasures.json'),staged.erasures);
  for(const name of ['classroom.sqlite','server.key'])if(existing){copyFileSync(join(directory,name),join(directory,'restore-old-'+name));syncFile(join(directory,'restore-old-'+name))}
  atomicJSON(join(directory,'restore-journal.json'),{version:1,hadData:existing});
  try{for(const suffix of ['-wal','-shm'])rmSync(join(directory,'classroom.sqlite'+suffix),{force:true});for(const name of ['classroom.sqlite','server.key']){copyFileSync(join(temp,name),join(directory,name));syncFile(join(directory,name))}const recoveryCode=await newRecovery(directory,staged.state.teacher.uid,Buffer.from(data.key,'hex'));purgeManagedBackups(directory);rmSync(join(directory,'restore-journal.json'));syncDirectory(directory);for(const name of ['classroom.sqlite','server.key'])rmSync(join(directory,'restore-old-'+name),{force:true});rmSync(ratePath,{force:true});return {recoveryCode,message:'還原完成，請保存新復原碼。使用備份中的老師密碼登入；教室維持下課。'}}catch(e){recoverInterruptedRestore(directory);throw e}
 }finally{if(temp)rmSync(temp,{recursive:true,force:true});release()}
}
if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url)){let input='';try{for await(const part of process.stdin){input+=part;if(input.length>20000)throw Error('內容過大')}const result=await maintenance(JSON.parse(input));process.stdout.write(JSON.stringify({result}))}catch(error){process.stdout.write(JSON.stringify({error:error.message}));process.exitCode=1}}
